- modules/core/package.json
- modules/core/src/common/file-utils/loader.js
- modules/core/src/common/file-utils/smart-fetch.js
- modules/core/src/formats/csv-loader/csv-loader.js
- modules/core/src/index.js
- modules/draco/src/index.js
- package.json
- test/modules/draco/draco-encoder.spec.js
- test/modules/draco/draco-loader.spec.js
- test/webpack.config.js
- yarn.lock
- Remove `d3-request`, use `fetch` instead
- Remove non-browser dependency `path`
- Fix an invalid export
- Consistent naming for draco submodule (the code base uses `DRACO*` and `Draco*` 50-50 and the official documentation uses `Draco`)
> Dependency issues fixes

- test/bench/draco.bench.js
- test/bench/index.js
- test/start.js
Node:
Draco Encode/Decode
├─ DracoEncoder#encode point cloud#quantization=10: 3.68 iterations/s
├─ DracoDecoder#decode point cloud#quantization=10: 2.71 iterations/s
├─ DracoEncoder#encode point cloud#quantization=14: 3.34 iterations/s
├─ DracoDecoder#decode point cloud#quantization=14: 2.88 iterations/s
Browser:
Draco Encode/Decode
├─ DracoEncoder#encode point cloud#quantization=10: 3.65 iterations/s
├─ DracoDecoder#decode point cloud#quantization=10: 2.85 iterations/s
├─ DracoEncoder#encode point cloud#quantization=14: 2.83 iterations/s
├─ DracoDecoder#decode point cloud#quantization=14: 2.78 iterations/s
> Add Draco point cloud benchmarks

- docs/api-reference/loaders/pcd-loader.md
Replaced `PCFDoader` by `PCDLoader` in usage example
> Fix PCD docs typo

- modules/core/src/parse-file/parse-with-loader.js
- modules/gltf/scripts/glbdump.js
- modules/gltf/src/glb/glb-builder.js
- modules/gltf/src/gltf/gltf-builder.js
- modules/gltf/src/gltf/gltf-loader.js
- modules/gltf/test/glb/glb-builder.spec.js
- modules/gltf/test/gltf/gltf-builder.spec.js
- modules/gltf/test/gltf/gltf-loader.spec.js
- modules/gltf/test/gltf/index.js
GLTFBuilder API retains the addImage() method, but it is implemented
at the GLTF layer rather than in the GLBBuilder.
The GLTFBuilder is responsible for adding the BufferView, then
passing that bufferViewIndex to create the images entry.
Currently the 'images' entry is managed by the GLBBuilder, but
eventually that can move to the GLTFBuilder as well.
- remove addApplicationData() from GLTF as it was a duplicate of the
GLBBuilder, and the GLBBuilder currently manages the json object
- Fix bug in addApplicationData() that did not set the key value if
the option 'nopack' was 'true'
> Fix addImage() on GLTFBuilder

- modules/arrow/package.json
- modules/images/package.json
This is was required when publishing 0.6.2
> add publishConfig to arrow & images modules

- aliases.js
- babel.config.js
- modules/draco/package.json
- modules/las/package.json
- modules/obj/package.json
- modules/ply/package.json
- package.json
- scripts/worker-webpack-config.js
- test/start.js
- yarn.lock
This issue has been preventing the update of deck.gl examples to use loaders.gl.
> Fix missing "regenerator" support in workers

- modules/gltf/src/glb/glb-builder.js
- Chunk type is supposed to be a 4 byte magic number: ASCII "JSON" or "BIN\0". See https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#chunks
- Added proper padding after chunks (spaces after json, zeroes after binary)
> Fix chunk headers in GLB file writer

- modules/core/src/image-utils/image-loaders.js
Using utf8 in data URL fails in the latest Chrome.
> Safe svg loading

- docs/api-reference/gltf-loaders/gltf-loader.md
- docs/api-reference/gltf-loaders/gltf-parser.md
- docs/whats-new.md
- modules/gltf/scripts/glbdump.js
- modules/gltf/src/glb/glb-parser.js
- modules/gltf/src/gltf/gltf-loader.js
- modules/gltf/src/gltf/gltf-parser.js
- modules/gltf/src/gltf/gltf-post-processor.js
- modules/gltf/test/glb/index.js
- modules/gltf/test/gltf/gltf-draco.spec.js
- modules/gltf/test/gltf/gltf-loader.spec.js
- modules/gltf/test/gltf/index.js
- modules/gltf/test/index.js
- modules/gltf/test/packed-json/index.js
This will be breaking change for v0.8 (Note: not breaking if using GLTFLoader, just GLTFParser).
Partial step for support for official Khronos Draco extension.
> GLTF API improvements

- docs/api-reference/gltf-loaders/glb-builder.md
- docs/api-reference/gltf-loaders/gltf-builder.md
- docs/api-reference/gltf-loaders/gltf-extensions.md
- docs/api-reference/gltf-loaders/gltf-loader.md
- docs/api-reference/gltf-loaders/gltf-writer.md
- docs/whats-new.md
- lerna.json
- modules/gltf/scripts/glbdump.js
- modules/gltf/src/glb/glb-builder.js
- modules/gltf/src/glb/glb-parser.js
- modules/gltf/src/glb/gltf-types.js
- modules/gltf/src/gltf/gltf-builder.js
- modules/gltf/src/gltf/gltf-constants.js
- modules/gltf/src/gltf/gltf-parser.js
- modules/gltf/src/gltf/gltf-post-processor.js
- modules/gltf/src/index.js
- modules/gltf/test/glb/glb-builder.spec.js
- modules/gltf/test/glb/glb-custom-payload.spec.js
- modules/gltf/test/glb/glb-encode-parse.spec.js
- modules/gltf/test/glb/glb-encoder-decoder.spec.js
- modules/gltf/test/glb/glb-parser.spec.js
- modules/gltf/test/gltf/gltf-draco.spec.js
- modules/gltf/test/gltf/gltf-loader.spec.js
- modules/gltf/test/gltf/gltf-roundtrip.spec.js
- test/modules.js
> GLTF Draco Integration Improvements

- docs/api-reference/gltf-loaders/gltf-extensions.md
- docs/api-reference/gltf-loaders/gltf-parser.md
- modules/gltf/src/gltf/gltf-post-processor.js
- modules/gltf/test/gltf/gltf-post-processor.spec.js
- modules/gltf/test/index.js
Since we are adding light support to luma.gl v7 we can support glTF lights. And by doing so we make sure our lights support the "right" set of parameters from the start.
See [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual)
This parse code just removes the extension objects from the glTF JSON and makes it look like the light info is a natural part of the "node".
> Add parser support for KHR_lights_punctual glTF extension

- docs/api-reference/core/load-file.md
- docs/api-reference/core/parse-file.md
- docs/api-reference/core/register-loaders.md
- modules/arrow/test/arrow-loader.spec.js
- modules/core/src/index.js
- modules/core/src/parse-file/parse-file.js
- modules/core/src/parse-file/register-loaders.js
A lot of doc changes creating noise so I copy the essential doc here
The loader registry allows applications to cherry-pick which loaders to include in their application bundle by importing just the loaders they need and registering them during initialization.
Applications can then make all those imported loaders available (via format autodetection) to all subsequent `parseFile` and `loadFile` calls, without those calls having to specify which loaders to use.
Initialization imports and registers loaders:
```js
import {registerLoaders} from '@loaders.gl/core';
import {CSVLoader} from '@loaders.gl/csv';
registerLoaders(CSVLoader);
```
Some other file that needs to load CSV:
```js
import {loadFile} from '@loaders.gl/core';
// The pre-registered SVLoader gets auto selected based on file …
```
> Add loader registry

- modules/gltf/src/glb/glb-parser.js
Fix referencing undefined this.arrayBuffer instead of this.glbArrayBuffer
Fix ignoring glTFAccessor.byteOffset
Was previously failing to load [Khronos Box sample](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box).
> Fix broken GLB Parser getBuffer()

- modules/gltf/src/glb/glb-parser.js
- modules/gltf/src/glb/parse-glb.js
- modules/gltf/src/index.js
For 3D tiles support, we need to be able to read "embedded" GLB files at any place in the byte stream.
> GLB Parser start on arbitrary byteOffset

- website/ocular-config.js
- website/package.json
- website/src/components/site-query.jsx
For #194 
- Upgrade to ocular-gatsby alpha.26 to fix getting started and github links
- Add list of sibling websites to ocular config to populate dropdown
> Minor website fixes

- modules/3d-tiles/src/tile-3d-loader.js
- modules/3d-tiles/src/tileset/tile-3d-header.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/3d-tiles/test/tileset/tileset-3d.spec.js
- modules/polyfills/src/fetch-node/fetch.node.js
- test/modules.js
Following test now passes:
```js
test('Tileset3D#loads tiles in tileset', async t => {
const tilesetJson = await parse(fetchFile(TILESET_URL), Tileset3DLoader);
const tileset = new Tileset3D(tilesetJson, TILESET_URL);
await tileset.root.loadContent();
t.ok(tileset.root.content);
t.end();
});
```
> 3d-tiles: Tile3DHeader.loadContent() implemented

- modules/loader-utils/src/lib/binary-copy-utils.js
The culprit for the `console.warn()`  is here:
https://github.com/uber-web/loaders.gl/blob/master/modules/polyfills/src/text-encoding/encoding.js#L1125
> Remove argument passed to TextEncoder that causes console.warn() to be called

- examples/pointcloud/components/control-panel.js
- modules/arrow/package.json
- modules/arrow/src/lib/arrow-table-batch.js
- modules/arrow/src/lib/parse-arrow-in-batches.js
- modules/arrow/src/lib/parse-arrow-sync.js
- modules/csv/test/csv-loader-arrow.spec.js
- yarn.lock
@trxcllnt Looks like we need to explicitly import the es5 dist to get apache-arrow working on Node 8, is that expected?
> arrow: Bump apache-arrow to 0.13. Use es5 dist for arrow to unblock Node 8.

- examples/3d-tiles/tile-3d-layer.js
- modules/3d-tiles/src/tileset/tileset-3d-traverser.js
Fixed issue with loading roots. Roots are culled if they are too far away from camera. The fix is hacky and the better solution is moving the camera to the newly selected asset from the dropdown menu.
Fixed issue with Matrix4 api call to include the output parameter since that one worked.
Fixed issue where layer.visible was moved to layer.props.visible.
> 3d-tiles: Fix traversal issues

- modules/3d-tiles/src/tileset/helpers/bounding-volume.js
Allows camera to re-focus on asset change. Due to some issue with the non-output parameter version of `transform` center was undefined.
> Camera focus on asset change

- examples/3d-tiles/tile-3d-layer.js
- modules/3d-tiles/src/tileset/tileset-3d.js
@loshjawrence Attempt to convert `cameraPosition, cameraDirection, cameraUp` to WGS84 cartesian coordinates.
> 3d-tiles: Convert camera parameters to WGS84 cartesian

- examples/3d-tiles/tile-3d-layer.js
- modules/3d-tiles/src/tileset/tile-3d-header.js
- modules/3d-tiles/src/tileset/tileset-3d-cache.js
- modules/3d-tiles/src/tileset/tileset-3d-traverser.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/3d-tiles/src/utils/doubly-linked-list-node.js
- modules/3d-tiles/src/utils/doubly-linked-list.js
- yarn.lock
Adds a tileset3d cache to clean up _content from tiles that weren't traversed this frame. These unloaded tiles are removed from the layer map.
Tested with a budget of 1MB on st helens to trigger the codes paths make sure things behaved as expected.
This is port of the cesium impl.
> Cleanup old tile._content

- docs/api-reference/image-loaders/image-loader.md
- modules/images/src/image-loader.js
- modules/images/src/lib/parse-image.js
Right now the loaded ImageBitmap is flipped if used with `Texture`.
> Add options to ImageBitmapLoader

- babel.config.js
- modules/csv/src/papaparse/papaparse.transpiled.js
Babel's root `env` and `plugins` config are *merged* with `overrides`. The transpiled files end up still being transpiled. This breaks the current las module because the output mixes `import` and `module.exports`.
> Fix babel config for already transpiled files

- modules/images/src/lib/image-parsers.js
- modules/images/test/lib/get-image-metadata.spec.js
Only the first 2 bytes where being tested. This adds a test for
the 1st byte of the second marker.
Validating the End Of Image would make this more robust, but since
it is expected to test on partial data adding that is not reasonable
at this time.
See the added test case for floating point values that encode as the valid
jpeg header values.
> Add additional check for jpeg headers for isImage

- modules/images/src/lib/image-parsers.js
- modules/images/test/lib/get-image-metadata.spec.js
Only the first 2 bytes where being tested. This adds a test for
the 1st byte of the second marker.
Validating the End Of Image would make this more robust, but since
it is expected to test on partial data adding that is not reasonable
at this time.
See the added test case for floating point values that encode as the valid
jpeg header values.
> Add additional check for jpeg headers for isImage (#315)

- docs/api-reference/images/image-loader.md
- modules/images/src/image-loader.js
- modules/images/src/lib/parse-image.js
For #317 
- `ImageLoader` loads to HTML object if possible (best compatibility)
- detect `createImageBitmap` support for options
> Fix image loader in FF

- docs/specifications/category-3d-tiles
- examples/3d-tiles/tile-3d-layer.js
- modules/3d-tiles/src/index.js
- modules/3d-tiles/src/parsers/helpers/normalize-3d-tile-colors.js
- modules/3d-tiles/src/parsers/parse-3d-tile-point-cloud.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/math/src/geometry/colors/rgb565.js
- modules/math/src/geometry/index.js
- modules/math/test/geometry/attributes/compute-vertex-normals.spec.js
- modules/math/test/geometry/colors/rgb565.spec.js
- modules/math/test/geometry/index.js
- modules/math/test/index.js
This starts the cleanup of Tile3DLayer by moving the color parsing into the 3d-tiles module
> 3d-tiles: Move point cloud color parsing into 3d-tiles module

- modules/3d-tiles/src/tileset/tileset-3d-traverser.js
- modules/3d-tiles/src/tileset/tileset-3d.js
@loshjawrence The fact that `Tileset3DTraverser` had full access to `Tileset3D` made these classes highly coupled and it was quite hard for me to follow what was going on.
With this refactor, the traverser no longer gets passed the tileset, but just the root tile and the options.
This works, but I had to disable one line in "cache touching" as we don't have access to the cache, however we can easily restore that to tileset (e.g. with an `onTileTouched` callback or a `touchedTiles` array, or we could pass in the cache).
The cache was not functional anyway as far as I could tell (never unloaded) so this should be OK for now.
Let me know if you have any major concerns before I land.
> 3d-tiles: traverser no longer knows about tileset

- modules/3d-tiles/src/tileset/tile-3d-header.js
- modules/3d-tiles/src/tileset/tileset-3d-cache.js
- modules/3d-tiles/src/tileset/tileset-3d-traverser.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/3d-tiles/test/tileset/tile-3d-header.spec.js
- modules/3d-tiles/test/tileset/tileset-3d.spec.js
- modules/3d-tiles/wip/README.md
This PR:
- adds `tileset.options` and removes the copying of fields from options object into fields of the `Tileset3D` class.
- removes underscore from some publicly accessible fields, and removes accessors.
- in some cases this makes previously constant fields mutable but it removes a lot of code clutter.
@loshjawrence
> 3d-tiles: Tileset3D options refactor

- modules/core/src/lib/parse-with-loader.js
- modules/core/src/lib/parse-with-worker.js
In Chrome 70, workers now have a name attribute, 
```new Worker(url, {name: 'worker name'});```
https://developers.google.com/web/updates/2018/10/nic70
Screenshot with our workers after mapbox workers:
> core: Name workers for debugger

- examples/3d-tiles/app.js
- modules/3d-tiles/src/tileset-3d-loader.js
- modules/3d-tiles/src/tileset/tile-3d-header.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/core/src/lib/loader-utils/auto-detect-loader.js
- modules/core/src/lib/loader-utils/get-data.js
- modules/core/src/lib/parse-with-loader.js
- modules/core/src/lib/parse.js
Slightly big PR, could split it if hard to review:
- Add `Batched3DModel` samples to 3d-tiles example
- Store local `basePath` in `Tile3DHeaders` loaded from "nested" tilesets.
- Move to pure `parse` calls when loading tiles dynamically
- Some cleanup in `Tileset3D` class
>  3d-tiles: Support loading of nested tilesets with local url folders

- examples/3d-tiles/tile-3d-layer/tile-3d-layer.js
- modules/3d-tiles/src/index.js
- modules/3d-tiles/src/request-utils/request-scheduler.js
- modules/3d-tiles/src/tileset/tile-3d-header.js
- modules/3d-tiles/src/tileset/tileset-3d.js
- modules/3d-tiles/test/index.js
- modules/3d-tiles/test/request-utils/request-scheduler.spec.js
- modules/3d-tiles/test/tileset/tileset-3d.spec.js
@loshjawrence - FYI, a minimal naive `RequestScheduler`, as you suggested this seems to dramatically affect performance. 
Now we need testing (and more test cases) to make sure results are correct.
I added a `throttleRequests` option to `Tileset3D` to make it easy to turn on-off. 
@xintongxia - `Tile3dLayer` should probably have a tilesetProps that we pass to `Tileset3D` when we create it...
> 3d-tiles: Add experimental RequestScheduler and throttleRequests option.

- modules/3d-tiles/src/parsers/helpers/normalize-3d-tile-positions.js
- modules/3d-tiles/src/parsers/parse-3d-tile-point-cloud.js
- modules/3d-tiles/src/tileset/helpers/transform-utils.js
Feeding in normalized shorts as position attribute now works in latest 7.3 alpha \o/
> 3d-tiles: Optimize quantized positions: normalized shorts and modelMatrix adjustments

- arrowjs/website/package.json
- website/package.json
Also fixes "full window" examples: https://loaders.gl/examples/3d-tiles
> websites: Update to ocular@1.0.0

- examples/3d-tiles/app.js
- examples/3d-tiles/components/control-panel.js
I am not happy with the `dangerouslySetInnerHTML` part, however since ION return credentials as HTML snippets this is the quickest way to implement it. 
There are modules to sanitize HTML but they are quite big, would prefer not to pull them in.
@Pessimistress 	As you can see this, doesn't look very good, some styling help would make a world of difference...
> 3d-tiles: Show attributions for tilesets loaded from ion.

- docs/api-reference/gltf/glb-loader.md
- docs/api-reference/gltf/glb-writer.md
- docs/api-reference/gltf/gltf-loader.md
- modules/core/src/lib/select-loader.js
- modules/gltf/src/glb-loader.js
- modules/gltf/src/gltf-loader.js
- modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.js
- modules/gltf/src/lib/extensions/extensions.js
- modules/gltf/src/lib/gltf-scenegraph.js
- modules/gltf/src/lib/parse-glb.js
- modules/gltf/src/lib/parse-gltf.js
- modules/gltf/src/lib/post-process-gltf.js
- modules/gltf/test/lib/extensions/KHR_lights_punctual.spec.js
- modules/gltf/test/lib/post-process-gltf.spec.js
This is a round of improvements to the new gltf parser that will become default in loaders.gl v2.
Note that the deprecated gltf v1 parser is still the default when using `GLTFLoader`, so this change should be fairly low risk.
> gltf: Improvements to v2.0 gltf parser

- modules/core/src/lib/select-loader.js
- modules/core/test/lib/select-loader.spec.js
- Typed arrays can have offset which must be observed
- Needed to handle embedded binary formats efficiently (e.g. 3d-tiles with embedded glb payload)
- Broken out of #390 as this is the only core change that is not related to the optional v2 gltf parser.
> core: Fix binary test for typed arrays

- docs/whats-new.md
- examples/3d-tiles/app.js
- examples/3d-tiles/tile-3d-layer/tile-3d-layer.js
- examples/gltf/app.js
- examples/webpack.config.local.js
- modules/gltf/src/gltf-loader.js
- modules/gltf/src/lib/parse-gltf.js
- modules/gltf/test/gltf-loader.spec.js
- modules/gltf/test/gltf-writer.spec.js
Add `gltf.parserVersion` option to enable clear selection of new v2 gltf parser.
V2 parser is gradually being phased in as remaining bugs are ironed out.
> gltf: Add `options.gltf.parserVersion`

- examples/3d-tiles/tile-3d-layer/tile-3d-layer.js
- modules/3d-tiles/src/tileset/tile-3d-header.js
- yarn.lock
The problem is contentUri is a relative to a tileset's base path so it won't be unique identifier in the layerMap. During tile construction we can save off the the full uri and use that as the unique string id for the layerMap.
> 3d-tiles: Use unique string for the key in layerMap

- docs/specifications/loader-object-format.md
- docs/table-of-contents.json
- website/gatsby-config.js
- website/ocular-config.js
@trxcllnt 
Making sure the docs we wrote are hosted on loaders.gl. The previous nested site staging was quite fragile. Hopefully this will inspire us to make the "final push".
> docs: Bring arrow docs into loaders.gl website

- examples/3d-tiles/package.json
- examples/gltf/package.json
- examples/webpack.config.local.js
Maybe some of the webpack.config.local handling could go into ocular-dev-tools?
> examples: Enable debugging with non-transpiled async functions

- examples/3d-tiles-threejs/LICENSE
- examples/3d-tiles-threejs/app.js
- examples/3d-tiles-threejs/index.html
- examples/3d-tiles-threejs/mapbox-3d-tiles-layer/mapbox-3d-tiles-layer.js
- examples/3d-tiles-threejs/mapbox-3d-tiles-layer/web-mercator.js
- examples/3d-tiles-threejs/package.json
- examples/3d-tiles-threejs/threejs-3d-tiles/tile-header.js
- examples/3d-tiles-threejs/threejs-3d-tiles/tile-parsers.js
- examples/3d-tiles-threejs/webpack.config.js
The current port uses loaders.gl to parse the tiles, but does not yet use loaders.gl traversal algorithm, see the pull request for more information.
Next step is to refactor the code to create THREE.js geometries in `onTileLoad` and `onTileUnload` callbacks. 
This is how loaders.gl `Tileset3D.traverse` works, so once that is done, replacing the current traversal with loaders.gl traversal should be relatively painless.
> 3d-tiles: Port Geodan THREE.js example

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-batched-model.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-composite.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-instanced-model.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-point-cloud.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile.js
- modules/3d-tiles/src/tile-3d-loader.js
For complex loaders that (depending on options) also need to do async processing, maintaining sync versions of the parsers doesn't make a lot of sense.
Removal cleans up and minimized code size. 
Technically a breaking change, but sync parsing functionality is already limited enough.
> 3d-tiles: Remove sync parser versions

- modules/3d-tiles/src/lib/tileset/tileset-3d.js
`baseUri` is missing, so the tiles' `fullUri` ended up something like  
`undefined/0/0.b3dm`.
> Fix full uri

- dev-docs/RFCs/v2.0/loader-options-rfc.md
- docs/developer-guide/using-loaders.md
- modules/core/src/lib/load.js
- modules/core/src/lib/loader-utils/loggers.js
- modules/core/src/lib/loader-utils/merge-options.js
- modules/core/src/lib/parse-in-batches-sync.js
- modules/core/src/lib/parse-in-batches.js
- modules/core/src/lib/parse-sync.js
- modules/core/src/lib/parse.js
- modules/core/test/index.js
- modules/core/test/lib/loader-utils/index.js
- modules/core/test/lib/loader-utils/loggers.spec.js
- modules/core/test/lib/loader-utils/merge-options.spec.js
Plumbing towards supporting v2 options objects:
```js
load(url, {
json: {...},
csv: {...},
'3d-tiles': {...},
gltf: {...}
});
```
when working with multiple registered loaders or sub-loaders
> core: Merge nested options objects

- dev-docs/RFCs/README.md
- examples/deck.gl/3d-tiles/app.js
- modules/3d-tiles/src/tile-3d-loader.js
- modules/csv/src/csv-loader.js
- modules/csv/test/csv-loader-arrow.spec.js
- modules/csv/test/csv-loader.spec.js
- modules/draco/src/draco-loader.js
- modules/gltf/docs/api-reference/glb-loader.md
- modules/gltf/docs/api-reference/glb-writer.md
- modules/gltf/docs/api-reference/gltf-extensions.md
- modules/gltf/docs/api-reference/gltf-loader.md
- modules/gltf/docs/api-reference/gltf-scenegraph.md
- modules/gltf/docs/api-reference/gltf-writer.md
- modules/gltf/docs/api-reference/post-process-gltf.md
- modules/gltf/src/glb-loader.js
- modules/gltf/src/glb-writer.js
- modules/gltf/src/gltf-loader.js
- modules/gltf/src/index.js
- modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.js
- modules/gltf/src/lib/extensions/gltf-extensions.js
- modules/gltf/src/lib/parse-glb.js
- modules/gltf/src/lib/parse-gltf.js
- modules/gltf/test/gltf-loader.spec.js
- modules/gltf/test/gltf-writer.spec.js
- modules/gltf/test/lib/deprecated/gltf-parser.spec.js
- modules/kml/src/kml-as-geojson-loader.js
- modules/ply/src/ply-loader.js
- modules/ply/src/ply-stream-loader.js
- website/package.json
A big step towards getting the glTF loader into "reference quality" shape.
Trying hard to keep it backwards compatible when `options.gltf.parserVersion: 1` but it is getting harder...
> gltf: drop parseSync, options refactor and doc refresh

- .travis.yml
- docs/developer-guide/creating-loaders-and-writers.md
- docs/developer-guide/using-loaders.md
- docs/table-of-contents.json
- docs/whats-new.md
- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-gltf-view.js
- modules/3d-tiles/test/lib/parsers/batched-model-3d-tile.spec.js
- modules/3d-tiles/test/tile-3d-loader.spec.js
- modules/core/src/lib/loader-utils/get-loader-context.js
- modules/core/src/lib/parse-sync.js
- modules/core/src/lib/parse.js
- modules/csv/src/csv-loader.js
- modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.js
- modules/gltf/src/lib/extensions/KHR_lights_punctual.js
- modules/gltf/test/gltf-loader.spec.js
- modules/zip/src/zip-loader.js
When calling a loader from a loader, it is useful to be able to pass in and override loaders
```
parse(data, [Tile3DLoader, GLTFLoader, DracoLoader], 
```
And have the subloaders called by Tile3DLoader resolved against this list, overriding any locally specified or globally registered loaders.
```
Loader.parse(..., context) {
const {parse} = context;
parse(embeddedArrayBuffer);
}
```
This will significantly reduce the need for `registerLoaders` which should be a good thing.
> core: Use `context` to resolve loaders in sub-loaders

- dev-docs/RFCs/README.md
- dev-docs/RFCs/v2.0/fetch-option-rfc.md
- dev-docs/RFCs/v2.0/loader-auto-detection-rfc.md
- dev-docs/RFCs/v2.0/loader-auto-registration-rfc.md
- modules/3d-tiles/src/lib/tileset/tileset-3d-traverser.js
- yarn.lock
Uncomments some commented traversal code. This code was previously turned off to make hacked versions of traversal work when certain vis functionality was not yet working.
With this change, additive traversal works normally again (a parent no longer pulls all of its children, just the ones that it needs to). 
replacement refinement is still broken. When a tile is done processing off a worker, we should trigger a tileset update.
> Enable commented vis code

- modules/gltf/docs/api-reference/gltf-extensions.md
- modules/gltf/src/lib/extensions/KHR_materials_unlit.js
- modules/gltf/src/lib/extensions/gltf-extensions.js
- modules/gltf/test/index.js
- modules/gltf/test/lib/extensions/KHR_materials_unlit.spec.js
@tsherif @jianhuang01 FYI - photogrammetry tiles are already lit and lighting needs to be disable for these tiles.
materials can now have an `unlit: true` field
> gltf: support KHR_materials_unlit extension

- examples/deck.gl/3d-tiles/components/control-panel.js
- examples/deck.gl/3d-tiles/examples.js
All the chained loader plumbing is now in place, and the NY example now works perfectly, so temporarily adding it back while we are debugging.
However, none of the other b3dm tilesets work well, we'll need to understand what is different between these.
> 3d-tilles: Add back NY example

- examples/cesium/3d-tiles/app.js
- examples/cesium/3d-tiles/index.html
- examples/cesium/3d-tiles/package.json
- examples/cesium/3d-tiles/webpack.config.js
- examples/deck.gl/pointcloud/package.json
- examples/get-started-rollup/package.json
- examples/luma.gl/gltf/package.json
- examples/progress/package.json
This is a port of @xintongxia 's [Code Sandbox](https://codesandbox.io/embed/static-kmd50) to the loaders.gl example structure.
My hope is that we can collaborate here on a Cesium integration that uses loaders.gl to load 3d-tiles.
At a minimum this will allow us to pinpoint bugs in the deck.gl/THREE.js integrations more clearly.
And also, this integration would allow you to evaluate a possible deeper adoptions of loaders.gl
> 3d-tiles: Add Cesium sandbox example

- docs/upgrade-guide.md
- docs/whats-new.md
- lerna.json
- Lots of big and potentially breaking changes going in => major bump prudent
- Lots of deprecated code (we have 2 complete glTFLoaders) => major bump allows removal
> lerna: Start 2.0.0-alpha track

- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-gltf-view.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-point-cloud.js
- modules/core/src/lib/loader-utils/get-loader-context.js
- modules/core/src/lib/parse-sync.js
- modules/core/src/lib/parse.js
For some reason the bind version of the context code fails in transpiled tests and under Node 8.
> core: Avoid binding context due to transpilation issues

- babel.config.js
- examples/webpack.config.local.js
- modules/arrow/src/arrow-worker-loader.js
- modules/arrow/test/arrow-loader.spec.js
- modules/core/src/lib/loader-utils/parse-with-worker.js
- modules/core/test/worker-utils/worker-farm.spec.js
- modules/draco/src/draco-worker-loader.js
- modules/draco/test/draco-loader.spec.js
- modules/las/src/las-worker-loader.js
- modules/las/test/las-loader.spec.js
- modules/obj/src/obj-worker-loader.js
- modules/obj/test/obj-loader.spec.js
- modules/pcd/src/pcd-worker-loader.js
- modules/pcd/test/pcd-loader.spec.js
- modules/ply/src/ply-worker-loader.js
- modules/ply/test/ply-loader.spec.js
- package.json
- test/browser.js
- test/node.js
Currently the `*WorkerLoader`s embed worker source as strings. This approach introduced the following issues:
- Re-distributing external modules - some loaders contain large external components such as Draco and LAZ. These components do not change with each loaders.gl version but we need to re-bundle them as part of the worker.
- Bundle size - large workers inflate application bundles significantly. Users do not have the choice to split the worker from the app bundle.
- Duplication - When a loader module's standalone bundle is created, the large components are included twice, once in the main thread version, once in the worker as an inline string.
This PR is the first step towards addressing these issues:
- The worker source is separated from the `*WorkerLoader`s and by default loaded …
> Import workers from url

- examples/cesium/3d-tiles/app.js
This updates the CesiumJS example to read the `tileLoad` events from `loaders.gl` and create the point cloud tiles directly, bypassing all of the 3D Tiles machinery in CesiumJS. So this is effectively pretending CesiumJS doesn't directly support 3D Tiles. 
I was quite pleased with how easy it was to put together since `loaders.gl` gives you these convenient events to listen to, and all I needed to was fetch the content and create the primitive using the given model matrix & bounding sphere. The code is a little verbose because CesiumJS does not expose a public interface for `PointCloud.js`.
Although one thing I noticed was that the `tileUnload` event never seems to fire?
Adding B3dm loading should be pretty similar, and probably even easier since the model primitive is in the public API …
> Load point cloud in CesiumJS with loaders.gl

- examples/cesium/3d-tiles/app.js
- examples/cesium/3d-tiles/index.html
- examples/cesium/3d-tiles/tile-parsers.js
- examples/cesium/3d-tiles/tileset-loader.js
This PR extends the CesiumJS example to support loading of b3dm tiles. It also adds a "side by side" mode that makes it easier to compare what a tileset looks like loaded with CesiumJS's built-in loading & traversal vs Loaders.gl handling all the loading and traversal, and just passing the model (or point cloud) and its location for CesiumJS to render.
Some notes:
* I added in a `setTileVisible` in `tileset-loader.js` that can be the callback for when Loaders.gl emits an event when any given tile's visibility changes
* I noticed with B3dm tilesets, it seems as though 
* I also noticed the `onTileLoad`, fires both for the b3dm/pnts content, but also for the `json` in case of a tileset that links to another tileset. Is it on me as the user of loaders.gl to run `new Tileset3D()` on that tile …
> Add b3dm loading to CesiumJS example

- examples/deck.gl/pointcloud/app.js
- modules/ply/src/lib/normalize-ply.js
- modules/ply/src/lib/parse-ply.js
@zt123123 - Re #528 #533 The "right" fix should be to stop dividing with 255, and set the `normalized: true` flag on the generated attribute.
Converting to `Float32Array` will make the colors consume 4x as much memory.
> PLYLoader: Fix handling of color values

- modules/3d-tiles/src/lib/tileset/tile-3d-header.js
For #524 
The root tile covers the whole area in high zoom because of invalid space error.
> improve distanceToTile calculation

- modules/core/src/lib/parse.js
- modules/core/test/lib/load.spec.js
`parse` is confused about incoming arguments when `loaders` is `null` (happens when calling `load(url, options)`).
Add a unit test.
> Fix `load` when using auto loader detection

- examples/deck.gl/3d-tiles/3d-tile-layer/tile-3d-layer.js
- examples/deck.gl/3d-tiles/app.js
- modules/3d-tiles/src/lib/tileset/base-tileset-traverser.js
- modules/i3s/src/lib/tileset/i3s-tile-manager.js
- modules/i3s/src/lib/tileset/i3s-tileset-traverser.js
- modules/i3s/src/lib/tileset/i3s-tileset.js
Problem:
When the traversal is asynchronous, different update and traversal cycles will update the same traversal stack, and messed up with the traversal results.
Solution:
In this PR, change the asynchronous traversal back to synchronous.
For i3s tile traversal, it may need fetching tile metadata during traversal, so provide a callback to the fetch call which will resume the traversal from tile after fetched.
> Make traversal synchronous and fix the tile-3d-layer example flashing issue

- modules/core/docs/api-reference/set-path-prefix.md
- modules/core/src/index.js
- modules/core/src/lib/fetch/fetch-file.js
- modules/core/src/lib/fetch/read-file.js
- modules/core/src/lib/fetch/write-file.js
- modules/core/test/lib/fetch/fetch-error-message.spec.js
- modules/core/test/lib/fetch/index.js
- modules/images/test/lib/texture-loading-api/load-image.spec.js
- modules/loader-utils/src/index.js
- modules/loader-utils/src/lib/path-utils/file-aliases.js
- modules/loader-utils/test/index.js
- modules/loader-utils/test/lib/path-utils/file-aliases.spec.js
- modules/polyfills/test/fetch-node/fetch.node.spec.js
- test/modules.js
To support #541, non-core modules such as images may need to import `resolvePath`.
This PR moves `resolvePath` from core to loader-utils to minimize the size impact on the images module (which currently has no dependencies and could be used stand-alone).
An alternate mechanism would be to make resolvePath available through some global variable, so that it can be used dynamically if core has been imported..
> loader-utils: Move resolvePath from core to loader-utils

- modules/core/src/lib/encode.js
- modules/core/src/lib/loader-utils/get-data.js
- modules/core/src/lib/loader-utils/parse-with-worker.js
- modules/core/src/worker-utils/worker-pool.js
- modules/core/test/core.bench.js
- modules/csv/package.json
- modules/csv/test/csv.bench.js
- modules/draco/src/draco-writer.js
- modules/draco/test/draco-compression-ratio.spec.js
- modules/draco/test/draco-writer.spec.js
- modules/draco/test/draco.bench.js
- modules/gltf/src/lib/deprecated/gltf-builder.js
- modules/gltf/src/lib/extensions/UBER_draco_point_cloud_compression.js
- modules/json/test/bench.js
- modules/json/test/clarinet/clarinet.bench.js
- modules/json/test/json-loader.bench.js
- modules/json/test/json-loader.spec.js
- package.json
- test/bench/bench-modules.js
- test/bench/index.js
- test/bench/node.js
- test/render/test-cases/point-cloud.js
- yarn.lock
Adds benchmarks for JSON, comparing to `JSON.parse`. Also adds an (unfortunately unfavorable) comparison to d3-csv for the  `CSVLoader`
```
CSV Decode
├─ CSVLoader#parse: 279 iterations/s ±3.77%
├─ d3-dsv#parse: 2.13K iterations/s ±2.57%
Clarinet - JSON parsing from string
├─ JSON.parse (used by parseSync): 26.6K iterations/s ±3.55%
├─ ClarinetParser (used by parseInBatches): 7.15K iterations/s ±1.64%
JSONLoader - loading from file
├─ load(JSONLoader) - Uses JSON.parse: 717 iterations/s ±6.61%
├─ loadInBatches(JSONLoader) - Uses Clarinet: 204 iterations/s ±19.31%
```
> json: Add benchmark (+ fix existing benchmarks)

- modules/core/test/lib/loader-utils/normalize-loader.spec.js
- modules/images/src/image-loader.js
- modules/images/src/lib/parsed-image-api/image-type.js
- modules/images/src/lib/parsed-image-api/parsed-image-api.js
- modules/images/src/lib/parsers/parse-image.js
- modules/images/test/image-loader.spec.js
- modules/images/test/images.bench.js
- test/bench/bench-modules.js
Note: this PR does not change default image type, just fixes existing logic.
- Incorrect `options.images` references in code changed to `option.image` (correct per documentation).
- Fix to `getImageData`
- Fix `ImageBitmap` loading
- Add tests for loading different types
Adds `Benchmarks` comparing `imagebitmap` and `html`. Unsurprisingly the loading speed is quite similar, though once we have worker support in the `ImageLoader`, `ImageBitmap` could potentially have a significant advantage. They are also supposedly optimized for rendering...
> images: fix ImageBitmap loading, add benchmarks/tests

- package.json
@Pessimistress Right now I can't think of a reason that we need the offending `prepare` script but I assume there was a reason at some point...
I added a `build-workers` script as a convenience when I am iterating on the workers, it builds the scripts in 25s vs 75s for the full build.
> Fix double build

- docs/specifications/category-3d-tiles.md
- docs/specifications/category-gis.md
- docs/specifications/category-image.md
- docs/specifications/category-mesh.md
- docs/specifications/category-scenegraph.md
- docs/specifications/category-table.md
- docs/table-of-contents.json
- docs/upgrade-guide.md
- modules/arrow/docs/api-reference/arrow-loader.md
- modules/basis/docs/api-reference/basis-loader.md
- modules/basis/docs/api-reference/compressed-texture-loader.md
- modules/images/docs/README.md
- modules/images/docs/api-reference/image-loader.md
- website/src/components/animation-loop-runner.jsx
Improve category doc structure and text, link to "participating loaders", etc.
> Category docs

- modules/core/src/javascript-utils/is-type.js
- modules/core/src/lib/loader-utils/get-data.js
- modules/core/test/lib/loader-utils/get-data.spec.js
As discovered by @isaacbrodsky, there were still instances where loaders.gl failed on "embedded" `Buffer` and typed array arguments since it just extracted the embedded arraybuffer without regards for offsets.
This PR adds:
- initially failing tests for both embedded typed arrays and embedded `Buffer`s
- adds fixes for those tests.
> core: Fix parse of embedded typedArrays and Buffers

- modules/3d-tiles/src/lib/utils/doubly-linked-list.js
- modules/3d-tiles/test/index.js
- modules/3d-tiles/test/lib/utils/doubly-linked-list.spec.js
- port test file
- fix linked list counter
> @loaders.gl/3d-tiles: Port DoublyLinkedList test from Cesium

- website/package.json
- website/templates/index.jsx
> Fix website build

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-batched-model.js
For https://github.com/uber/deck.gl/issues/4222
> [3d-tiles] Handle GLTF w/ CESIUM_RTC extension

- docs/specifications/category-image.md
- docs/upgrade-guide.md
- docs/whats-new.md
- modules/images/docs/api-reference/image-loader.md
- modules/images/docs/api-reference/parsed-image-api.md
- modules/images/src/lib/parsed-image-api/image-type.js
- modules/images/src/lib/parsed-image-api/parsed-image-api.js
- modules/images/src/lib/parsers/parse-image.js
- modules/images/test/image-loader.spec.js
- modules/images/test/images.bench.js
- modules/images/test/lib/parsed-image-api.spec.js
- Replace `options.image.type: 'ndarray'` for Node.js with `options.image.type: 'data'`
- Support `options.image.type: 'data'` this on both Node.js and browser. 
- Continued cleanup and consolidation of the extensive image category docs
Apart from unifying the API and making it easy to load image data for image textures, also enables moving pixel extraction into the image worker (next PR), increasing parallel throughput of data texture loading.
> Image data

- examples/deck.gl/i3s/app.js
- examples/deck.gl/i3s/index.html
- modules/i3s/src/lib/parsers/parse-i3s-node-geometry.js
- modules/i3s/src/lib/tileset/i3s-tile-header.js
- modules/i3s/src/lib/tileset/i3s-tileset.js
Introduces a new traversal pattern for IntegratedMesh and 3D Object I3S layers that avoids using feature data document for traversal and loading of content. This should improve (cuts the request queue by 1/4th) performance by cutting down requests.
> I3s featureDataLess traversal pattern

- docs/whats-new.md
- modules/arrow/package.json
- Partly unrelated: some cleanup of what's new.
> arrow: Bump apache-arrow dependency to v0.16 (from v0.13)

- docs/upgrade-guide.md
- modules/arrow/test/arrow-loader.spec.js
- modules/core/src/index.js
- modules/core/src/iterator-utils/async-iteration.js
- modules/core/src/iterator-utils/chunk-iteration.js
- modules/core/src/iterator-utils/stream-iteration.js
- modules/core/src/lib/loader-utils/get-data.js
- modules/core/src/lib/parse-in-batches.js
- modules/core/test/index.js
- modules/core/test/iterator-utils/async-iteration.spec.js
- modules/core/test/iterator-utils/chunk-iteration.spec.js
- modules/core/test/iterator-utils/stream-iteration.spec.js
- modules/core/test/javascript-utils/index.js
- modules/json/test/lib/parser/streaming-json-parser.spec.js
- modules/ply/test/ply-loader.bench.js
- modules/ply/test/ply-loader.spec.js
- package.json
- yarn.lock
This function will be used to implement `parseInBatches` for `File` objects.
The goal here is to enable kepler.gl to use loaders.gl, and having streaming parsing support for `File` objects is a key goal.
> core: Add `makeChunkIterator`. Improve iterator generator function naming.

- modules/images/src/lib/binary-image-api/binary-image-parsers.js
- modules/images/test/lib/binary-image-api.spec.js
Add few additional bitmap file checks to prevent false positives:
- the header is at least 14 bytes long [wikipedia](https://en.wikipedia.org/wiki/BMP_file_format#File_structure)
- bytes 2-6 contain the size of the bitmap (incl header) [wikipedia](https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header)
> images: additional bitmap checks

- modules/images/src/lib/binary-image-api/binary-image-parsers.js
- modules/images/test/lib/binary-image-api.spec.js
As an additional safeguard for false positives, check the end of image marker [wikipedia](https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#File_format_structure).
> images: additional jpeg check

- modules/images/src/lib/image-parsers.js
- modules/images/test/lib/get-image-metadata.spec.js
_Backport of https://github.com/uber-web/loaders.gl/pull/673 to the `1.3-release` branch._
Add few additional bitmap file checks to prevent false positives:
- the header is at least 14 bytes long [wikipedia](https://en.wikipedia.org/wiki/BMP_file_format#File_structure)
- bytes 2-6 contain the size of the bitmap (incl header) [wikipedia](https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header)
> images: additional bitmap check

- modules/basis/src/basis-loader.js
- modules/basis/test/basis-loader.spec.js
Problem:
When running browser tests locally, [`basis`](https://github.com/uber-web/loaders.gl/blob/master/modules/basis/src/lib/basis-module-loader.js#L19) module will try to [load from CDN](https://github.com/uber-web/loaders.gl/blob/master/modules/loader-utils/src/lib/library-utils/library-utils.js#L48).
> basis: disable CDN when running local test

- modules/gis/docs/api-reference/geojson-to-binary.md
- modules/gis/src/index.js
- modules/gis/src/lib/geojson-to-binary.js
- modules/gis/test/data/mixed_features.json
- modules/gis/test/geojson-to-binary.spec.js
> GeoJSON to binary arrays improvements

- modules/images/docs/README.md
A couple of the image loader links are currently broken.
> Fix links in ImageLoader docs

- modules/polyfills/src/fetch-node/read-file.node.js
- modules/polyfills/src/fetch-node/utils/stream-utils.node.js
- modules/polyfills/test/fetch-node/fetch.node.spec.js
Node.js polyfill wrapper (modules/polyfills/src/fetch-node/read-file.node.js) wasn't closing request making it unable to complete for a non-local FS resources.
Fixed this as well as made test cases for node to pull resources from github directly instead of a local file system. (those 2 were failing before the change if pointed to http/https resources) and passing now.
> Fix for Node.js being unable to pull files from non local FS

- dev-docs/RFCs/README.md
- dev-docs/RFCs/vNext/category-improvements-rfc.md
- dev-docs/RFCs/vNext/images-category-rfc.md
- docs/contributing.md
- Proposes splitting the images module into a small loader-only module and a bigger utilities module - this RFC is ready for review
- Also contains a draft RFC on category modules - not ready for review but intended to indicate that we will likely have a category module for each category.
- Also salvages some unrelated text on how to add a new module from a github convo.
Background: We need to add more image utilities and this split should help us avoid concerns on e.g. bundle size growth.
> Images Category RFC 

- docs/table-of-contents.json
- modules/core/src/index.js
- modules/loader-utils/docs/api-reference/request-scheduler.md
- modules/loader-utils/src/lib/request-utils/request-scheduler.d.ts
- modules/loader-utils/src/lib/request-utils/request-scheduler.js
- modules/loader-utils/test/lib/request-utils/request-scheduler.spec.js
- modules/tiles/src/tileset/tile-3d.js
- `handle` is no longer required to have an `id`
- Dropped `trackRequestPromise` (not sure what this accomplishes - it does not trigger the promise)
- Dropped `startRequest` and `endRequest`:
Before
```js
const shouldRun = requestScheduler.scheduleRequest(this);
if (shouldRun) {
requestScheduler.startRequest(this);
await runTask();
requestScheduler.endRequest(this);  // `startRequest`/`endRequest` must be called in pairs for the next request in queue to resolve
}
```
After
```js
const requestToken = requestScheduler.scheduleRequest(this);
if (requestToken) {
await runTask();
requestToken.done();  // must be called for the next request in queue to resolve
}
```
This makes it possible to chain after `scheduleRequest` in another component without passing around the `requestScheduler` …
> [Discussion] Simplify RequestScheduler API

- modules/arrow/package.json
- yarn.lock
This is to set up for supporting Feather v2.
> Bump Arrow to 0.17.0

- modules/json/docs/api-reference/json-loader.md
The streaming examples in JSON docs had incorrect imports.
Additionally, should `loadInBatches` be listed as a Supported API? Right now only `load` is listed in the table, which might be confusing?
| Loader         | Characteristic                                       |
| -------------- | ---------------------------------------------------- |
| Supported APIs | `load`, `parse`, `parseSync`, `parseInBatches`       |
> Fix imports in JSONLoader docs

- docs/whats-new.md
- lerna.json
- Worker support for WKT, 
- Experimental GeoJSONLoader
- Bump arrow to 0.17.0
Update `lerna.json` version to `2.2.0-alpha.0`.
> Update What's New

- docs/README.md
- docs/whats-new.md
- modules/core/docs/api-reference/select-loader.md
- modules/loader-utils/docs/api-reference/request-scheduler.md
- modules/terrain/docs/api-reference/quantized-mesh-loader.md
- modules/video/docs/README.md
- modules/video/docs/api-reference/gif-builder.md
- modules/video/docs/api-reference/video-loader.md
- modules/wkt/docs/api-reference/wkt-loader.md
- website/package.json
Let users easily see what is available in each version.
@kylebarron
> docs: Add version numbers to doc pages for new exports

- website/gatsby-config.js
- Fixes the org of the top-right "Github" link to point to `https://github.com/visgl/loaders.gl` instead of `https://github.com/uber-web/loaders.gl`
- Fixes the link to `react-map-gl` which is currently broken
> Fix website links

- docs/whats-new.md
- examples/experimental/gltf-with-deck.gl/app.js
- examples/experimental/gltf-with-deck.gl/package.json
- examples/website/3d-tiles/app.js
- examples/website/pointcloud/app.js
- modules/3d-tiles/docs/api-reference/tiles-3d-loader.md
- modules/3d-tiles/package.json
- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-gltf-view.js
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-point-cloud.js
- modules/gltf/package.json
- modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.js
This removes the need for applications to keep track of the `DracoWorkerLoader` (which complicated the API and keeps causing some confusion.)
We should update examples in deck.gl once this lands, will add note to 2.2 checklist
> gltf/3d-tiles: DracoLoader now automatically imported and used

- docs/whats-new.md
- modules/json/src/lib/parse-json-in-batches.js
- modules/json/test/json-loader.spec.js
- modules/tables/src/lib/table/table-batch-builder.js
Unfortunately, this simple strategy doesn't work on CSVLoader since it doesn't use a clean AsyncIterator model.
Another reason to phase out papaparse (in addition to perf)...
> json: Add `batch.bytesRead` field (progress bar enabler)

- docs/whats-new.md
- modules/core/docs/api-reference/parse-in-batches.md
- modules/core/src/lib/api/parse-in-batches.js
- modules/core/src/lib/constants.js
- modules/core/test/index.js
- modules/core/test/lib/parse-in-batches.spec.js
- modules/draco/package.json
- yarn.lock
Provides the basic capability for kepler to get some information about which format was parsed.
The new metadata batch currently has two experimental fields `_loader` and `_context`, just to unblock.
> core: parseInBatches new metadata option returns additional metadata batch

- modules/core/src/lib/loader-utils/merge-options.js
- modules/csv/package.json
- modules/gltf/docs/api-reference/gltf-loader.md
- modules/gltf/src/gltf-loader.js
- modules/gltf/test/lib/gltf-scenegraph-accessors.spec.js
- modules/images/src/image-loader.js
- modules/json/src/json-loader.js
- modules/las/src/las-loader.js
- modules/las/src/lib/parse-las.js
- modules/loader-utils/src/index.d.ts
- modules/loader-utils/src/index.js
- modules/potree/src/potree-bin-loader.js
- modules/potree/src/potree-hierarchy-chunk-loader.js
This adds warnings for scoped loader options that do not match with the selected loader's default options.
Also added checking the top level options, we may need to add a longer white list but this seems to cover the test suite.
> core: Add loader option warnings

- modules/json/src/lib/parse-json-in-batches.js
- modules/json/src/lib/parser/streaming-json-parser.js
- modules/json/test/json-loader.spec.js
Ensures that `jsonpath` is exposed as a `JSONPath` object for all batch types (used to be a string for some, and an object for others). This will also allow clients to use the JSONPath object for setting/getting fields without an additional import.
> Fix: expose the jsonpath property in a consistent shape

- modules/terrain/src/terrain-loader.js
In 2.2, `validateLoaderOptions` throws a warning because `bounds` isn't defined on the default options object.
By default, `bounds` is `[0, 0, tileSize, tileSize]`, which is used when bounds is falsy.
It might be ideal to add a test for `validateLoaderOptions` to the `validateLoader` test?
> TerrainLoader Add bounds: null default to prevent warnings

- modules/core/src/lib/utils/mime-type-utils.js
- modules/core/test/lib/utils/mime-type-utils.spec.js
Improve regex for detecting MIME type. While not implementing the [full spec](https://mimesniff.spec.whatwg.org/#parsing-a-mime-type) for parsing an arbitrary MIME type, this should be improved over the existing `.+`.
Derived from [this regex](https://www.regextester.com/110183), tested against many common mime type strings.
Should it still return the input if no match found?
> Improve MIME type regex

- modules/json/test/json-loader.spec.js
Not cherry picked from the `2.2-release` branch, because it's in the `2.2.3` release commit.
> Skip sometimes-failing JSON loader test

- modules/shapefile/package.json
- modules/shapefile/src/shp-loader.js
- modules/shapefile/test/index.js
- modules/shapefile/test/shp-loader.spec.js
- yarn.lock
This adds a `parseInBatches` method to the `SHPLoader`. For now, this is still non-streaming, but should be streaming in the future.
The output of each batch is:
```
{
header: {
length: 676,
type: 5,
bbox: {
minX: 0,
minY: 0,
minZ: 0,
minM: 0,
maxX: 5,
maxY: 5,
maxZ: 0,
maxM: 0
}
},
features: [
{ positions: [Object], indices: [Object] },
{ positions: [Object], indices: [Object] },
{ positions: [Object], indices: [Object] }
]
}
```
Relies on #820.
> Add parseInBatches Shapefile method

- modules/3d-tiles/docs/api-reference/tiles-3d-loader.md
- modules/core/src/lib/api/register-loaders.js
- modules/core/src/lib/loader-utils/merge-options.d.ts
- modules/core/src/lib/loader-utils/merge-options.js
Stores global registered loaders and options on the global object to increase chances of cross loaders-version interoperability
NOTE: This use case is not reliable but can help when testing new versions of loaders.gl with existing frameworks
This is in response to the suggestion that we make loader-utils a peerDependency of core, which after consideration seemed too problematic given how closely dependent core is on loader-utils.
> core: truly global loaders and options

- docs/whats-new.md
- modules/polyfills/src/fetch-node/fetch.node.js
- modules/polyfills/src/fetch-node/response.node.js
- modules/polyfills/src/fetch-node/utils/stream-utils.node.js
- modules/polyfills/test/fetch-node/fetch.node.spec.js
Streams no longer crash under Node when opened on invalid files, and now propagate platform error messages to `Response.statusText`.
This turned out to be a big blocker for getting the Node tests working in upcoming multi-file loading PRs, and also generally improves the Node.js support.
> polyfills: Improved stream error handling

- arrowjs/docs/get-started/installing.md
- docs/developer-guide/get-started.md
- examples/website/pointcloud/app.js
- modules/core/src/lib/api/parse.js
- modules/core/src/lib/loader-utils/normalize-loader.js
- website/gatsby-config.js
- website/package.json
- website/src/components/animation-loop-runner.jsx
- website/templates/index.jsx
Switching main example from glTF to pointcloud until glTF example is fixed in luma.gl.
Remaining.
- Still the images (example thumbnails and images in the module api reference) are not working.
- Setup looks similar to deck.gl, not yet sure where things go wrong.
> website: Fix new ocular website

- modules/loader-utils/src/index.d.ts
- modules/loader-utils/src/types.d.ts
- modules/shapefile/package.json
- modules/shapefile/src/dbf-loader.js
- modules/shapefile/src/index.js
- modules/shapefile/src/lib/api/parse-files.js
- modules/shapefile/src/lib/filesystems/browser-filesystem.d.ts
- modules/shapefile/src/lib/filesystems/browser-filesystem.js
- modules/shapefile/src/lib/filesystems/node-filesystem.d.ts
- modules/shapefile/src/lib/filesystems/node-filesystem.js
- modules/shapefile/src/shapefile-loader.js
- modules/shapefile/src/shp-loader.js
- modules/shapefile/src/workers/dbf-loader.worker.js
- modules/shapefile/src/workers/shp-loader.worker.js
- modules/shapefile/test/dbf/parse-dbf.spec.js
- modules/shapefile/test/index.js
- modules/shapefile/test/shapefile-loader.spec.js
This provides filesystems that can hold a group of related files, letting the ShapefileLoader `fetch` sidecar files without caring about whether they were other files in the same drag-and-drop operation or if they are fetched from URLs.
Keeping the new filesystem classes in shapefile for now, to avoid adding too much unproven code to core.
> Shapefile multi-file loading, initial file system support.

- modules/images/docs/api-reference/image-loader.md
- modules/images/docs/api-reference/image-writer.md
- modules/images/src/image-loader.js
- modules/images/src/image-writer.js
- modules/images/src/lib/encoders/encode-image.d.ts
- modules/images/src/lib/encoders/encode-image.js
- modules/images/test/image-writer.spec.js
- modules/loader-utils/src/types.d.ts
- ImageWriter now works correctly (inverse of ImageLoader, as one would expect) and passes proper tests.
- Image module script size: +387 bytes (11735 -> 12122 bytes).
- In bundlers, writer will be tree shaken if not used.
Note: there are a couple PRs in the works will significantly reduce the image module script size
> images: improved ImageWriter

- modules/gis/src/index.js
- modules/gis/src/lib/binary-to-geojson.d.ts
- modules/gis/src/lib/binary-to-geojson.js
- modules/gis/src/lib/geojson-to-binary.d.ts
- modules/gis/test/binary-to-geojson.spec.js
- modules/gis/test/data/featurecollection.json
- modules/gis/test/index.js
Right now this only parses single geometries.
Todo: 
For now I use the WKB test cases, which contains a mapping between GeoJSON and binary representations, but there are some edge cases that can be described in GeoJSON but not in our binary format. I.e. a geometry of type `MultiPoint` that only has one point. Those cases are assumed to be non-Multi. I'll need to copy some custom test cases for this into the `loaders.gl/gis` module.
> WIP Binary to geojson converter

- modules/shapefile/src/lib/parse-shp.js
- modules/shapefile/src/shapefile-loader.js
- modules/shapefile/test/data/shapefile-js/singleton.json
- modules/shapefile/test/shapefile-loader.spec.js
- modules/shapefile/test/shp-loader.spec.js
- modules/shapefile/test/shp/parse-shp.spec.js
The output of the `SHPLoader` is an _array of binary objects_, each of which corresponds to a single geometry. This modifies the `ShapefileLoader` to first convert each of these geometries to GeoJSON, then combine with the properties output of the `DBFLoader` into an array of GeoJSON `Feature`s.
> Shapefile fixes

- modules/csv/src/csv-loader.js
- v2.2 introduced a helpful warnings system to draw the user's attention to unsupported options.
- the system depends on loaders listing out all supported options, otherwise false warnings may be flagged.
- this adds all the papaparse options to CSVLoader, expect the auto-detect/function valued ones that require more investigation as it is not clear if the presence of a default value here affects the auto detection.
> csv: List out supported options to avoid incorrect warnings

- modules/core/src/lib/api/parse-in-batches.js
- modules/core/src/lib/utils/resource-utils.js
- modules/core/test/lib/utils/resource-utils.spec.js
For some reason, `null` was passed instead of the resource to `selectLoaders` which skipped much of the logic to get the resource type and url based on it's class type.
> [Bug/Enhancement] Pass actual resource so inference can be done via getResouceUrlAndType

- modules/loader-utils/src/lib/worker-utils/get-transfer-list.js
A [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) is very useful when splitting a single job among multiple workers. `TypedArray.buffer: <SharedArrayBuffer>` is not transferrable, and in the current implementation `getTransferList` recursively looks into the typed array's content which kills the perf.
This PR is intended to be a quick patch. In my mind we need better rules in determining what objects need to be traversed, e.g. we could skip an array if the first element is a number/string.
> Perf: prevent iterating through typed array if using SharedArrayBuffer

- docs/upgrade-guide.md
- docs/whats-new.md
- modules/core/docs/api-reference/select-loader.md
- modules/core/src/index.d.ts
- modules/core/src/index.js
- modules/core/src/iterator-utils/make-iterator/blob-iterator.d.ts
- modules/core/src/iterator-utils/make-iterator/blob-iterator.js
- modules/core/src/lib/api/load-in-batches.js
- modules/core/src/lib/api/load.js
- modules/core/src/lib/api/parse-in-batches.js
- modules/core/src/lib/api/parse-sync.js
- modules/core/src/lib/api/parse.js
- modules/core/src/lib/api/select-loader.d.ts
- modules/core/src/lib/api/select-loader.js
- modules/core/src/lib/filesystems/browser-filesystem.js
- modules/core/src/lib/loader-utils/get-data.d.ts
- modules/core/src/lib/loader-utils/get-data.js
- modules/core/test/lib/api/select-loader.spec.js
- modules/images/test/image-loader.spec.js
- modules/polyfills/src/fetch-node/fetch.node.js
- modules/tiles/test/tileset/tileset-3d.spec.js
- tsconfig.json
This is a breaking change in that `selectLoader` is now async. But I don't think it is used directly by many applications.
The PR also removes the option to pass a final url parameter to `parse` etc, favoring passing url through (synthetic) response. This simplifies the logic in those functions which was making them quite intimidating to new (and old) maintainers, and also made them very hard to update correctly.
There is some small risk for impact but overall I felt this was the right change.
> core: selectLoader/selectLoaderSync split

- modules/mvt/package.json
- modules/mvt/src/lib/mapbox-vector-tile/LICENSE.txt
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile-feature.d.ts
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile-feature.js
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile-layer.d.ts
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile-layer.js
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile.d.ts
- modules/mvt/src/lib/mapbox-vector-tile/vector-tile.js
- modules/mvt/src/lib/parse-mvt.js
- yarn.lock
The current `@mapbox/vector-tile` code parses into binary by first parsing to geojson, creating large amounts of small objects that are immediately thrown away, causing unnecessary memory / garbage collection pressure. 
It seems straightforward to write a binary parsing pass to avoid this step and parse directly to binary buffers. However, this requires modifying the mapbox code.
- Forks `@mapbox/vector-tile` source code
- Lightly modernizes to ES6 style
- Adds minimal typescript typings
> mvt: Fork @mapbox/vector-tile (prep for optimized binary loading)

- modules/shapefile/src/lib/parse-geometry.js
LineString and Polygon geometries are stored identically in Shapefiles. This PR returns explicit type information for these geometries so that the binary-to-geojson conversion process can coerce to the right geometry type.
> Shapefile: Make polyline data type explicit

- modules/shapefile/src/lib/parse-geometry.js
- modules/shapefile/src/shapefile-loader.js
- modules/shapefile/test/shp/parse-shp.spec.js
The SHP polyline parsing previously returned an `indices` key. According to the [binary format "spec"](https://github.com/visgl/loaders.gl/blob/master/modules/gis/docs/api-reference/geojson-to-binary.md#outputs) only `Point` output should have an `indices` key. `LineString` output should instead have a `pathIndices` key, and `Polygon` output should have both `polygonIndices` and `primitivePolygonIndices` keys.
The above alone fixes the binary-to-geojson's auto-deduction, since it sniffs for that index:
https://github.com/visgl/loaders.gl/blob/782ee05169c1c329b9a9a564e9a38c5e3113e938/modules/gis/src/lib/binary-to-geojson.js#L201-L211
But this PR also updates to pass the geometry type to `binaryToGeoJson` explicitly, so that no sniffing is needed.
> Fix name of indices returned from SHPLoader

- modules/shapefile/src/dbf-loader.worker.js
- modules/shapefile/src/shp-loader.worker.js
It looks like in `modules/shapefile`, there are duplicate `dbf-loader.worker.js` and `shp-loader.worker.js` files. This PR keeps the files in `src/workers` and removes the files in `src/`.
> Remove duplicate shapefile worker loader files

- modules/crypto/src/lib/crc32/crc32-hash-transform.js
- modules/crypto/src/lib/crc32c/crc32c-hash-transform.js
- modules/loader-utils/test/lib/iterator-utils/make-transform-iterator.spec.js
- modules/shapefile/test/shapefile-loader.spec.js
- Fix a bug leading to hash occasionally being emitted as part of the parsed data.
- Add additional test case for non-streaming (Shapefile) loader parsed with `parseInBatches` and a crypto transform.
> crypto: fix transform iterators

- .travis.yml
> CI: add cache to .travis.yml

- modules/gltf/docs/api-reference/gltf-loader.md
- modules/json/src/json-loader.js
`text/json` isn't really a valid mime-type, and `application/json` is the more standard type usually used. This will also make loaders consistent with heavily used mime type databases and packages such as [`mime-db`](https://github.com/jshttp/mime-db/blob/master/db.json#L519) and [`mime-types`](https://www.npmjs.com/package/mime-types)
> [Bug] Fix incorrect text/json mimeType for JSON Loader

- modules/loader-utils/src/lib/binary-utils/array-buffer-utils.js
- modules/loader-utils/src/lib/iterator-utils/async-iteration.js
- modules/loader-utils/test/loader-utils.bench.js
- test/bench/modules.js
Repeated concatenation of big chunks is very slow. Replace with a single concatenation at the end.
> loader-utils: concatenateChunksAsync perf increase

- docs/whats-new.md
- modules/gltf/docs/api-reference/glb-loader.md
- modules/gltf/docs/api-reference/glb-writer.md
- modules/gltf/docs/api-reference/gltf-loader.md
- modules/gltf/src/gltf-loader.js
- modules/gltf/src/lib/extensions/KHR_binary_gltf.js
- modules/gltf/src/lib/extensions/gltf-extensions.js
- modules/gltf/src/lib/gltf-constants.js
- modules/gltf/src/lib/gltf-scenegraph.d.ts
- modules/gltf/src/lib/gltf-scenegraph.js
- modules/gltf/src/lib/normalize-gltf-v1.js
- modules/gltf/src/lib/parse-glb.js
- modules/gltf/src/lib/parse-gltf.js
- modules/gltf/test/glb-loader.spec.js
- modules/gltf/test/gltf-loader.spec.js
- yarn.lock
Optional support for automatically converting glTF v1 to glTF v2 on load. 
The logic is in a new file `normalize-gltf-v1.js` which is only invoked when the new option `options.gltf.normalize` is set to true.
This should not affect existing apps.
The main use case for adding support for the older glTF format is currently to support older 3D tiles tilesets that were tiled before glTF v2 was available.
> gltf: partial support for GLBv1 and glTFv1

- modules/core/src/iterator-utils/make-iterator/stream-iterator.js
Ref #925, where I discovered that loading files as streams in Node produced Node Buffers instead of ArrayBuffers.
I couldn't find where the relevant tests are for this code. Does this change need a new test?
> Coerce each chunk of a Node stream to an ArrayBuffer

- modules/las/docs/api-reference/las-loader.md
- modules/las/src/las-loader.js
- modules/las/src/lib/parse-las.js
Before this commit, colors were assumed to be encoded on one byte.
However, the [LAS specification says otherwise, at least since 1.3][0]
(description of Point Data Record Format 2):
>  Red, Green, Blue values should always be normalized to 16 bit values.
As final colors are stored in a Uint8Array, a division by 256 has been
added. However, to ensure retrocompability, this division is done only
if a value of R, G or B is greater than 255. It is assumed that their
won't be a case of colors being scaled in the 0-255 range, even for
10 bits or greater range of camera color.
This assumption is subject to a debate, I just copy the way [it is done
in Potree.](https://github.com/potree/potree/blob/develop/src/workers/EptLaszipDecoderWorker.js#L68)
[0]: …
> las: parse two-bytes colors

- modules/las/src/lib/parse-las.js
I forgot to add this in #927, sorry about that !
> las: add a safeguard for two bytes color detection

- modules/core/src/lib/api/load.d.ts
- modules/draco/package.json
- modules/draco/src/index.d.ts
- modules/draco/src/lib/draco-builder.d.ts
- modules/draco/src/lib/draco-builder.js
- modules/draco/src/lib/draco-parser.d.ts
- modules/draco/src/lib/draco-parser.js
- modules/draco/src/types/draco-types.d.ts
- modules/draco/src/types/draco-web-decoder.d.ts
- modules/draco/src/types/draco-web-encoder.d.ts
- Introduce typescript types for the underlying draco3d library, semi-manually extracted from Web IDL.
- No functional changes
> draco: Add draco3d types

- modules/draco/src/draco-loader.js
- modules/draco/src/lib/draco-builder.js
- modules/draco/src/lib/draco-parser.js
- modules/draco/test/draco-loader.spec.js
An improvement from @Avnerus PR #940:
- the DracoLoader now automatically detects custom attributes (giving them default names unless provided in `options.draco.extraAttributes`).
> draco: Custom attributes

- modules/mvt/src/lib/parse-mvt.js
Fix issue where parsing MVT to wgs84 throws if `tileIndex` contains `0`
@jesusbotella
> [MVT] Fix tile index check

- modules/shapefile/test/dbf-loader.spec.js
- modules/shapefile/test/shapefile-loader.spec.js
- modules/shapefile/test/shp-loader.spec.js
Tests were unreliable/failing because shapefile tests were trying to use remote worker bundles.
> Set worker url to local file for shapefile tests

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-point-cloud.js
- modules/draco/src/lib/draco-parser.js
Hi,
It looks like the recent fixes broke the cases in which there is no batch table json, such as in the Melbourne example on the loaders.gl website. The `extraAttirbutes` key was present in `options`, but was `null` which caused the loader to crash. 
I added a check both in `DracoLoader`,  and in the point cloud parser.
/Avner
> Draco: Fix for the case that extraAttriutes are provided in options but are null.

- modules/tiles/src/tileset/tile-3d.js
Hi!
As I mentioned earlier, external tileset JSONs within tiles were not loading from my Cesium ION data.  
It seems like all I had to do was change the `isTileset` to `auto`.
Unfortunately, I don't have a public test case available with external tilesets, because they are only used by Cesium in larger datasets (~5Gb or more), but perhaps you have one available that you can test this on?
I have confirmed on my ION account that before the enclosed fix I get the following error:
`A 3D tile failed to load: undefined 3DTileLoader: unknown type {"as` because the JSON is attempting to load as a binary tile.
After the fix it seems to work! Looks like that `false` was set in [this PR](https://github.com/visgl/loaders.gl/pull/827/commits).
Let me know if this is OK, or if you need alarge data to …
> Set isTileset to 'auto' in tile-3d to enable loading an external tileset json within a tile

- modules/3d-tiles/src/lib/encoders/encode-3d-tile-instanced-model.js
- modules/3d-tiles/test/lib/parsers/instanced-model-3d-tile.spec.js
The encode/parse based tests were passing, but for the wrong reason - false positives.
> 3d-tiles: Fix encodeSync based tests

- modules/shapefile/package.json
Closes #988 
Does the file itself need an exclude, or just `fs`? If so does it need paths in `dist/` as well like 
https://github.com/visgl/loaders.gl/blob/3e7a4f8b8bb1ddcef7c2e26c7cc8e07d3b0cf546/modules/core/package.json#L25-L35
> Add browser excludes for shapefile

- modules/las/docs/api-reference/las-loader.md
- modules/las/src/las-loader.js
- modules/las/src/lib/parse-las.js
- modules/las/test/las-loader.spec.js
- modules/pcd/src/lib/parse-pcd.js
https://github.com/visgl/deck.gl/issues/3914
Open for discussion: should we provide options for 64-bit positions in all modules?
- Point clouds (this PR): I think 64-bit should be the default, so that users do not have to worry about the precision.
- More advanced formats like glTF and Draco have built-in data types.
- Simple meshes (OBJ, PLY etc.): it has not come up as an issue, since deck's SimpleMeshLayer only supports 32-bit mesh positions. However the users may want to do custom rendering.
> Option to use float64 for LAS positions

- modules/tables/src/lib/table/row-table-batch.js
An optional fix to decrease memory usage during and after parsing of row based datasets.
The issue was caused by following "feature" of JS implementation: https://bugs.chromium.org/p/v8/issues/detail?id=2869
Example of string views in Chrome's memory profiler. For some of our datasets the profiler found 1000+ levels of views which caused memory explosions.
Summary from testings:
- 480 Mb dataset, with long rows. The dataset was crashing during parsing (used around 4+Gb). With the fix the dataset is parsed without issues and fits in 600Mb memory.
- 636 Mb dataset (timestamp and h3 index per row). 58% longer parsing time, 338 Mb less memory used (12-17% less)
- 280 Mb dataset (timestamp and h3 index per row). 58% longer parsing	time, 100 Mb less memory used (15-20% less)
- 25 Mb dataset (10 …
> Row based parsing: Option to enable memory usage optimizations.

- modules/csv/src/csv-loader.js
optimizeMemoryUsage isn't passed from outside to the place where it is used.
> Fix - properly pass optimizeMemoryUsage param during CSV parsing

- modules/shapefile/src/lib/parsers/parse-shp-geometry.js
When a Shapefile has a Polygon geometry with a very large number of positions, indices for polygon rings can be greater than 65535.
> Fix polygonIndices uint16 overflow with large rings

- modules/shapefile/src/lib/parsers/parse-dbf.js
- modules/shapefile/src/lib/parsers/parse-shapefile.js
- modules/shapefile/test/shapefile-loader.spec.js
When `options.metadata` is `true`, an extra initial batch of metadata is returned when using `loadInBatches`. Since the `ShapefileLoader` creates the `SHPLoader` and `DBFLoader` under the hood and then iterates over them together using `zipBatchIterator`, it needs to understand the format of batches returned by each of them. `zipBatchIterator` currently expects batches to be an `Array` and will fail when either is not an array.
> Fix shapefile batch parsing when options.metadata: true

- .github/workflows/test.yml
As noted in #1015, Github Actions currently doesn't run for a pull request from a fork. I believe `pull_request_target` needs to be added for this to happen.
Note that `pull_request_target` [is safer than](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) `pull_request` because:
> instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request
Full `pull_request_target` docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pul …
> Add pull_request_target event to github actions template

- .github/workflows/test.yml
The PR #1016 was necessary to allow CI to run on PRs from forks. However this now duplicates tests on pull requests made from a branch of the `visgl/loaders.gl` repository, since it counts as a `push` and a `pull_request_target`. Apparently [the standard way to prevent both from happening](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662) this should be something like:
```yaml
on:
push:
branches:
- master
pull_request_target:
```
So that every pull request runs CI but `push` only runs separately for new commits to master
> Deduplicate gh actions on pull request

- modules/core/docs/api-reference/parse.md
https://loaders.gl/modules/core/docs/api-reference/parse#options
> Fix options table rendering in parse.md

- .github/workflows/test.yml
See the PR in `react-map-gl` for a description of why we should be using `pull_request` instead of `pull_request_target`: https://github.com/visgl/react-map-gl/pull/1251
> Use pull_request instead of pull_request_target for Github Actions

- docs/table-of-contents.json
- examples/webpack.config.local.js
- examples/website/3d-tiles/app.js
- examples/website/3d-tiles/constants.js
- examples/website/i3s/app.js
- modules/tile-converter/docs/README.md
- modules/tile-converter/docs/api-reference/3d-tiles-converter.md
- modules/tile-converter/docs/api-reference/i3s-converter.md
- modules/tile-converter/docs/cli-reference/tile-converter.md
- website/gatsby-config.js
The basemaps for the examples were broken in the published documentation since the mapbox token was not set. 
Updated the examples to use different map styles.
A few fixes to the docs.
> Fix basemaps

- modules/core/src/lib/loader-utils/option-utils.js
- modules/polyfills/docs/api-reference/README.md
- modules/polyfills/src/fetch-node/fetch.node.js
- modules/polyfills/test/fetch-node/fetch.node.spec.js
+ test case for redirect;
+ documentation;
- followRedirect option. I found comment that passing options into `fetch` function is deprecated https://github.com/visgl/loaders.gl/blob/e54cff4b680024b66b23684ab1b411337b4afc57/modules/core/src/lib/loader-utils/option-utils.js#L99.
> polyfills: test 302 redirect

- modules/mvt/src/mvt-loader.js
Add standard [MIME Type](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#22-multipurpose-internet-mail-extensions-mime) to MVTLoader
> Add MVT MIME type

- modules/textures/src/index.d.ts
- modules/textures/src/index.js
- modules/textures/src/lib/utils/texture-formats.d.ts
- modules/textures/src/lib/utils/texture-formats.js
- modules/textures/test/index.js
- modules/textures/test/utils/format-utils.spec.js
@dryabinin-actionengine Please take over and land
> feat(textures): Add texture format utils

- modules/textures/package.json
- modules/textures/src/compressed-texture-loader.js
- modules/textures/src/crunch-loader.js
- modules/textures/src/workers/compressed-texture-loader.worker.js
- modules/textures/src/workers/crunch-loader.worker.js
- modules/textures/src/workers/npy-loader.worker.js
- Created workers for `crunch` and `compressed-textures`;
- Moved `npy` worker into `workers` path.
> textures: loader workers

- modules/gis/src/lib/binary-to-geojson.js
- modules/gis/src/lib/geojson-to-binary.js
- modules/gis/test/binary-to-geojson.spec.js
- modules/gis/test/data/empty_binary.js
- modules/gis/test/data/geojson_no_properties.json
- modules/gis/test/geojson-to-binary.spec.js
- modules/mvt/src/lib/parse-mvt.js
- modules/mvt/test/mvt-loader.spec.js
Fixes some issues related to transformation for empty objects (eg. when a tile has no data) or geojson data without properties.
> Fix binary-geojson transformations for empty objects

- modules/csv/src/libs/papaparse.js
- modules/las/src/libs/laz-perf.js
- modules/polyfills/src/libs/encoding.js
- scripts/bundle.config.js
Previous [fix](https://github.com/visgl/loaders.gl/pull/1134) was bad. It breaks `dist/es5 `files. Just because we should not transpile` /libs/` folder using babel because it stores external already transpiled and minified libraries and scripts. So all files in `/libs` folder have `ES5` syntax and we can't add `ES6` syntax there.
To avoid error in `dist.min.js` file I also tried to replace `import` with `require` syntax for modules which we get from `/libs` folder, but it doesn't help because somehow webpack logic change `module` object to another `module` object with `read-only ` exports filed.
So the easiest way to fix that is to use `commonJs` plugin to align all the code using only one standard.
> Change babel config to fix es5 modules transpilation

- modules/gis/docs/api-reference/geojson-to-binary.md
- modules/gis/src/lib/geojson-to-binary.js
- modules/gis/test/geojson-to-binary.spec.js
This fix is intended to avoid mutating the properties of the geoJSON object used as input for `geojsonToBinary` function as it currently removes all the numeric properties from the original geoJSON features.
> Avoid mutating input object in geojsonToBinary function

- docs/whats-new.md
- modules/compression/package.json
- modules/compression/src/index.d.ts
- modules/compression/src/index.js
- modules/compression/src/lib/lz4/lz4-inflate-transform.d.ts
- modules/compression/src/workers/lz4-worker.js
- modules/compression/src/workers/lz4.worker.js
- modules/compression/src/workers/zlib-worker.js
- modules/compression/src/workers/zlib.worker.js
- modules/compression/test/zlib/zlib.spec.js
- modules/compression/wip/zstd/zstd-deflate-transform.md
- modules/core/src/index.d.ts
- modules/core/src/index.js
- modules/loader-utils/README.md
- modules/loader-utils/package.json
- modules/loader-utils/src/index.d.ts
- modules/loader-utils/src/index.js
- modules/loader-utils/src/lib/path-utils/path.d.ts
- modules/loader-utils/src/lib/worker-utils/create-worker.d.ts
- modules/loader-utils/src/lib/worker-utils/create-worker.js
- modules/loader-utils/src/lib/worker-utils/get-worker-url.js
- modules/loader-utils/src/lib/worker-utils/process-on-worker.d.ts
- modules/loader-utils/src/lib/worker-utils/process-on-worker.js
- modules/loader-utils/src/lib/worker-utils/worker-thread.js
- modules/loader-utils/src/types.d.ts
- modules/loader-utils/src/workers/null-worker.js
- modules/loader-utils/test/index.js
- modules/loader-utils/test/lib/worker-utils/process-on-worker.spec.js
- scripts/webpack/worker.js
Compression should be done on workers but our existing worker support was specific to loaders. This generalizes things so that arbitrary tasks can be bundled up and packaged as loadable workers.
- Adds `createWorker()` and `processOnWorker()` APIs for running non-loader pre-bundled worker tasks
- Adds `WorkerObject` type
- Adds `ZlibWorker` and `LZ4Worker` worker objects that support compression and decompression on worker threads. 
- Importing these objects does not add compression library dependencies to main bundle size.
> feat(compression): worker compression

- modules/tile-converter/src/i3s-converter/i3s-converter.js
`sharedResouce` should be an `object`
https://github.com/Esri/i3s-spec/blob/master/docs/1.7/3DNodeIndexDocument.cmn.md
> Change sharedResource href structure as per spec

- modules/gltf/src/lib/post-process-gltf.js
Hi!
When testing out some Cesium 3d-tiles, one model loaded seemingly fine, but the normals were off and the geometry had some holes in it.
After doing some digging, I found that some accessor buffers were not loaded correctly because of this line:
```
const byteOffset = (accessor.bufferView.byteOffset || 0) + buffer.byteOffset;
```
where it was not taking into account `accessor.byteOffset`, which looks to be part of the [gLTF standard](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/accessor.schema.json#L13-L19).
Once I added `+ (accessor.byteOffset || 0)` to the sum, it fixed my model.
/Avner
> gltf: when resolving accessors in post-processing, take into account accessor.byteOffset

- scripts/webpack/bundle.js
- scripts/webpack/worker.js
Build `.map` source map files in dist folder for script and worker bundles. 
The hope is that the browser debugger will be able to load these from CDN after we publish.
> feat: Build source maps on CDN to enable script and worker debugging.

- modules/mvt/src/mvt-loader.js
Enable vector tiles to be loaded from ArcGIS server.
Per https://github.com/visgl/deck.gl/discussions/5482
> fix(mvt): Add extensions/mime types to support ArcGIS server

- examples/experimental/i3s-picking/app.js
- examples/website/textures/components/compressed-texture.js
- modules/textures/src/compressed-texture-loader.js
- modules/textures/src/crunch-loader.js
- modules/textures/src/lib/utils/version.js
- modules/worker-utils/src/lib/worker-api/worker-object-utils.js
- website/gatsby-config.js
I run it locally. On San Francisco 1.6 works good. On 1.7 SF and NY we have a draco lib error. Looks like something related to npm versions.
`7398244c-4112-4da5-bff8-dcc5b9c58f54:4 DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://unpkg.com/@loaders.gl/draco@latest/dist/draco-worker.js' failed to load`
> Change I3S example to I3S with picking feature

- examples/experimental/i3s-picking/app.js
- examples/experimental/i3s-picking/components/attributes-panel.js
- Added close button at the top of the attributes panel
- Replace Control panel with attributes panel if any building is selected
- Replace empty value with 'No Data' string.
- Close attributes panel if user clicked outside of buildings
> I3s Picking improve attributes panel

- examples/experimental/i3s-picking/app.js
- Enabled picking color only when user click on object (building).
- After this changes we get an issue in `I3S v1.7` picking functionality:
In` I3s v1.6 `vesrion we are using `featureIds` which were created by using `id` and `faceRange` data of particular tile.
This `featureIds` represents `OBJECTID` values from `attributeStorageInfo` and they are all unique across all tiles.
So when we encode such `featureIds` to `pickingColors` we have unique color for each building across all tiles on the map.
In `I3S v1.7` version `featureIds` from compressed geometry are like feature indices for every attribute in `attributeStorageInfo`. We can find particular building attributes using `featureId` as index in `attributeStorageInfo` object. So such `featureIds` are not unique across all tiles in …
> I3S picking - Select building using only onclick event

- .eslintignore
- .prettierignore
As noted [here](https://github.com/visgl/loaders.gl/pull/1235#issuecomment-789600863), merging https://github.com/visgl/loaders.gl/pull/1225 caused CI on master to fail. This PR adds that example directory to `.eslintignore` and `.prettierignore`.
> Fix lint causing CI to fail

- modules/i3s/src/lib/parsers/parse-i3s-attribute.js
- modules/i3s/test/i3s-attribute-loader.spec.js
Sometimes in tileset in `attributeStorageinfo` one of attributes has no` attributeValues.valueType `data. We should anyway load such case just without any data.
For example we have such situation in[ New York](https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/NYC_Attributed_v17/SceneServer/layers/0) tilleset.
But if we are looking to [spec](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/value.cmn.md) we should have such value.
> I3S-picking - change attribute parsing logic

- modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
We should avoid using `CUSTOM_ATTRIBUTES_1`,` CUSTOM_ATTRIBUTES_2` etc by passing parse options to `DracoLoader`
> I3s-picking - fix feature-index parsing in compressed geometry

- modules/3d-tiles/src/tiles-3d-loader.js
- modules/core/src/lib/loader-utils/option-utils.js
- modules/gltf/src/gltf-loader.js
- modules/tiles/src/tileset/tile-3d.js
Hi!
When working with 3d-tiles my console was flooded with a variety of unresolved options. This PR fixes the following warnings:
1. `maxConcurrency`, `maxMobileConcurrency`: I was using those top level options, as specified also in the [docs](https://github.com/visgl/loaders.gl/blob/master/modules/core/docs/api-reference/parse.md), but they were generating warnings. I added them to `DEFAULT_LOADER_OPTIONS`. 
2. `baseUri`: It was generating warnings in the nested `GLTFLoader`. The `option-utils` logic adds `baseUri` if it is not present, but warns when it is. The simplest way I could avoid this without refactoring the logic was to add a specific condition to not warn about a top level `baseUri`.
3. `uri`: It is added to the top level by the `GLTFLoader` but gets warned as deprecated. I …
> Fixes for warnings regarding unresolved options and further separate i3s/3d-tiles options

- examples/experimental/i3s-17-and-debug/app-debug.js
- examples/experimental/i3s-17-and-debug/coloring-utils.js
- examples/experimental/i3s-17-and-debug/components/control-panel.js
- examples/experimental/i3s-17-and-debug/constants.js
- examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
- modules/tiles/src/tileset/tile-3d.js
I added ways to recolor tiles to make them stand out for debugging.
Now user can choose:
- original colors
- coloring by tile id (random)
- coloring by depth
> I3S - Tile coloring in debug application

- modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
Sometimes there is no `featureIds` and `faceRange` in geometry. We should check it before flattening process.
> I3S Parse content - check attributes before flatten process

- examples/experimental/i3s-17-and-debug/mesh-layer/mesh-layer.js
- examples/experimental/i3s-17-and-debug/mesh-layer/simple-mesh-layer-vertex.glsl.js
- examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
- modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
I implemented support of the texture atlas according to https://github.com/Esri/i3s-spec/blob/master/docs/1.7/geometryUVRegion.cmn.md . But it doesn't work for some reason.
This PR works for San Francisco 1.7:
> i3s: support texture atlas

- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js
I spent some time analyzing what `normalizeAttributesByIndicesRange` actually does. The case occurs when indices attribute has min and max properties. It looks like the function is legacy and we don't really need it anymore. For this particular tileset it breaks attribute arrays. The tileset is textured partially. It is correct. Some primitives have material without texture.
> tile-converter: fixes issue 1313

- examples/experimental/i3s-17-and-debug/components/semantic-validator.js
- examples/experimental/i3s-17-and-debug/constants.js
- examples/experimental/i3s-17-and-debug/tile-debug.js
It validates 2 things:
1. The tile is never seen. This can occur when a child lodMetric is so small, that the tile switches to a grandchild;
2. All neighbor tiles are refined at the same moment.
I didn't find tiles with 1st error - it is more critical.
I created some pictures explaining 2nd: https://docs.google.com/document/d/1tQoNLiH0m9bmTBW20TRXGYhDqxIynKm98iiMp5KEyng/edit?usp=sharing
> i3s-debug: LOD validation

- modules/i3s/src/helpers/promises-handler.js
- modules/i3s/src/i3s-attribute-loader.js
- modules/i3s/test/i3s-attribute-loader.spec.js
This fix allows to load all attributes and doesn't fail all loaded attributes if any of them are not fetched or parsed properly
> I3S-attribute-loader - Fix for attributes loading

- examples/experimental/i3s-17-and-debug/app-debug.js
- examples/experimental/i3s-17-and-debug/app.js
- examples/experimental/i3s-17-and-debug/mesh-layer/mesh-layer.js
- examples/experimental/i3s-17-and-debug/mesh-layer/simple-mesh-layer-vertex.glsl.js
- examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
- modules/3d-tiles/src/tiles-3d-loader.js
- modules/i3s/src/i3s-content-loader.js
- modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
- modules/i3s/test/i3s-loader.spec.js
- modules/i3s/test/lib/parsers/parse-i3s-tile-content.spec.js
- modules/tile-converter/src/3d-tiles-converter/helpers/b3dm-converter.js
- modules/tile-converter/test/3d-tiles-converter/helpers/b3dm-converter.spec.js
The reason of this PR to prepare for moving picking logic to` deck.gl` just using common naming strategy for I3S and 3DTiles.
There are few changes:
1. Rename ` featureIds -> segmentationData` to make it common for `I3S` and `3DTiles`.
2. Delete useless `_replaceFeatureIdsAndFaceRangeWithBatchId` because we don't need to flatten `featureIds` any more because we already do it in `parse-i3s-tile-content.js`.
> Refactoring in I3S loaders

- docs/table-of-contents.json
`Basis loader `and `Compressed texture loader` are moved to texture module.
> Website - Remove Basis + Compressed texture duplicated loaders from loaders list

- modules/csv/src/csv-loader.js
- modules/csv/src/libs/papaparse.js
- modules/csv/test/csv-loader.spec.js
- modules/csv/test/data/sample-empty-line.csv
Some CSV include an additional line, and I was trying to see how loaders can ignore such lines correctly using `skipEmptyLines`. 
I noticed that the `skipEmptyLines` option doesn't work for stream parsing. The parser gets stuck in an infinite loop, and no rows get reported if the `skipEmptyLines` is set (to either `true` or `greedy`). After some digging, it turns out to be related to two different bugs in Papaparse:
- `skipEmptyLines = true` hangs the parser if `chunkSize` isn't set, even though Papaparse has a default: https://github.com/mholt/PapaParse/issues/465
- `skipEmptyLines = greedy` hangs the parser when combined with using the `step` callback option (which we do to build the result): https://github.com/mholt/PapaParse/issues/825
I spent a few hours trying to see if this can be …
> Chore(CSV): fix skipEmptyLines handling for streaming parsing

- examples/experimental/i3s-17-and-debug/app-debug.js
- examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
Changes to move coloring logic from `tile-layer.js` file to `app-debug.js `to prepare merging changes back to deck.gl.
> I3S-Debug - Refactoring for tiles color

- modules/tile-converter/docs/api-reference/i3s-converter.md
- modules/tile-converter/scripts/converter.js
- modules/tile-converter/src/i3s-converter/i3s-converter.d.ts
- modules/tile-converter/src/i3s-converter/i3s-converter.js
- modules/tile-converter/test/i3s-converter/i3s-converter.spec.js
1. Rename `validateBoundingVolumes` -> `validate` flag.
2. Move `validation of refinement type` under `validate` flag to make converter output cleaner.
> Tile-converter - Rename "validateBoundingVolumes" -> "validation" flag

- examples/experimental/i3s-17-and-debug/helpers/build-minimap-data.js
- modules/i3s/src/i3s-content-loader.js
- Switch i3s-content-loader worker on;
- Fixes: `TypeError: t.getBoundingSphere(...).radius is not a function`
> i3s-debug: fix multiple viewports

- modules/gis/test/geojson-to-binary.spec.js
When working on #1390 I noticed that this test was taking a long time to execute. This change removes the inefficiency and makes the test run faster.
> CHORE(gis): Fix inefficient geojson-to-binary  test

- docs/whats-new.md
- modules/arrow/package.json
- modules/arrow/src/lib/arrow-table-batch.js
- modules/arrow/src/lib/encode-arrow.js
- modules/arrow/src/lib/parse-arrow-in-batches.js
- modules/arrow/src/lib/parse-arrow-sync.js
- modules/csv/test/csv-loader-arrow.spec.js
- modules/gis/test/geojson-to-binary.spec.js
- modules/tables/src/lib/table/table-types.d.ts
- tsconfig.json
- yarn.lock
Upgrades `apache-arrow` to the latest `4.0.0` version, given that we have been sitting on the old `0.17.1` version for a while now.
> Chore(Arrow): Upgrade apache-arrow to 4.0.0

- modules/mvt/package.json
- modules/mvt/src/lib/binary-vector-tile/features-to-binary.js
- modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.d.ts
- modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.js
- modules/mvt/test/mvt-loader.spec.js
- yarn.lock
visgl/loaders.gl#1356 implemented polygon triangulation using earcut in loaders.gl however seems more natural to have earcut in math.gl, so as to allow other projects to import it if needed. This PR moves earcut into math.gl, see https://github.com/uber-web/math.gl/pull/219 for more details
> Extract earcut

- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-tables.js
- modules/3d-tiles/test/tiles-3d-loader.spec.js
@ibgreen Please take a look at my idea to validate 28 bytes header to detect legacy or wrong `b3dm` file structure.
To be honest it not really sophisticated method to check that but I didn't find any code which was done for such kind of [test](https://github.com/visgl/loaders.gl/blob/master/modules/3d-tiles/test/lib/parsers/batched-model-3d-tile.spec.js#L44). Please let me know if where was such kind of validation earlier.
> Add support for legacy B3DM file format

- modules/tile-converter/src/i3s-converter/i3s-converter.js
In legacy b3dm files sometimes `sourceTileContent` is null.
> fix(3d-tiles): Add additional check for batchTableJson

- examples/website/3d-tiles/components/control-panel.js
It is not really good practice to use `dangerouslySetInnerHTML` in react. But in the control panel of 3d-tiles example we see the following picture:
All content under 'Tileset Credentials' header is made by using `dangerouslySetInnerHTML` attribute.
Possible solutions:
1. Transform pure `html` to `jsx` . For that perspective we need additional package which allows such transformation. I am not sure that we really need this.
2. Turn off `react/no-danger` rule in eslint config for files under example folder. I am not sure it is a good solution because we should avoid `dangerouslySetInnerHTML` in the future.
3. Just use /`* eslint-disable */ `comment for these lines. I think this is enough just because we get this html from trusted source and we don't need to be over secure.
@ibgreen  Your …
> Fix for dangerouslySetInnerHTML lint error

- examples/experimental/i3s-17-and-debug/components/tile-validator.js
Replace `componentDidMount` with `getDerivedStateFromProps`.
> Fix "no-did-mount-set-state" eslint error in tile-validator.js

- .eslintrc.js
- examples/website/textures/components/compressed-texture.js
1. Done some code improvements
2. Turned off `react/no-did-mount-set-state`  checking. If we take a look to the [componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount) spec it is a normal practice to do `async` operations and call `this.setState()` function there. So I decided to turn off checking for this method in the examples folder.
> Fix no-did-mount-set-state eslint error in compressed texture

- modules/loader-utils/src/index.ts
- modules/loader-utils/src/lib/request-utils/request-scheduler.ts
- modules/worker-utils/src/index.ts
When using the latest alpha package (`3.0.0-alpha20`) of loaders currently, the following errors surface when running TS checks:
```sh
$ tsc
node_modules/@loaders.gl/loader-utils/src/index.ts:3:3 - error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
3   WorkerLoaderObject,
~~~~~~~~~~~~~~~~~~
node_modules/@loaders.gl/loader-utils/src/index.ts:4:3 - error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
4   LoaderObject,
~~~~~~~~~~~~
node_modules/@loaders.gl/loader-utils/src/index.ts:5:3 - error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
5   WriterObject,
~~~~~~~~~~~~ …
```
> Fix(loader-utils|worker-utils): fix TS type exports for isolated modules

- examples/website/i3s/app.js
- modules/tiles/docs/README.md
- modules/tiles/docs/api-reference/tile-3d.md
- modules/tiles/docs/api-reference/tileset-3d.md
- modules/tiles/src/tileset/tile-3d.ts
- modules/tiles/src/tileset/tileset-3d.ts
- modules/tiles/src/tileset/traversers/tileset-traverser.ts
Hi! this is a long one.
As part of our work on Cesium 3d tiles with photogrammetry and three.js I ended up doing some changes to the loaders.gl tiles code which I detail in this PR:
1. Consolidate the tile `getPriority` function:
When working with heavy street-view-style photogrammetry tilesets, I always had to use `requestThrottling`, or the browser could not handle the amount of tiles being loaded. However, the priority function used for the request scheduler was using only `lodMetricValue`, not taking into account the distance to the camera. A priority function which resembles more the [CesiumJS function](https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Cesium3DTile.js#L1660) and takes both sse and camera distance into account was used in the [traversal …
> tiles: Tile traversal optimizations

- modules/tiles/src/tileset/tile-3d.ts
- modules/tiles/test/tileset/tile-3d.spec.js
There is no `distanceToCamera` method in `BoundingSphere` and `OrientedBoundingBox`
Changed to `distanceSquaredTo` method.
> Fix: Inside viewer request volume distance to camera

- modules/core/src/null-loader.ts
Oddly I wasn't able to reproduce this in the main repo (maybe some different in the typescript environment), but I got this error in my project using loaders.gl:
```
node_modules/@loaders.gl/loader-utils/src/null-loader.ts:34:5 - 
error TS2741: Property '[Symbol.asyncIterator]' is missing in 
type 'Promise<AsyncGenerator<ArrayBuffer, void, undefined>>' 
but required in type 'AsyncIterable<any>'.
34     (async function* parseInBatches() {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
35       // @ts-ignore
~~~~~~~~~~~~~~~~~~~
36       yield* asyncIterator;
~~~~~~~~~~~~~~~~~~~~~~~~~~~
37     })()
~~~~~~~~
```
And I could fix it by adding the following `@ts-ignore` ,
> Resolve typings in null-loader ParseInBatches

- modules/core/docs/api-reference/fetch-file.md
- modules/core/src/lib/fetch/fetch-file.ts
For #1538 , #1548
`fetchFile` currently accepts a loaders.gl options object but looks like it would accept a standard `fetch` `RequestInit` object which is confusing and causing bugs.
For now make sure that `fetchFile` accepts both `RequestInit` options and a loaders.gl options object.
I think we could make a case that `fetchFile` should just take a `RequestInit` object (it is named after `fetch` after all), but this is a first non-breaking step in that direction. I see some very few places in loaders that would need to be updated, in CesiumIONLoader.
https://github.com/visgl/loaders.gl/search?q=%22%7Bfetch%3A+headers%22
> fix(core): fetchFile option handling

- modules/loader-utils/src/types.ts
- modules/tile-converter/src/i3s-converter/i3s-converter.ts
- modules/tile-converter/src/types.ts
It is first small step to convert i3s-tile-converter to typescript.
Next steps:
1. Remove d.ts file and move all types to i3s-converter.ts file.
2. Enable validation for i3s-converter.ts in ts config.
> Convert i3s-tile-converter to typescript

- modules/core/src/lib/api/parse.ts
- modules/excel/src/excel-loader.ts
- modules/excel/src/index.ts
- modules/excel/src/lib/parse-excel.js
- modules/excel/src/workers/excel-worker.js
- modules/excel/test/excel-loader.spec.js
- modules/las/src/index.ts
- modules/las/src/las-loader.ts
- modules/las/src/lib/parse-las.ts
- modules/las/src/workers/las-worker.js
Reorganizing the `excel-loader` (1MB) and `las-loader` (700KB) modules so that their `WorkerLoader` objects can be imported (via an admittedly ugly dist subpath) without importing any other dependencies. It is just an object so doesn't matter which dist it comes from.
This should not break any existing code, and if it works will make it possible to import worker loaders without having to first bundle and then "tree shake out" the code.
> feat: unbundled loaders

- modules/tiles/src/tileset/tile-3d.ts
- modules/tiles/src/tileset/tileset-3d.ts
- modules/tiles/src/tileset/traversers/i3s-tileset-traverser.ts
- modules/tiles/test/tileset/tile-3d.spec.js
I didn't find a place where `basePath` is using in `TileHeader` class.
So I decided to remove it.
Also there were some issues after I changed arguments order in [PR](https://github.com/visgl/loaders.gl/pull/1536/files). I fixed it here as well.
> Remove basePath option from TileHeader class

- modules/worker-utils/src/lib/env-utils/version.ts
When bundling against the source I got a runtime error:
```
Uncaught (in promise) ReferenceError: __VERSION__ is not defined
at version.ts:5
```
I tried to fix it according to other `version.ts` files.
> Worker-utils: Fix for runtime error: ReferenceError: __VERSION__ is not defined

- modules/tiles/src/tileset/traversers/i3s-tileset-traverser.ts
Hi,
This fixed for me the following typescript error:
```
TS2559: Type '{ i3s: any; }' has no properties in common with type 'LoaderOptions'
```
> use loadOptions in i3s-tileset-traverser

- babel.config.js
- package.json
Version injection via `plugin-version-inline` does not work in cases where we don't build locally in a module directories, for instance when we run node tests, build test bundles or websites.
Since we sync all module versions we should be able to use the version in `lerna,json`.
> chore: Fix version injection for node and workers

- .eslintrc.js
- modules/core/src/lib/api/select-loader.ts
I think this might be related to eslint/typescript version, because again I only had problem in another project that is using loaders.gl and should be using latest typscript and eslint.
```
TS2488: Type 'Loader | Loader[]' must have a '[Symbol.iterator]()' method that returns an iterator.
../../loaders.gl/modules/core/src/lib/api/select-loader.ts: (80:22)
80   loadersArray = [...(loadersArray || []), ...getRegisteredLoaders()];
```
It does make sense if though there is that `return` statement.
When I fixed it to `(loaders as Loader[])` I got the error **only in loaders.gl (not in my project)** from eslint:
```
79:19  error    This assertion is unnecessary since it does not change the type of the expression  @typescript-eslint/no-unnecessary-type-assertion
```
So I could only disable that …
> select-loaders type assertion

- modules/core/src/lib/fetch/read-file.ts
- modules/core/src/node/fs.ts
- modules/geopackage/src/lib/parse-geopackage.ts
- modules/gis/package.json
- modules/gis/test/binary-to-geojson.spec.js
- modules/gltf/src/lib/extensions/gltf-extensions.ts
- modules/gltf/src/lib/parsers/parse-glb.ts
- modules/gltf/src/meshopt/meshopt-decoder.ts
- modules/json/test/lib/parser/streaming-json-parser.spec.js
- modules/loader-utils/src/lib/request-utils/request-scheduler.ts
- modules/loader-utils/src/lib/worker-loader-utils/create-loader-worker.ts
- modules/loader-utils/src/lib/worker-loader-utils/parse-with-worker.ts
- modules/parquet/src/parquet-loader.ts
- modules/parquet/src/parquetjs/reader.ts
- modules/ply/src/lib/parse-ply-in-batches.ts
- modules/polyfills/src/node/file/blob-stream-controller.ts
- modules/polyfills/src/node/file/blob-stream.ts
- modules/polyfills/src/node/file/file-reader.ts
- modules/polyfills/test/fetch-node/fetch.node.spec.js
- modules/shapefile/src/lib/parsers/parse-shapefile.ts
- modules/shapefile/src/lib/parsers/parse-shp-geometry.ts
- modules/shapefile/test/shapefile-loader.spec.js
- modules/tile-converter/package.json
- modules/tile-converter/src/lib/utils/compress-util.js
- modules/worker-utils/src/lib/worker-api/process-on-worker.ts
- modules/worker-utils/src/lib/worker-farm/worker-pool.ts
- tsconfig.json
- This removes all lint warnings except three i3s/tile-converter warnings.
- I am disabling tile-converter module in `tsconfig.json` because a lot of warnings are sporadically triggered (not sure what triggers them yet, doesn't happen always).
> chore: Remove lint warnings

- docs/README.md
@ibgreen  After this [line](https://github.com/visgl/loaders.gl/pull/1617/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R19) was added we get an issue related to parsing such markup via `gatsby-plugin-mdx`
This plugin normally works with comments outside of html markup.
I also tried to add [gatsby-remark-remove-comments](https://www.gatsbyjs.com/plugins/gatsby-remark-remove-comments/?=comments) plugin. It doesn't help.
I decided to just remove it from markup for now.
Please let me know if you have a better solution for that.
> Remove commented markup from readme.md

- modules/tiles/src/tileset/helpers/i3s-lod.ts
- modules/tiles/test/tileset/index.js
- modules/tiles/test/tileset/traversers/index.js
- modules/tiles/test/tileset/traversers/tileset-traverser.spec.js
There is a link in code:
https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space
I found a formula there to calculate projected radius:
`return 1.0 / Math.tan(fov) * r / Math.sqrt(d * d - r * r); // Right`
Now it doesn't work without magic number `300`. Possibly, `d` and `r` are calculated wrong way.
Anyway, refinement works better now.
I checked this Munich and layers from website (SF, NY).
https://user-images.githubusercontent.com/18549629/124549302-a6ec3e80-de37-11eb-9070-2a2e52f4868f.mp4
> tiles: fix i3s LOD selection

- modules/i3s/package.json
- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
One of three failing typescript errors when importing loaders into an app.
> fix(i3s): import type TypedArray

- modules/i3s/test/i3s-loader.spec.js
- Fixes one of two errors when running `yarn test browser` in Safari.
- The other error in MVT module seems to be a precision issue during deep equal, requires a bit more work.
Neither error would affect apps, but good to have a clean run.
> fix(i3s): Safari test error

- modules/core/src/lib/api/select-loader.ts
- modules/shapefile/src/lib/parsers/parse-shp.ts
MVTLayer of deck.gl is throwing an exception at versions 8.4.3+:
```
tile-layer.js:18 Error: No valid loader found data: "", contentType: "null" url: http://localhost:8282/user/carto/bigquery/tileset/1/0/0
at _callee$ (select-loader.js:29)
at tryCatch (runtime.js:45)
at Generator.invoke [as _invoke] (runtime.js:271)
at Generator.prototype.<computed> [as next] (runtime.js:97)
at asyncGeneratorStep (asyncToGenerator.js:3)
at _next (asyncToGenerator.js:25)
at asyncToGenerator.js:32
at new Promise (<anonymous>)
at asyncToGenerator.js:21
at _selectLoader (app.js:56663)
value @ tile-layer.js:18
```
It happens when a 204 is received and there is no Content-Type because of the fact there is no content in the response. [RFC](https://tools.ietf.org/html/rfc2616#section-7.2.1) says the following:
> …
> Avoid throw exception when a 204 is received

- examples/experimental/terrain/package.json
This configuration allows to debug `modules/terrain/src/lib/parse-terrain.js` with `yarn start-local-deck`. I can't setup it to debug with `yarn start-local`. It runs code from `node_modules`.
> examples: terraint debug with start-local

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.js
- modules/3d-tiles/src/tiles-3d-loader.ts
- modules/3d-tiles/test/tiles-3d-loader.spec.js
- modules/tiles/test/tileset/tileset-3d.spec.js
- `t.plan(number);` works in browser instead of `t.end()`
- "Tileset3D#loads json from base64 URL" - moved to "3d-tiles" module;
- "Tileset3D#rejects invalid tileset version" - removed. It doesn't have sense because the module is unified now for I3S and 3DTiles.
> tiles: improve testing

- modules/csv/src/csv-loader.ts
- modules/json/src/geojson-loader.ts
- modules/json/src/index.ts
- modules/json/src/json-loader.ts
CSVLoader doesn't handle batchSize='auto' but requires override.
Having to set a global override is not ideal, so build in a default override.
> fix(csv): options.batchSize

- modules/parquet/package.json
- yarn.lock
Internal dependency (@loaders/*) versions must match the current package version, otherwise lerna does not bump them during publish.
> [parquet] fix internal dependency versions

- modules/geotiff/src/lib/tiff-pixel-source.ts
- modules/zarr/src/lib/zarr-pixel-source.ts
https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties
This syntax doesn't work when we run `yarn test node-debug`
> chore(tiff): fix yarn test node-debug

- modules/3d-tiles/src/lib/classes/tile-3d-batch-table-hierarchy.js
I came across this bug trying to bundle `deck.gl` with `esbuild`.
```bash
❯ esbuild --bundle --external:util --external:react --external:geotiff --format=esm index.js
> node_modules/@loaders.gl/3d-tiles/dist/esm/lib/classes/tile-3d-batch-table-hierarchy.js:40:4: error: Cannot assign to "classIds" because it is a constant
40 │     classIds = binaryAccessor.createArrayBufferView(binaryBody.buffer, binaryBody.byteOffset + classIds.byteOffset, instancesLength);
╵     ~~~~~~~~
node_modules/@loaders.gl/3d-tiles/dist/esm/lib/classes/tile-3d-batch-table-hierarchy.js:31:8: note: "classIds" was declared a constant here
31 │   const classIds = hierarchyJson.classIds;
╵         ~~~~~~~~
> node_modules/@loaders.gl/3d-tiles/dist/esm/lib/classes/tile-3d-batch-table-hierarchy.js:50:6: error: Cannot …
```
> fix(3d-tiles): `const` -> `let` for reassignment in tile-3d-batch-table-hierarchy

- modules/i3s/src/i3s-content-loader.ts
- modules/worker-utils/src/lib/worker-api/get-worker-url.ts
This reverts commit 48672a87f617aa37bdc0414694d022294f747692.
We have to use 'beta' workers on master. `latest` are for release branch.
> Revert "Load workers of `latest` versions (#1673)"

- modules/worker-utils/src/lib/process-utils/child-process-proxy.ts
Further discussion here: https://github.com/hms-dbmi/viv/pull/480#issuecomment-892970913
TL;DR - when `@loaders.gl/worker-utils` [transitioned to TS](visgl/loaders.gl@787271a#diff-653aabc2ef3b70398fe5a382c9f7c6359a5ecdd223901c6b15ea54b6ce418e67), changing 
```javascript
import ChildProcess from 'child_process';
```
to
```typescript
import {spawn, ChildProcess, SpawnOptionsWithoutStdio} from 'child_process';
```
broke our build when we tried to upgrade to deck.gl 8.5. This is because the `"empty"` resolution for some bundlers for node builtins is only a `default` export, so using named imports won't be resolved. This may seem like a bundler/bundler-plugin issue, but bundlers will resolve `package.json` "browser" differently. Using a `default` import for node-builtins will likely reduce …
> fix(worker-utils): Use default import for "child_process"

- modules/tiles/src/tileset/tile-3d.ts
Hi!
I tested the condition I proposed in #1565 ([here](https://github.com/visgl/loaders.gl/issues/1565#issuecomment-873561746)) and it does seem to improve performance, with less tiles being loaded.
I checked the most recent i3s and 3d-tiles demo websites and it seems to work well, but please verify this with the latest i3s test-cases.
Thank you!
(cc: @ibgreen , @belom88 , @hpugis)
> Add an out-of-view condition based on 'touchedFrame' to 3d tiles request scheduling

- modules/core/src/index.ts
- modules/core/src/iterators/make-stream/make-node-stream.ts
- modules/core/src/iterators/make-stream/make-stream.ts
Similar issue to #1742 & #1741. Ran into an issue with `rollup` and `vite`.
Not sure if you have a preference for implementing this. I figure that is someone wants to "fix" the import weirdness, they will need to navigate to `make-node-stream.ts` to change the default export and will see the comment.
> fix(core): Help browser resolution `make-node-stream`; use default export

- modules/compression/src/lib/lz4-compression.ts
- modules/compression/test/compression.spec.js
- modules/parquet/src/parquetjs/compression.ts
Parquet files with LZ4 compression doesn't have "header" with magic number + frame descriptor part.
The idea is to add dummy header to file buffer.
[Spec](https://android.googlesource.com/platform/external/lz4/+/HEAD/doc/lz4_Frame_format.md)
Here an [example](https://github.com/Benzinga/lz4js/blob/master/lz4.js#L474) of encoding lz4 file from package which we use to decompress such files.
> Add part of dummy header to LZ4 parquet files

- examples/website/i3s/app-debug.js
- examples/website/i3s/package.json
In the mobile version, tooltips are not needed. They just break the layout.
> I3S-Debug-App - Disable info picking tooltips for mobile

- modules/compression/src/lib/compression.ts
- modules/compression/src/lib/lz4-compression.ts
- modules/compression/test/compression.spec.js
- modules/parquet/src/parquetjs/compression.ts
- modules/parquet/test/data/files.js
- modules/parquet/test/expected.js
- modules/parquet/test/parquet-loader.spec.js
Added Block Level Decoding for Parquet LZ4 compressed frames.
Solution was found in [Apache Parquet Compression spec](https://github.com/apache/parquet-format/blob/master/Compression.md) and appropriate js lib is  [node-lz4](https://github.com/pierrec/node-lz4) implementation.
It is adapted to work without Node.js `Buffer` object. As a result it can be performed in browser side for parsing.
> Add LZ4 compression support for Parquet

- modules/parquet/src/lib/convert-schema.ts
- modules/parquet/src/parquetjs/schema/declare.ts
- modules/parquet/src/parquetjs/schema/schema.ts
- modules/parquet/src/parquetjs/schema/shred.ts
- modules/parquet/src/parquetjs/schema/types.ts
- modules/parquet/src/parquetjs/utils/decoders.ts
- modules/parquet/test/data/files.js
- modules/parquet/test/expected.js
- modules/parquet/test/parquet-loader.spec.js
DECIMAL type can annotate different physical types.
Implemented here:
`toPrimitive` functions have't been tested.
> feat(parquet): decimal logic type

- examples/website/i3s/url-utils.js
Now I**3S App** and **I3S-Debug App** are able to handle the following tileset urls:
1. /?url=https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer
2.  /?url=https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/
3.  /?url=https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/layers/0
3.  /?url=https://tiles.arcgis.com/tiles/u0sSNqDXr7puKJrF/arcgis/rest/services/Frankfurt2017_v17/SceneServer/layers/0/
> fix(i3s): change logic of tileset urls parsing for i3s apps

- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
Browser has not the same context object as in node.js script. Therefore while conversion (I3S -> 3DTiles) we should use parsing in ordinary way.
> fix(website/tile-converter): parsing textures

- modules/i3s/src/lib/parsers/constants.ts
- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
- modules/i3s/src/lib/utils/url-utils.ts
- modules/i3s/src/types.ts
Bumping `xmldom` to `@xmldom/xmldom` as documented here: https://github.com/xmldom/xmldom/issues/271
I have a project failing a Dependabot security alert for the `xmldom` package. The suggested patch is this:
```
Update to one of the fixed versions of @xmldom/xmldom (^0.5.1 || ^0.6.1 || >=0.7.0). ❗ Users of xmldom should switch to @xmldom/xmldom to not be affected by this vulnerability.
See issue #271 for the status of publishing xmldom to npm or join #270 for Q&A/discussion until it's resolved.
```
The new `@xmldom/xmldom` package looks to be just a fork that's now being maintained, so we shouldn't have any upgrade issues.
The new package for reference - https://github.com/xmldom/xmldom
> build(deps): bump xmldom 0.5.0 to @xmldom/xmldom 0.7.5

- modules/compression/package.json
- modules/compression/src/brotli/decode.ts
- modules/compression/src/lib/brotli-compression.ts
- modules/compression/src/lib/zstd-compression.ts
- modules/compression/src/workers/worker.ts
- modules/crypto/package.json
- modules/draco/package.json
- modules/geotiff/package.json
- modules/images/package.json
- modules/loader-utils/package.json
- modules/parquet/package.json
- modules/parquet/src/parquetjs/compression.ts
- modules/parquet/src/parquetjs/parser/parquet-envelope-reader.ts
- modules/parquet/src/parquetjs/parser/parquet-reader.ts
- modules/parquet/src/parquetjs/utils/file-utils.ts
- modules/tile-converter/package.json
- modules/worker-utils/package.json
- package.json
- yarn.lock
Speeds up the remaining build scripts. 
Bizarrely this builds locally but not on CI, seems esbuild works differently on different platforms, or there is something different in how the crypto libraries are built on linux.
> chore: Move all libs to esbuild

- modules/json/src/index.ts
- modules/json/src/lib/parse-json-in-batches.ts
Based on feedback from https://github.com/keplergl/kepler.gl/pull/1212.
Kepler is currently just using the streaming system to drive progress bars and remain interactive while parsing large files. It does yet not take advantage from the partial data delivery to start early processing or visualization of the data.
The final stitching of data gets quite complicated when supporting multiple jsonpaths and it makes sense that loaders.gl provides a utiliity to take care of this.
Still a WIP: This PR needs some test cases before it lands. Once it lands it could be back ported to 2.2.
> json: rebuild json payload based on streamed json path

- modules/worker-utils/src/lib/worker-api/get-worker-url.ts
- modules/worker-utils/src/types.ts
This PR allows for a non-nested `workerUrl` option for the `CompressionWorker`.
For the `CompressionWorker`, `workerOptions` is currently not nested correctly. For most loaders, you'd have options within an object where the key is the loader's `id`:
```js
{
mvt: {
coordinates: ...
}
}
```
but the `CompressionWorker` overrides this and uses the top level `compression` key to hold the _type of compression_ not an options object. To not break backwards compatibility, this allows the `CompressionWorker` to have a `workerUrl` option at the top level.
Should this be documented in the `processOnWorker` page? The `CompressionWorker` page?
> Allow top-level workerUrl for CompressionWorker

- modules/gis/src/lib/geojson-to-binary.ts
- modules/gis/test/geojson-to-binary.spec.js
- modules/mvt/src/lib/binary-vector-tile/features-to-binary.ts
- modules/mvt/src/lib/types.ts
Fix for https://github.com/visgl/loaders.gl/issues/1951
> Detect when 64 bit precision is required for a numericProp in MVTLoader

- examples/website/i3s/app-debug.js
- examples/website/i3s/app.js
Terrain data source has only 15 levels available. It is described [here](https://github.com/tilezen/joerd/blob/master/docs/use-service.md#specify-z-x-and-y-tile-coordinates).
> fix(i3s-app, i3s-debug-app): set max zoom property for terrain layer

- test/modules.js
- yarn.lock
I picked a number of commits from `master` branch and found out that the converter tests are switched off on the `3.1-release` branch
> test: switch converter tests on

- modules/3d-tiles/package.json
- modules/arrow/package.json
- modules/gltf/package.json
- modules/i3s/package.json
- modules/i3s/src/i3s-building-scene-layer-loader.ts
- modules/i3s/src/i3s-content-loader.ts
- modules/ply/package.json
- modules/polyfills/test/fetch-node/fetch.node.spec.js
- modules/textures/src/lib/parsers/basis-module-loader.ts
- modules/textures/src/lib/utils/version.ts
- modules/tile-converter/package.json
- modules/tiles/package.json
- modules/worker-utils/src/lib/env-utils/version.ts
- modules/worker-utils/src/lib/library-utils/library-utils.ts
- modules/worker-utils/src/lib/worker-api/get-worker-url.ts
- modules/zip/package.json
- yarn.lock
- replace `beta` with `latest`;
- fix peer-dependency version: `"@loaders.gl/core": "3.1.0"`;
- yarn.lock
> fix: load workers of latest version

- examples/get-started/get-started-rollup/package.json
- examples/get-started/get-started-rollup/rollup.config.js
For #2000 
- Latest loaders.gl libraries
- Latest rollup
> chore(examples): Update get-started-rollup example dependencies.

- modules/arrow/package.json
- modules/compression/package.json
- modules/core/package.json
- modules/crypto/package.json
- modules/draco/package.json
- modules/excel/package.json
- modules/flatgeobuf/package.json
- modules/i3s/package.json
- modules/json/package.json
- modules/las/package.json
- modules/mvt/package.json
- modules/obj/package.json
- modules/parquet/package.json
- modules/pcd/package.json
- modules/ply/package.json
- modules/shapefile/package.json
- modules/terrain/package.json
- modules/textures/package.json
- modules/wkt/package.json
- modules/worker-utils/package.json
For issue #2014, I ran the following script in the `modules` folder:
```
grep "\"build-worker\": \"esbuild" * -Rl | xargs sed -i -r 's/(\"build-worker\".*)\"$/\1 --define:__VERSION__=\\\\\\\"\$npm_package_version\\\\\\\""/g'
```
Then I noticed it still missed a few scripts that were named differently so I fixed those manually.
Note that there are two issues with this:
1.  Does not work on Windows traditional cmd.  I tested this on a traditional Windows cmd and it didn't work. It requires using `%npm_package_version%`. It can be fixed for example using [cross-var](https://github.com/elijahmanor/cross-var), but I noticed that also `yarn bootstrap` and `build` failed with various errors, so I figure this is not really maintained on Windows?
2. As @ibgreen noted: 
```
I suspect this might …
```
> Added __VERSION__ definitions to build-worker scripts 

- modules/i3s/src/i3s-attribute-loader.ts
- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js
- modules/tile-converter/test/i3s-converter/i3s-converter.spec.js
1. Added default values for `roughnessFactor` and `metallicFactor` based on [spec](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/pbrMetallicRoughness.cmn.md)
2. Fix for loading `picking attributes `in` I3S-App `
> fix(tile-converter,i3s-app): default value of pbr + app picking

- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
- modules/tile-converter/src/i3s-converter/i3s-converter.ts
An error occurred when a scene with materials without textures was parsed. When trying to get a uv0 buffer, we went beyond the buffer boundary. Parsing 'Geometry buffer' depends on 'ordering'. In one scene some materials may have texture while others may not. Because of this, we cannot guarantee to remove the error by affecting only the 'ordering', removing the uv0 from it. Therefore, we will simply skip the step with getting uv0 if getting it goes beyond the boundaries of the buffer.
spec: https://github.com/Esri/i3s-spec/blob/master/docs/1.8/defaultGeometrySchema.cmn.md
> fix(parse-i3s-tile-content): I3S conversion issue without draco

- modules/tile-converter/src/i3s-converter/helpers/node-pages.ts
We have the report from @Tamrat-B. I hope this PR will fix it. @Tamrat-B  could you check it on your big dataset.
```
.
..
Z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\6403.json saved.
z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\6404.json saved.
z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\6407.json saved.
z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\6406.json saved.
z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\6405.json saved.
z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\4094.json.gz: compression error!
node:internal/process/promises:246
triggerUncaughtException(err, true /* fromPromise */);
^
[Error: EMFILE: too many open files, open 'z:\slpk_loaders_315\Krimpen\SceneServer\layers\0\nodepages\4094.json'] …
```
> fix(tile-converter): simultaneous file writing

- examples/experimental/terrain/package.json
- modules/terrain/src/lib/helpers/skirt.ts
- modules/terrain/test/lib/helpers/skirt.spec.js
- swap winding order of triangles during skirts generation
- test for resulting indices
- fix for terrain yarn start-local
Skirts aren't visible when culling is enabled in <Deck parameters={{cull: true}} ...>
> fix(terrain): swap winding order of skirts to match winding order of terrain

- examples/website/geospatial/app.js
- examples/website/geospatial/package.json
- modules/geopackage/docs/api-reference/geopackage-loader.md
- modules/geopackage/package.json
- modules/geopackage/src/geopackage-loader.ts
- modules/geopackage/src/lib/parse-geopackage.ts
- yarn.lock
- sql.js 1.6.2 doesn't seem to have worker files published at `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.2/`
- sql.js 1.6.1 fails to load with error `LinkError: WebAssembly.instantiate(): Import #0 module="a" function="a" error: function import requires a callable`
- sql.js 1.6.0 makes the page hang when testing with the Geospatial example app in `examples/website/`.
sql.js 1.5.0 seems to work.
> Pin sql.js 1.5.0 in GeoPackageLoader

- modules/core/src/lib/utils/response-utils.ts
I presume the intention was to use only the first 60 chars - but instead it was removing the first 60 chars.
> Fix error message truncation in checkResponse

- modules/gltf/docs/README.md
- modules/gltf/docs/api-reference/gltf-loader.md
fixes https://github.com/visgl/loaders.gl/issues/2120
The new md urls do not include the .md extension. Please let me know if this is incorrect.
> fix some postProcessGLTF and glTF Extensions urls

- modules/gltf/src/lib/extensions/EXT_meshopt_compression.ts
- modules/gltf/src/lib/parsers/parse-gltf.ts
This code is dedicated from https://github.com/visgl/loaders.gl/pull/2035 . 
I checked it with 3DTiles dataset:
Textures are in black because of KHR_texture_transform extension that is not supported by @loaders.gl
> fix(gltf): meshopt compression extension

- modules/tile-converter/src/3d-tiles-converter/3d-tiles-converter.ts
- modules/tiles/src/tileset/tileset-3d.ts
Previously we changed `I3SLoader` to load root node asynchronously. It affected the tile-converter.
> fix(tile-converter): async root node loading

- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts
Fix the transformation order per spec:
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#reference-node
Should be `translation * rotation * scale`
> fix(tile-converter): node transformation order

- modules/tile-converter/src/converter-cli.ts
Fixes regression of https://github.com/visgl/loaders.gl/pull/2157
```
A 3D tile failed to load: undefined Install '@loaders.gl/polyfills' to parse images under Node.js
A 3D tile failed to load: undefined Install '@loaders.gl/polyfills' to parse images under Node.js
```
> fix(tile-converter): import polyfills

- modules/schema/src/index.ts
Import from root of `apache-arrow` fails build with errors kind of:
```
ERROR in /home/user/apps/loaders.gl/node_modules/apache-arrow/Arrow.dom.mjs 33:0-2582
Can't reexport the named export 'Visitor' from non EcmaScript module (only default export is available)
```
Originally `convertMesh` was done for `LASLoader` but related code was commented due to issue on the website:
https://github.com/visgl/loaders.gl/blob/7d8300f78deca9dd688b5605ecc8f38ff28f768e/modules/las/src/lib/parse-las.ts#L28
Possibly the root cause is the same.
> fix(schema): failing imports from apache-arrow

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts
- modules/3d-tiles/test/index.js
- modules/3d-tiles/test/lib/parsers/parse-3d-tile-header.spec.js
Tilesets can use absolute paths or even fully qualified URLs in the
content.uri field. This patch adds support for all of those cases.
How would I best go about testing this? Would it be ok to add a new Tileset to `test/data/Tilesets` specifically to test the url-handling? Or add some unit-tests just for the normalize-functions?
> fix(3d-tiles): add support for absolute content-uris

- modules/3d-tiles/test/data/Tilesets/TilesetGlobal/tileset.json
- modules/tiles/src/tileset/tileset-3d.ts
- modules/tiles/test/tileset/tileset-3d.spec.js
Fixes the crash occuring in Tileset3D when the bounding-box center is at
the cartesian center and thus the cartographic center can not be
unambiguously computed.
fixes #2196
> fix(3d-tiles): prevent crash when cartographic center is undefined

- modules/polyfills/src/index.ts
I just had the situation where I didn't want to use the whole set of polyfills, but wanted to pass fetchNode to load like this:
```typescript
const batches = await loadInBatches(shapeFilePath, ShapefileLoader, {
fetch: fetchNode,
});
```
Sadly I think the only way currently is via a file import from `dist`: `@loaders.gl/polyfills/dist/node/fetch/fetch.node`. I'd say we could add an export to make that easier.
> chore(polyfills): add export for fetchNode

- modules/3d-tiles/src/index.ts
- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-implicit-tiles.ts
- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-subtree.ts
- modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts
- modules/3d-tiles/src/tile-3d-subtree-loader.ts
- modules/3d-tiles/src/tiles-3d-loader.ts
- modules/3d-tiles/src/types.ts
- modules/gltf/src/index.ts
- modules/gltf/src/lib/parsers/parse-gltf.ts
- modules/tile-converter/src/i3s-attributes-worker.ts
- modules/tile-converter/src/i3s-converter/helpers/batch-ids-extensions.ts
- modules/tile-converter/src/i3s-converter/helpers/gltf-attributes.ts
- modules/tiles/src/tileset/tile-3d.ts
In 3DTiles, not only the root tile can be implicit, but also the child tile. We have to deal with this as well.
> fix(implicit-tiling): handle child tiles

- modules/tile-converter/src/deps-installer/deps-installer.ts
- modules/tile-converter/test/deps-installer/deps-installer.spec.js
Prevent `install-dependencies` from rewriting actual workers during tests
> fix(tile-converter): install deps test

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts
- modules/3d-tiles/src/tiles-3d-loader.ts
To download implicit tiling subtrees from cesium we need to pass token in options.
> fix(3d-tiles): add options to normalizeTileHeaders

- modules/tile-converter/src/converter-cli.ts
This PR allows converting
`node converter.min.js --input-type 3DTILES --tileset c:\tmp\tile-converter\tilesets\TILESET_NAME\tileset.json --max-depth 6 --slpk --name TILESET_Windows`
> fix(tile-converter): i3s - handle file path with "\"

- modules/tile-converter/src/i3s-converter/helpers/coordinate-converter.ts
- modules/tile-converter/src/i3s-converter/i3s-converter.ts
- modules/tile-converter/test/i3s-converter/helpers/coordinate-converter.spec.js
- modules/tile-converter/test/i3s-converter/i3s-converter.spec.js
The issue is reproduced for Japanese dataset (Eastern semisphere). We can't disclose the actual dataset.
Expected result:
"fullExtent":{**"xmin":136.8512835031769**,**"xmax":136.92452109055998**,"ymin":35.121734280476964,"ymax":35.15768129440385,"zmin":48.7547465655491,"zmax":2361.049808624967} 
z values are taken from the root node bounding volume
Actual result:
"fullExtent":{**"xmin":136.92452109055998**,"ymin":35.121734280476964,**"xmax":136.8512835031769**,"ymax":35.15768129440385,"zmin":-1181.3147795024154,"zmax":1356.6865765038197} where z values are extremely big
Another issue - zmin and zmax. Now they are calculated from MBS. If original tileset has region, it will convert to MBS. So zmin and zmax could be not relevant to the actual extent.
Now, if the original dataset has region …
> fix(tile-converter): i3s - fix fullExtent calculation

- modules/tile-converter/src/i3s-converter/json-templates/shared-resources.ts
- modules/tile-converter/test/i3s-converter/helpers/shared-resources.spec.js
- modules/tile-converter/test/index.js
According to https://github.com/Esri/i3s-spec/blob/master/docs/1.7/sharedResource.cmn.md
arrays for MaterialDefinitions are expected to have 3 elements (r, g, b).
> fix(i3s-converter): fix default arrays in shared-resources.ts

- modules/i3s/src/lib/parsers/constants.ts
- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
Fix loading of tilesets with UVRegions like https://tiles.arcgis.com/tiles/z2tnIkrLQ2BRzr6P/arcgis/rest/services/SanFrancisco_Bldgs/SceneServer/layers/0
with not compressed textures and not compressed geometry.
> fix(i3s): parse not compressed attributes

- examples/website/wms/app.tsx
- examples/website/wms/examples.js
- examples/website/wms/imagery-layer.ts
- modules/wms/src/index.ts
- modules/wms/src/lib/data-sources/adhoc-image-service.ts
- modules/wms/src/lib/data-sources/image-service.ts
- modules/wms/src/lib/data-sources/image-source.ts
- modules/wms/src/lib/data-sources/wms-service.ts
- modules/wms/test/data-sources/wms-service.spec.ts
Add new `AdHocImageSource` that allows URL template strings to be used as data sources to quickly wire up new imagery sources.
Tested with ArcGISImageServer template URL:
> feat(wms): AdHocImageSource - initial URL template support

- modules/wms/src/index.ts
- modules/wms/test/lerc/lerc-level2.spec.ts
- modules/wms/test/lerc/lerc-sanity.spec.ts
Need to fix bundling issues before including this loader.
> fix(wms): Unbundle LERCLoader to unblock esbuild applications

- examples/get-started/bundle-with-vite/package.json
- examples/get-started/bundle-with-vite/tsconfig.json
- modules/loader-utils/src/lib/path-utils/path.ts
- modules/loader-utils/src/types.ts
Hi,
regarding to https://github.com/visgl/loaders.gl/pull/2373.
- (examples/get-started/bundle-with-vite) fixed `vite` version (previous one does not exist)
- (examples/get-started/bundle-with-vite) fixed `tsconfig.json` to use correct `app.ts`
- (modules/loader-utils/src/lib/path-utils/path.ts) added types mentioned in https://github.com/visgl/loaders.gl/issues/2372#issuecomment-1443417094 and my previous PR https://github.com/visgl/loaders.gl/pull/2373
I'm still not able to build `vite` locally, but at least it has correct version and I can continue. There are some TS errors in other modules similar to `loader-utils` ^^ it seems. `app.ts` can be fixed quickly, but I don't know what to do with `apache-arrow`
> Fix vite deps + add types to loader-utils/src/types.ts

- modules/3d-tiles/wip/tile-3d-header.md
- modules/tiles/src/tileset/helpers/bounding-volume.ts
- modules/tiles/src/tileset/tile-3d.ts
- modules/tiles/test/tileset/tile-3d.spec.js
Related: https://github.com/visgl/deck.gl/pull/7795
To support Tile3DLayer + TerrainExtension in deck.gl, I'm proposing a unified API between 2d and 3d tile headers:
`tile.boundingBox: [min: number[], max: number[]]`
- Add `Tile3D.boundingBox` member
- Docs
- Test
> (feat)tiles: add boundingBox to Tile3D class

- examples/website/wms/app.tsx
- examples/website/wms/components/control-panel.tsx
- examples/website/wms/package.json
@ibgreen this is a trial POC for showing the JSON of the GetCapabilities using the Monaco editor in read-only mode. Thus, this replaces the JSON which was in a `<pre>` element, and makes a few other styling changes to the side control panel.
I wanted to give this a go first before looking into the xml 🔄  json side-by-side dual Monaco editors idea. Thoughts?
> WMS Example: show capabilities metadata with Monaco editor

- website/docusaurus.config.js
fixes invalid navigation to `https://loaders.gl/deck.gl`
> fix docusaurus footer links typo

- modules/tile-converter/package.json
- test/modules.js
- yarn.lock
Here is a fix for tile-converter dependences and enabling tile-converter tests that have been disabled in PR https://github.com/visgl/loaders.gl/pull/2410
Here is the end of output for yarn test node:
1..5056
Done in 99.53s.
@ibgreen Could you please review?
> fix(tile-converter): tile-converter dependencies changed and tests enabled

- examples/website/3d-tiles/app.tsx
- examples/website/3d-tiles/components/control-panel.jsx
- examples/website/i3s/src/app.tsx
- website/src/styles.css
1. Width of examples from
to
2. Stats widget issue (I3s and 3dTiles)
3. 3dTiles: Info panel text color (dark mode)
> fix(website examples): stats widget issue

- modules/arrow/src/arrow-loader.ts
- modules/arrow/src/arrow-writer.ts
- modules/arrow/src/lib/encode-arrow.ts
- modules/bson/src/bson-loader.ts
- modules/bson/src/bson-writer.ts
- modules/gltf/src/glb-loader.ts
- modules/gltf/src/glb-writer.ts
- modules/gltf/src/lib/encoders/encode-glb.ts
- modules/gltf/src/lib/encoders/encode-gltf.ts
- modules/gltf/src/lib/types/glb-types.ts
- modules/parquet/src/lib/arrow/convert-schema-from-parquet.ts
- modules/ply/src/index.ts
- modules/schema/src/lib/table/simple-table/table-accessors.ts
> feat: Adding types to more loaders

- modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts
- modules/tiles/src/tileset/tileset-3d.ts
- Format query parameters correctly when path contains query string
- Extract file extension correctly when query string is present
- Google API special handling: retain session parameter for all subsequent requests
> Fix handling of query parameters in 3D tile url

- docs/developer-guide/creating-loaders-and-writers.md
- docs/modules/3d-tiles/api-reference/tiles-3d-loader.md
- docs/whats-new.mdx
- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-subtree.ts
- modules/3d-tiles/src/tiles-3d-loader.ts
- modules/core/src/lib/api/parse-in-batches.ts
- modules/core/src/lib/api/parse-sync.ts
- modules/core/src/lib/api/parse.ts
- modules/core/src/lib/api/select-loader.ts
- modules/core/src/lib/loader-utils/loader-context.ts
- modules/core/src/lib/utils/resource-utils.ts
- modules/core/src/lib/utils/response-utils.ts
- modules/core/src/lib/utils/url-utils.ts
- modules/core/test/lib/utils/resource-utils.spec.js
- modules/loader-utils/src/types.ts
- modules/tiles/src/tileset/tileset-3d.ts
- modules/tiles/test/tileset/tileset-3d.spec.js
Some tile servers require query parameters to be appended to requests when requesting 3D tiles, a common one being adding an API key. Currently, this is only achievable in deck.gl by using `onTilesetLoad` in a rather hacky way:
```js
new Tile3DLayer({
id: 'tile-3d-layer',
data: "http://www.tileserver.com/tileset.json?key=KEY",
onTilesetLoad: tileset3d => {
tileset3d._queryParams = {key: "KEY"};
}
});
```
This PR enhances Tileset3D so that it passes the query parameters on to tile requests as well as the initial tileset request, thus removing the need for the above hack. 
This is in line with how Cesium works: https://github.com/CesiumGS/3d-tiles/issues/484
> Tiles3DLoader: pass query parameters used on tileset request onto tile requests

- modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
- modules/i3s/test/parse-slpk.spec.js
- modules/tile-converter/src/i3s-server/README.md
- modules/tile-converter/src/i3s-server/app.js
- modules/tile-converter/src/i3s-server/routes/slpk-router.js
- modules/tile-converter/src/i3s-server/utils/create-scene-server.js
Start server:
`I3sLayerPath="../datasets/Rancho_Mesh_mesh_v17_1.slpk" DEBUG=i3s-server:* npx i3s-server`
Run on ArcGIS:
`https://www.arcgis.com/home/webscene/viewer.html?url=https://localhost/SceneServer`
Run on I3S Explorer (the tile is floating because no terrain. Switch on terrain to see the layer on appropriate elevation):
`https://i3s.loaders.gl/viewer?tileset=https://localhost/SceneServer`
> fix router to serve on ArcGIS

- modules/tile-converter/src/deps-installer/deps-installer.ts
- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts
- modules/tile-converter/src/i3s-converter/i3s-converter.ts
- modules/tile-converter/src/lib/utils/file-utils.ts
Related to https://github.com/visgl/loaders.gl/pull/2495
* Use workers from local fs;
Also
* Fix dependencies installer;
* Fix NodeJS deprecation warning.
> fix(tile-converter): node workers error

- modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
- modules/i3s/src/lib/utils/customize-сolors.ts
- modules/i3s/src/lib/utils/customizeColors.ts
- modules/i3s/src/types.ts
- modules/i3s/test/i3s-content-loader.spec.js
- yarn.lock
> feat(i3s): Add an option to multiply colors by attribute

- docs/modules/gis/api-reference/geojson-to-binary.md
- docs/whats-new.mdx
- modules/gis/src/lib/flat-geojson-to-binary-types.ts
- modules/gis/src/lib/flat-geojson-to-binary.ts
- modules/gis/src/lib/geojson-to-binary.ts
- modules/gis/test/geojson-to-binary.spec.js
- modules/gis/test/gis.bench.js
We have found that the `geojsonToBinary` function can be very slow (multiple seconds) when processing large polygons due to the triangulation done via earcut. This PR adds a new optional parameter to disable the triangulation. By defaulting to `true` we maintain back compatibility but enable fast processing when needed (e.g. for a realtime API).
The result is that the output data structure doesn't include the `polygons.triangles` property. deck.gl is able to cope with this and will perform the tesselation at render time, much like it does when rendering GeoJSON.
- Add new parameter to `geojsonToBinary`
- Implementation in `flat-geojson-to-binary.ts`
- Doc & test update
> Add `triangulate` property to `geojsonToBinary`

- modules/i3s/src/lib/parsers/parse-slpk/parse-slpk.ts
- modules/zip/src/hash-file-utility.ts
- modules/zip/src/index.ts
Contains part of https://github.com/visgl/loaders.gl/pull/2578
Moved hash generation to zip module as well
> chore(i3s): Hash generation moved to @loader.gl/zip

- modules/zip/package.json
Fixes:
`npm install @loaders.gl/tile-converter@4.0.0-alpha.21` fails
> fix(zip): @loaders.gl/core dependency

- modules/gltf/src/index.ts
- modules/gltf/src/lib/types/gltf-types.ts
- modules/images/src/image-loader.ts
- modules/images/src/lib/parsers/parse-image.ts
- modules/images/src/lib/parsers/parse-to-image-bitmap.ts
- modules/images/src/lib/parsers/parse-to-image.ts
- modules/images/src/lib/parsers/parse-to-node-image.ts
- modules/images/src/lib/texture-api/load-image.ts
- modules/tile-converter/src/i3s-converter/helpers/batch-ids-extensions.ts
- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts
- modules/wms/src/lib/services/ogc/wms-service.ts
- yarn.lock
Address some issues found when investigating #2615, however root cause not yet understood.
Removing default exports in images may or may not help.
> chore: Clean up module imports, remove default exports in images module

- docs/whats-new.mdx
- modules/arrow/package.json
- modules/arrow/test/arrow-loader.spec.ts
- modules/las/package.json
- modules/parquet/package.json
- yarn.lock
@trxcllnt When I upgrade to v12 or v13, arrow crashes in this test case
https://github.com/visgl/loaders.gl/blob/master/modules/arrow/test/arrow-loader.spec.ts#L55
Some kind of big int issue in that table?
> feat(arrow): upgrade to apache-arrow v13

- docs/roadmap.md
- docs/whats-new.mdx
Additions from ActionEngine team into Loaders.gl roadmap and/or whats-new pages for the upcoming 4.0 release of Loaders.gl
> docs(release-notes): Loaders 4.0 upcoming release notes

- modules/i3s/src/lib/parsers/parse-i3s.ts
- yarn.lock
Getting root node url for tilesets without node pages needs to be corrected according to recent changes in the NormalizeTilesetData
> fix(parse-i3s): getting root node url for normalizeTilesetData without nodepages

- modules/tiles/src/tileset/tileset-3d.ts
- modules/tiles/test/tileset/tileset-3d.spec.ts
We don't need sign '?' at the end of the url if there are no query parameters
> fix: getting tile url with empty query params

- modules/3d-tiles/src/3d-tiles-archive/3d-tiles-archive-archive.ts
- modules/3d-tiles/src/3d-tiles-archive/3d-tiles-archive-parser.ts
- modules/3d-tiles/src/lib/filesystems/tiles-3d-archive-file-system.ts
- modules/3d-tiles/src/types.ts
- modules/i3s/package.json
- modules/i3s/src/i3s-slpk-loader.ts
- modules/i3s/src/index.ts
- modules/i3s/src/lib/parsers/parse-slpk/parse-slpk.ts
- modules/i3s/src/lib/parsers/parse-slpk/slpk-archieve.ts
- modules/i3s/tsconfig.json
- modules/tile-converter/src/i3s-server/controllers/slpk-controller.ts
- modules/tile-converter/test/i3s-server/controllers/slpk-controller.spec.ts
- modules/zip/package.json
- modules/zip/src/filesystems/zip-filesystem.ts
- modules/zip/src/hash-file-utility.ts
- modules/zip/src/index.ts
- modules/zip/src/parse-zip/cd-file-header.ts
- modules/zip/tsconfig.json
- yarn.lock
@dariaterekhovaae 
- Since loaders.gl already has a crypto module I prefer that we use that.
- We should avoid using Node.js `Buffer` class: it pulls in a big polyfill when used in browser and generally I can become confusing to use too many different abstractions for handling binary memory at the same time. Prefer ArrayBuffer and DataView.
- While I was making changes, I noted that your hash/offset data structure could be more efficiently stored as `{[hash: string]; offset}`
> chore(i3s): use loaders.gl MD5 hash, avoid Buffer usage

- modules/tiles/src/tileset/helpers/bounding-volume.ts
- modules/tiles/test/index.ts
- modules/tiles/test/test-utils/compareArrays.ts
- modules/tiles/test/tileset/helpers/bounding-volume.spec.ts
We need it in the tile-converter but I decided to use it widely in tiles.
I think, region is better fit to obb then mbs.
Before (region converted to mbs converted to obb):
After:
> fix(tiles): convert region to obb

- modules/wms/src/services/ogc/wms-service.ts
`getMapURL` uses the `_getWMS130Parameters` to improve compatibility between WMS 1.3.0 and 1.1.0, but `getFeatureInfoUrl` does not.
This means, for instance if SRS is set to `EPSG:3857` it will be handled incorrectly by `getFeatureInfoUrl` as it would use the default CRS of `EPSG:4326`, causing bbox flipping
> fix: WMS 1.3.0 compatibility on GetFeatureInfo

- modules/tiles/src/tileset/helpers/zoom.ts
- modules/tiles/src/tileset/tileset-3d.ts
replace
```
const x = Ellipsoid.WGS84.cartographicToCartesian(y, new Vector3());
```
with
```
const x = new Vector3();
Ellipsoid.WGS84.cartographicToCartesian(y, x)
```
Existing syntax fails in JEST tests environment in "I3S Explorer". It uses es5 transpiled code and `cartographicToCartesian` returns `undefined`. The issue occured from NodeJS 16. NodeJS 14 is ok.
> fix(tiles): cartographicToCartesan syntax

- modules/i3s/src/i3s-loader.ts
- modules/i3s/src/lib/parsers/parse-i3s.ts
- modules/i3s/src/lib/utils/url-utils.ts
- modules/i3s/test/lib/parsers/url-utils.spec.ts
It is a regression fix. I3S datasets don't work with ArgGIS token.
> fix(i3s): handle search params in I3SLoader

- modules/arrow/package.json
- modules/arrow/src/arrow-loader.ts
- modules/arrow/src/arrow-writer.ts
- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/geoarrow/convert-geoarrow-to-geojson.ts
- modules/arrow/src/geoarrow/get-arrow-bounds.ts
- modules/arrow/src/index.ts
- modules/arrow/src/schema/convert-arrow-schema.ts
- modules/arrow/src/tables/convert-arrow-to-table.ts
- modules/arrow/src/types.ts
- modules/arrow/src/workers/arrow-worker.ts
- modules/arrow/test/arrow-loader.spec.ts
- modules/arrow/test/arrow-writer.spec.ts
- modules/arrow/test/geoarrow/convert-geoarrow-to-geojson.spec.ts
- modules/arrow/test/index.ts
- modules/arrow/tsconfig.json
- modules/gis/src/index.ts
- modules/gis/src/lib/geo/geoarrow-metadata.ts
- modules/gis/src/lib/geo/geoparquet-metadata.ts
This is a repackaging for #2738 so that those utilities fit into the right places/sub-modules in loaders.gl
> feat(arrow): GeoArrow utilities

- modules/tile-converter/src/i3s-server/routes/slpk-router.ts
I faced with a problem, that browser receives `{}` for file requests, although data passed to `res.send()` contains the requested file. So there's the fix, it looks like .toString() stopped working correctly for `ArrayBuffer` or some other its implementation
> fix(tile-converter): fixed empty response error

- CONTRIBUTING.md
- README.md
- docs/modules/3d-tiles/README.md
- docs/modules/3d-tiles/api-reference/cesium-ion-loader.md
- docs/modules/3d-tiles/api-reference/tiles-3d-loader.md
- docs/modules/i3s/api-reference/i3s-loader.md
- docs/modules/tiles/api-reference/tileset-3d.md
- modules/3d-tiles/wip/tileset-3d-full.md
- modules/tiles/src/tileset/tile-3d.ts
This is a follow up from https://github.com/visgl/loaders.gl/pull/2679 (had some issues with git rebasing there and the PR got automatically closed somehow..)
This PR updates the documentation to (1) better explain how to use `maximumScreenSpaceError` (2) how to correctly load a 3D Tileset for a given view using Loaders.gl, specifically to support 3D Tilesets that have external tilesets, like the Google Photorealistic 3D Tiles.
@justinmanley after a lot of investigating I believe I have answers to all the questions we had in the original PR:
* You are correct in that `maximumScreenSpaceError` is already being passed correctly, and my fix is not necessary. My confusion came from setting SSE to 16 was still loading tiles down to 8. But I think this is due to the structure of the 3D Tileset …
> Update 3D Tiles Docs

- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/geoarrow/get-arrow-bounds.ts
- modules/arrow/src/index.ts
- modules/arrow/test/geoarrow/get-arrow-bounds.spec.ts
- modules/arrow/test/index.ts
- Fix a small bug that map bound is not computed correctly from GeoArrow samples. 
- Add test cases for `updateBoundsFromGeoArrowSamples()`
> fix(arrow): fix get map bound from geoarrow samples

- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/geoarrow/convert-geoarrow-to-geojson.ts
- modules/arrow/src/lib/arrow-table-batch.ts
- modules/arrow/src/lib/arrow-table.ts
- modules/arrow/src/lib/encode-arrow.ts
- modules/arrow/src/lib/parse-arrow-in-batches.ts
- modules/arrow/src/lib/parse-arrow-sync.ts
- modules/arrow/src/schema/arrow-type-utils.ts
- modules/arrow/src/schema/convert-arrow-schema.ts
- modules/arrow/src/tables/convert-arrow-to-table.ts
- modules/csv/test/csv-loader-arrow.spec.ts
- modules/parquet/src/index.ts
- modules/parquet/src/lib/wasm/encode-parquet-wasm.ts
- modules/parquet/src/lib/wasm/parse-parquet-wasm.ts
- modules/parquet/src/parquet-wasm-loader.ts
- modules/parquet/src/parquet-wasm-writer.ts
- modules/parquet/test/geoparquet-loader.spec.ts
I normally prefer explicit imports, but given how many small symbols apache arrow exports, I think this style (inspired by @kylebarron's https://github.com/geoarrow/deck.gl-layers) works better.
> chore: Adopt namespace style imports for apache-arrow

- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/index.ts
- modules/arrow/test/geoarrow/convert-geoarrow-to-binary-geometry.spec.ts
- modules/arrow/test/geoarrow/convert-geoarrow-to-geojson.spec.ts
- modules/arrow/test/geoarrow/get-arrow-bounds.spec.ts
- modules/arrow/test/index.ts
- add test cases for `getBinaryGeometriesFromArrow()`
- Fix lint
> chore(Arrow): add test cases for geoarrow to binary geometries

- modules/3d-tiles/src/tile-3d-writer.ts
- modules/arrow/src/arrow-writer.ts
- modules/bson/src/bson-writer.ts
- modules/core/src/lib/api/encode-table.ts
- modules/core/src/lib/api/encode.ts
- modules/csv/src/csv-writer.ts
- modules/draco/src/draco-writer.ts
- modules/gltf/src/glb-writer.ts
- modules/images/src/image-writer.ts
- modules/json/src/geojson-writer.ts
- modules/json/src/json-writer.ts
- modules/loader-utils/src/index.ts
- modules/loader-utils/src/writer-types.ts
- modules/parquet/src/parquet-wasm-writer.ts
- modules/parquet/src/parquet-writer.ts
- modules/textures/src/compressed-texture-writer.ts
- modules/textures/src/ktx2-basis-writer.ts
- modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts
- modules/wkt/src/wkb-writer.ts
- modules/wkt/src/wkt-crs-writer.ts
Since we are starting to create worker-only writers, adopt same type split as loaders: `Worker` / `WorkerWithEncoder`.
> chore(loader-utils): split Worker/WorkerWithEncoder types

- modules/loader-utils/src/loader-types.ts
- modules/parquet/src/index.ts
- modules/parquet/src/lib/parsers/parse-parquet-to-columns.ts
- modules/parquet/src/lib/parsers/parse-parquet-to-rows.ts
- modules/parquet/src/parquet-loader.ts
- test/common/conformance.ts
Standardize random access parsing on `ReadableFile` interface.
> chore: parseFile accepts `ReadableFile`

- examples/website/geospatial/app.tsx
- examples/website/geospatial/package.json
- examples/website/geospatial/vite.config.ts
It still fails because of recently enabled `ParquetWasmLoader`. But now I can comment it to debug the JS loader.
> fix(examples): run 'geospatial' locally

- modules/i3s/src/arcgis-webscene-loader.ts
- modules/i3s/src/i3s-building-scene-layer-loader.ts
- modules/i3s/src/i3s-content-loader.ts
- modules/textures/src/lib/utils/version.ts
- modules/tile-converter/src/deps-installer/deps-installer.ts
- modules/worker-utils/src/lib/env-utils/version.ts
We need to switch from `beta` to `latest` on production releases.
> fix: Use "latest" version tag when loading from unpkg

- modules/worker-utils/src/lib/node/require-utils.node.ts
- modules/worker-utils/src/lib/node/worker_threads-browser.ts
- modules/worker-utils/src/lib/node/worker_threads.ts
- modules/worker-utils/src/lib/worker-api/get-worker-url.ts
- modules/worker-utils/src/lib/worker-farm/worker-body.ts
- Reports of `processOnWorker()` with compression worker failing in Node tests in kepler tools. This is a regression but the confusing thing is that this is a node only test. Looks like this particular browser worker used to work in node in 3.4?
- Regardless, the imported loaders code in kepler is very confusing and hard to debug, with dummy worker object injected instead of worker_threads etc. 
- This is a first attempt to simplify the worker-utils code, step by step.
- I am also just a little bit worried that now that we test node workers from source, and cust the dist tests, we don't get any tests on node workers that have been built.
> chore(worker-utils): worker simplification

- modules/wms/src/services/ogc/wms-service.ts
- modules/wms/test/services/wms-service.spec.ts
The `WMSLayer` is broken in v9 deck: https://felixpalmer.github.io/deck.gl/examples/wms-layer due to the `ImageSource.getImage` function expecting parameters of the type `GetImageParameters`, while the `WMSService.getImage` function expects `WMSGetMapParameters`. These differ only in the specification of the bounds, with the former using `boundingBox` and the latter `bbox`.
There are different ways this could be resolved but I'm assuming that the intended design is to have a unified `getImage` API and thus here the conversion is being done in `WMSService.getImage`
> Convert GetImageParameters to WMSGetMapParameters

- docs/whats-new.mdx
- modules/flatgeobuf/src/flatgeobuf-loader.ts
- modules/flatgeobuf/src/index.ts
- modules/flatgeobuf/src/lib/get-schema-from-fgb-header.ts
- modules/flatgeobuf/src/lib/parse-flatgeobuf.ts
- modules/flatgeobuf/src/workers/flatgeobuf-worker.ts
- modules/flatgeobuf/test/flatgeobuf-loader.spec.ts
- Extract Schema (metadata and fields) from the FGB HeaderMeta object.
- The geospatial examples on the loaders.gl website will have a schema viewer - gradually making sure that all loaders generate a schema.
> feat(flatgeobuf): Extract arrow compatible schema

- modules/gltf/package.json
- modules/gltf/src/lib/extensions/utils/3d-tiles-utils.ts
Without this, importing `@loaders.gl/gltf` fails (e.g. in luma.gl) due to this import: https://github.com/visgl/loaders.gl/blob/master/modules/gltf/src/lib/extensions/utils/3d-tiles-utils.ts#L17
> GLTF: inline emod function to remove loaders.gl/math dependency

- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/triangulate-on-worker.ts
- modules/arrow/src/workers/triangulation-worker.ts
- modules/arrow/test/geoarrow/convert-geoarrow-to-binary-geometry.spec.ts
In practice, there are many geoarrow files converted from GeoJson files using `ogr2ogr` containing invalid geometries. For example, polygon ring not closed; self-intersect polygon; multipolygon within `geoarrow.polygon` type arrow file etc. This will cause `earcut()` function to hang or return an empty triangle index. 
Ideally, users should make sure the geoarrow file is correct, and use `ogr2ogr` to fix these invalid geometries e.g. with `-makeValie` or using Sqlite `SELECT ST_MAKEVALID`. However, to prevent hanging or crashing in loader.gl, we catch the possible error in earcut and let deckgl to remove the positions of these invalid polygons for filling polygon props. The option `triangulate: boolean` is also added to allow users to skip polygon tessellation on bulk geometries at …
> fix(GeoArrow): handle tessellation error & improve mean centers

- modules/tile-converter/src/i3s-server/routes/slpk-router.ts
Some tools request resource using the path with a slash in the end (ex. http://localhost:8081/SceneServer/layers/0/nodepages/0/) and i3s server currently cannot retrieve anything on this path. Current PR contains a small fix for this issue.
> fix(tile-converter): trailing slash Removing from path in i3s-server

- modules/arrow/src/geoarrow/convert-geoarrow-to-binary-geometry.ts
- modules/arrow/src/index.ts
- modules/arrow/src/parsers/parse-arrow-in-batches.ts
- modules/arrow/src/triangulate-on-worker.ts
- modules/arrow/src/workers/hard-clone.ts
- modules/arrow/src/workers/triangulation-worker.ts
- modules/arrow/test/geoarrow/convert-geoarrow-to-binary-geometry.spec.ts
- modules/arrow/test/triangulate-on-worker.spec.ts
Starts wiring up earcut into the new triangulation worker.
This requires making some of the existing functions async.
@lixun910 My sense is that this is the wrong approach. The workload is too small, and it introduces to much async into a sync util library. It would preferable to run the worker on one batch of geometries rather than on individual polygons.
> feat(arrow): Triangulate on worker

- modules/crypto/src/lib/crc32-hash.ts
- modules/crypto/src/lib/crc32c-hash.ts
- modules/crypto/src/lib/crypto-hash.ts
- modules/crypto/test/crypto.spec.ts
- modules/crypto/test/lib/crypto-hash.spec.ts
Reusing Hash class instances would fail to clear the digest and yield incorrect results.
> fix(crypto):  Reuse of Hash instance failures

- babel.config.cjs
- package.json
- ocular had moved all babel configs into a subfield, no typings meant no warnings.
- this handles the subset of compilation that still goes through babel
- worker builds e.g. rely on version injection through esbuild parameters.
- scripts esbuild from babel transpiled source so they are OK for now.
> fix: version injection

- modules/mvt/src/mvt-source.ts
- modules/mvt/test/mvt-source.spec.ts
- Support deck.gl style template URL
- Support custom metadata URL, as well as no (null) metadata URL.
- Specify custom extension in props.
@igorDykhta Should cover most of the limitations you found.
> feat(mvt): Add templateUrl etc to MVTSource.

- modules/arrow/src/arrow-loader.ts
- modules/arrow/src/parsers/parse-arrow-in-batches.ts
Description: add an optional delay between batches in parseArrowInBatches, so the incremental loading and rendering based on batches can be smooth e.g. in https://github.com/keplergl/kepler.gl/pull/2474
> feat(GeoArrow): add optional delay between batches in parseArrowInBatches

- modules/geotiff/src/index.ts
- modules/geotiff/src/loaders.ts
This is an experimental version of a GeoTIFF loader. Its goal is to add native RGB GeoTIFF rendering support for deck.gl to render aerial images, orthophotos and overlays into a deck instance.
**Discussion on:** #1280 
**TODO:**
**Testing instructions:**
TBD
> feat(geotiff): RGB GeoTIFFLoader

- modules/loader-utils/src/lib/option-utils/merge-loader-options.ts
Don't want to risk breaking the functionality or spend too much time on this right now, so just adding a trivial guard to prevent jest overrides from triggering infinite recursion.
@nrabinowitz
> fix(loader-utils): Guard against infinite recursion

- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-subtree.ts
- modules/3d-tiles/src/types.ts
- modules/3d-tiles/test/index.ts
- modules/3d-tiles/test/lib/parsers/helpers/parse-3d-tile-subtree.spec.ts
Currently, loadExplicitBitstream works correctly for implicit tilesets containing a single buffer. However, because the implementation ignores both the buffer length and its offset, for tilesets with multiple buffers embedded in a binary subtree (rather than as separate .bin files), loadExplicitBitstream returns the entire binary buffer every time loadExplicitBitstream is called.
In other words: if the buffer B = B0 + B1, loadExplicitBitstream(B, 0) and loadExplicitBitstream(B, 1) currently both return B0 + B1. Instead, loadExplicitBitstream(B, 0) should return only B0 and loadExplicitBitstream(B, 1) should return only B1.
This PR fixes the issue by slicing the main buffer according to the offset and byte-length of the target buffer. This PR also adds unit tests for loadExplicitBitstream …
> Fix loadExplicitBitstream by accounting for buffer offset and byte length when extracting from a combined binary blob

- modules/tiles/src/tileset/tileset-traverser.ts
Hi!
After a year of absence I'm back doing some viz work. 
I'm now updating [nytimes/three-loader-3dtiles](https://github.com/nytimes/three-loader-3dtiles/tree/feature/loadersgl-4) to loaders.gl-4 and support for Google's 3D Tiles (*feature/loadersgl-4* branch).
I noticed one issue where low-res tiles flicker above the high-res tiles during traversals, possible related to [this issue](https://github.com/visgl/loaders.gl/issues/2570). It seemed to have come from some glitch in the "empty" traversal mechanism. I updated the algorithm to match the [latest CesiumJS one](https://github.com/CesiumGS/cesium/blob/66dba4b2e6bef81e5662499921c2eacd35a90dee/packages/engine/Source/Scene/Cesium3DTilesetBaseTraversal.js#L251C25-L251C26) and at least on my tests it seems to fix the issue and does not …
> Update the empty traversal algorithm to match CesiumJS, possible fix for low-res flickering

- modules/loader-utils/src/index.ts
- modules/loader-utils/src/lib/binary-utils/array-buffer-utils.ts
- modules/zip/src/hash-file-utility.ts
I've got the `RangeError: Maximum call stack size exceeded` error for huge slpk creation. So I investigated and found out that we have a bottleneck on the current implementation of concatenateArrayBuffers function in amount of arguments. I haven't found any info about nodejs, but I've found the following article: https://stackoverflow.com/a/22747272 and it looks like node has the same limitation of max 65 535 arguments per function and throw the same error since it use the same V8 engine to interpret JS code. But number of files even in 5gb datasets can reach 800 000, so node can't handle it and throws an error.
To solve this problem I've created another function receiving `ArrayBuffer[]` instead of multiple arguments
> fix(loader-utils): concatenateArrayBuffers bottleneck fix

- examples/benchmarks/package.json
- examples/experimental/3d-tiles-with-cesium/package.json
- examples/experimental/basis/package.json
- examples/experimental/gltf-with-deck.gl/package.json
- examples/experimental/terrain/package.json
- examples/gallery/package.json
- examples/get-started/bundle-with-nextjs/package.json
- examples/get-started/bundle-with-rollup/package.json
- examples/website/3d-tiles/package.json
- examples/website/geospatial/package.json
- examples/website/gltf/package.json
- examples/website/i3s-arcgis/package.json
- examples/website/i3s-building-scene-layer/package.json
- examples/website/i3s/package.json
- examples/website/pointcloud/package.json
- examples/website/textures/package.json
- examples/website/tiles/package.json
- examples/website/wms/package.json
Preparing for Vite 6.0
- The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
@belom88 We need to do some test of the `get-started` examples. They use old bundler versions and I expect them to need some TLC. Is that testing something AE could help with?
> chore: Update examples to type: module

- modules/core/src/lib/loader-utils/option-utils.ts
- modules/core/test/lib/fetch/fetch-file.node.spec.ts
In the scripting environment, library exports (`loaders.*`) cannot be reassigned. `loaders._state = loaders._state` throws the following error:
```
TypeError: Cannot set property _state of #<Object> which has only a getter
```
> Avoid reassigning loaders._state

- docs/whats-new.mdx
I don't know if this belong in /core or /csv, as I've only tried the v4 parse() with the CSVLoader, but I found this to be a breaking change when updating from v3 -> v4 that wasn't mentioned in the release notes which i think belongs there somewhere.
> migration info loaders v4

- modules/parquet/src/parquetjs/parser/parquet-reader.ts
I was trying to fix some compression errors and found out that we're cutting off the data to decompress incorrect. Data in my case was around 6 million byte long but it was cut off at 1 million and it caused error. 
So I propose to set max dictionary length there to 2 Gb which is max possible ArrayBuffer length in JS
> fix (parquet): Increased max dictionary size to the max size of ArrayBuffer

- modules/wkt/src/lib/parse-wkb.ts
There are several geoparquet dataset in the examples/website/geospatial where the max polygon indices values are around 68,000, although max unsigned 16-bit value is 65,536. So I increased amount of memory to 32 bits there
> fix(wkt): Increased amount of memory for polygon indices

- examples/website/geospatial/examples.ts
- modules/wkt/src/lib/parse-wkb.ts
* `primitivePolygon` might be a Uint16Array and `.map((x: number) => x + primitivePolygonIndices[primitivePolygonIndices.length - 1])` might cut sum operation result;
* need to upload `countries.json` to @deck.gl-data. Current link doesn't work
> fix(wkt): multipolygons UInt16 overflow

- modules/las/src/lib/laslaz-decoder.ts
Manually allocated memory should be freed by ourself. Otherwise we may encounter OOM error.
> Fix laslaz-decoder.ts: free memory after laz file parsed.

- examples/website/geospatial/app.tsx
- examples/website/geospatial/examples.ts
- modules/compression/src/lib/zstd-compression.ts
- modules/parquet/src/lib/parsers/parse-parquet-to-columns.ts
- modules/parquet/src/lib/parsers/parse-parquet.ts
- modules/parquet/src/parquetjs/compression.ts
- website/docusaurus.config.js
- website/package.json
- website/webpack-plugin.js
- website/yarn.lock
Custom zstd decompress method to support big buffers. In my case it failed with about 6.8MB input buffer size. 
* use `zstd.Streaming` instead of `zstd.Simple`
* split input buffer on chunks 1MB.
> fix(parquet): zstd decompression

- modules/csv/src/csv-loader.ts
`Table` is overly broad; `parseCSV` returns `Promise<ObjectRowTable | ArrayRowTable>`.
> fix(csv): CSVLoader return type

- modules/draco/src/lib/draco-parser.ts
For https://github.com/visgl/deck.gl/issues/8746
Holding off https://github.com/visgl/loaders.gl/pull/2949 until we have test data, and instead we'll just ignore unknown attributes for now.
> fix(draco): Ignore unknown attribute types

- examples/website/wms/package.json
- modules/wms/src/services/ogc/wms-service.ts
Another round of seemingly arbitrary parameter name changes in the WMS 1.3 standard.
This can be tested in the loaders.gl website which has been redeployed with this fix: https://loaders.gl/examples/wms
> fix(wms): Use correct featureInfo parameters for WMS 1.3

- modules/core/src/lib/api/select-loader.ts
- modules/core/src/lib/utils/mime-type-utils.ts
- modules/core/test/lib/utils/mime-type-utils.spec.ts
> fix(core): Case insensitive MIME type comparison

- modules/loader-utils/package.json
[/modules/loader-utils/src/lib/log-utils/log.ts](https://github.com/visgl/loaders.gl/blob/d9db37097245ce8ea3204c2f4f4d4ed32b5f3c10/modules/loader-utils/src/lib/log-utils/log.ts#L5) depends on `@probe.gl/log`, so this package should be added to package dependencies.
Currently this results in an error when installing `@loaders.gl/loader-utils@4.2.1` with Yarn:
```
Cannot find module '@probe.gl/log' from '[REDACTED]/.yarn/__virtual__/@loaders.gl-loader-utils-virtual-7093831d78/0/cache/@loaders.gl-loader-utils-npm-4.2.1-a254ec9477-03fd9b18c2.zip/node_modules/@loaders.gl/loader-utils/dist'
```
Note: workaround until this PR is merged:
```
packageExtensions:
"@loaders.gl/loader-utils@*":
dependencies:
"@probe.gl/log": "*"
```
> fix(loader-utils): add missing dependency on @probe.gl/log

- modules/csv/package.json
Note: this PR is similar to #3008
[/modules/csv/src/lib/encoders/encode-csv.ts](https://github.com/visgl/loaders.gl/blob/d9db37097245ce8ea3204c2f4f4d4ed32b5f3c10/modules/csv/src/lib/encoders/encode-csv.ts#L7) depends on `d3-dsv`, so this package should be added to package dependencies.  Previously this import was in `devDependencies` (looks like a test also imports it), but since this is code that runs in production is should be moved to `dependencies`
Currently this results in an error when installing `@loaders.gl/csv@4.2.1` with Yarn:
```
Cannot find module 'd3-dsv' ...
```
Note: workaround until this PR is merged:
```
packageExtensions:
"@loaders.gl/csv@*":
dependencies:
"d3-dsv": "*"
```
> fix(csv): move d3-dsv from devDependencies to dependencies

- modules/textures/package.json
- modules/textures/src/lib/parsers/parse-basis.ts
- modules/textures/test/basis-loader.spec.ts
- yarn.lock
Someone on the [Web Game Dev](https://www.webgamedev.com/) Discord server reported that loaders.gl doesn't return any mipmaps for KTX2 textures. Appears to be a quick fix, and the returned data looks valid. I've updated `ktx-parse` to a newer version, while I'm here.
> feat(textures): Support loading mipmaps in KTX2 textures

- modules/core/src/lib/utils/response-utils.ts
- modules/core/test/lib/utils/response-utils.spec.ts
For #3025
Added a test case that reproduced the issue together with a fix: 
- add `await` on `response.text()`, causing the error to happen outside of the catch.
- add a check for `response.bodyUsed`:  https://developer.mozilla.org/en-US/docs/Web/API/Response/bodyUsed.
> fix(core): checkResponse crash when Request body is already used

- modules/tiles/src/tileset/tileset-traverser.ts
Hi!
Yet another fix for tile traversal. Bug was noticed while traveling in Google's 3D Tiles.
The `canTraverse` function should not check for visibility in the traversal process, as [shown in the CesiumJS code](https://github.com/CesiumGS/cesium/blob/cbd13cee0959d2de6e01f355dd1cd73342467102/packages/engine/Source/Scene/Cesium3DTilesetTraversal.js#L58-L68). Probably there are cases where a parent in the traversal process is not visible, but the child tile is.
Here is how it looked before the fix:
And here is how it looks after:
Possibly, this functionality existed previously via the `ignoreVisibility` argument. Now I removed both optional arguments from `canTraverse` since they are not used.
If approved, would it be possible to merge this PR to the current stable branch?
Thank you,
/Avner
> Tiles traverser: do not check for visibility in `canTraverse`.

- docs/developer-guide/using-worker-loaders.md
- modules/mvt/package.json
Ref #3034 
This MR exports the bundled worker package via `@loaders.gl/mvt/mvt-worker.js`.
I've also added an example with `vite`, and fixed a bunch of typos.
> fix(mvt): Add mvt-worker.js bundle to exports path

- yarn.lock
Currently test workflow fails because puppeteer installer cannot download chrome binaries because of obsolete link, so there I'm trying to upgrade puppeteer version to an actual one
Upgraded via `yarn up puppeteer -R`
> fix: Puppeteer version upgraded

- modules/tile-converter/src/i3s-converter/i3s-converter.ts
Addition to the previous fix, we need this flag because calculation for one-file dataset isn't a default behaviour now
> fix(tile-converter): Added flag to size calculation

- modules/tile-converter/src/deps-installer/deps-installer.ts
- modules/worker-utils/src/lib/process-utils/child-process-proxy.ts
Fix according to new NodeJS security limitations: https://stackoverflow.com/questions/78420489/error-when-running-npm-script-with-yarn-err-spawn-einval
> fix(tile-converter): Fix according to new NodeJS security limitations

- modules/3d-tiles/src/lib/parsers/helpers/parse-3d-implicit-tiles.ts
Fixes https://github.com/visgl/loaders.gl/issues/3085.
It's possible to fix that issue with smaller changes, but I believe I found and fixed some more bugs by rewriting it for clarity.
Adds comments.
> fix(3d-tiles): Rewrite of parseImplicitTiles for readability

- modules/parquet/src/parquet-loader.ts
parquet-loader-worker.js is not built because of CommonJS relationships in code. Make the loader to work without worker by default
> fix(parquet): ParquetLoader worker: false

- modules/3d-tiles/src/lib/ion/ion.ts
It appears Cesium Ion has changed the return value of ${CESIUM_ION_URL}/${assetId}, when getting metadata from CesiumIonLoader.preload.  Now this value has the url inside options.url instead of the top level. 
This also puts the correct bearer token inside the metadata headers, coming from the input arg instead of what is returned by the query to the cesium ion api.
> getIonAssetMetadata struct changed (options.url)

- modules/tile-converter/src/converter-cli.ts
Currently tile-converter will just stop if it found `--slpk` option so we need to ignore it in order to keep backward compatibility. We're  also going to make 4.3.1 version with this fix
> fix(tile-converter): Returning --slpk for backward compatibility

- docs/arrowjs/api-reference/builder.md
- docs/arrowjs/developer-guide/builders.md
- modules/bson/src/bson-format.ts
- modules/bson/src/bson-loader.ts
- modules/bson/src/bson-writer.ts
- modules/draco/src/draco-writer.ts
- modules/gis/src/index.ts
- modules/images/src/image-writer.ts
- modules/loader-utils/src/format-types.ts
- modules/loader-utils/src/index.ts
- modules/loader-utils/src/loader-types.ts
- modules/loader-utils/src/source-types.ts
- modules/loader-utils/src/writer-types.ts
- modules/schema/src/categories/category-table.ts
- modules/schema/src/types/batch.ts
- modules/textures/src/compressed-texture-writer.ts
- modules/textures/src/ktx2-basis-writer.ts
- modules/wkt/src/twkb-writer.ts
- modules/wkt/src/wkb-writer.ts
- modules/wkt/src/wkt-writer.ts
- Enable sharing of format metadata between growing set of loaders and writers.
> feat(loader-utils): Add `Format` type

- modules/gis/src/lib/table-converters/make-arrow-batch-iterator.ts
- modules/json/test/lib/clarinet/clarinet.spec.js
- modules/schema-utils/src/index.ts
- modules/schema-utils/src/lib/table/batch-builder/arrow-table-builder.ts
- modules/shapefile/src/dbf-arrow-loader.ts
- modules/shapefile/src/dbf-format.ts
- modules/shapefile/src/index.ts
- modules/shapefile/src/lib/parsers/parse-dbf-to-arrow.ts
- modules/shapefile/test/dbf-arrow-loader.spec.ts
- modules/shapefile/test/index.ts
- Simple `ArrowDBFLoader` version of the `DBFLoader`
- First step towards making a GeoArrow `ShapefileLoader`
- Keeps the old `DBFLoader` for now, but this could be rewritten as a minimal "adapter" on top of the `ArrowDBFLoader`
-
> feat(shapefile): DBFArrowLoader

- modules/compression/package.json
- yarn.lock
The types for `brotli` include a depenency on `@types/node`. For a web-based user of deck.gl, loaders.gl, and which does not use the `brotli` library, this adds the node type globals into the type system. That creates some unfortunate inconsistencies with Web/DOM global types.
Since `brotli` is optional, the types can also be optional so that both can be excluded from environments that don't use them.
> Make @types/brotli also optional
