visgl/loaders.gl

test/modules/core/common/loader-utils/get-image-size.spec.js, test/webpack.config.js
=> Fix image tests under browser

docs/api-reference/gltf-loaders/glb-builder.md, docs/api-reference/gltf-loaders/glb-parser.md, docs/api-reference/gltf-loaders/gltf-builder.md, docs/api-reference/gltf-loaders/gltf-parser.md, docs/whats-new.md, modules/gltf/scripts/glbdump.js, modules/gltf/src/glb/glb-builder.js, modules/gltf/src/glb/glb-parser.js, modules/gltf/src/gltf/gltf-builder.js, modules/gltf/src/gltf/gltf-parser.js, test/modules/gltf/glb/glb-custom-payload.spec.js, test/modules/gltf/glb/glb-encode-parse.spec.js, test/modules/gltf/glb/glb-encoder-decoder.spec.js, test/modules/gltf/glb/glb-parser.spec.js, test/modules/gltf/gltf/gltf-loader.spec.js, test/modules/gltf/gltf/gltf-roundtrip.spec.js
- Get rid of broken `config` handling
- Keep refinining GLB/glTF API split and docs.
=> GLTF cleanup

docs/api-reference/gltf-loaders/gltf-extensions.md, docs/developer-guide/category-gltf.md, website/src/mdRoutes.js
=> Document Uber glTF extension strings.

modules/core/src/index.js, modules/core/src/mesh-utils/gltf-attribute-utils.js, modules/draco/src/draco-decoder.js, modules/las/src/parse-las.js, modules/pcd/src/parse-pcd.js, modules/ply/src/parse-ply.js, test/modules/conformance.js, test/modules/draco/draco-compression-ratio.spec.js, test/modules/draco/draco-encoder.spec.js, test/modules/draco/draco-loader.spec.js, test/modules/gltf/gltf/gltf-draco.spec.js, test/modules/las/las-loader.spec.js, test/modules/obj/obj-loader.spec.js, test/modules/pcd/pcd-loader.spec.js, test/modules/ply/ply-loader.spec.js, test/render/test-cases/point-cloud.js, test/render/test-utils/get-model.js, test/render/test-utils/normalize-attributes.js
Add conformance test.
- draco (header, draw mode, attributes)
- las (header, attributes)
- ply (header, draw mode)
=> Make sure all loaders output consistent format

modules/kml/src/index.js, modules/kml/src/kml-as-geojson-loader.js, modules/kml/src/kml-to-geojson.js, modules/kml/test/index.js, modules/kml/test/kml-as-geojson-loader.spec.js, test/start.js
Just for fun as I was fixing logging in this example...
=> Add KMLasGeoJsonLoader

aliases.js, docs/api-reference/misc-loaders/zip-loader.md, docs/api-reference/misc-loaders/zip-writer.md, modules/core/src/index.js, modules/zip/README.md, modules/zip/package.json, modules/zip/src/index.js, modules/zip/src/zip-loader.js, modules/zip/src/zip-writer.js, modules/zip/test/index.js, modules/zip/test/zip-writer-loader.spec.js, test/modules.js, yarn.lock
=> New module @loaders.gl/zip

modules/gltf/package.json
=> Fix gltf/glbdump publish

docs-arrow/api-reference/record-batch.md, docs-arrow/api-reference/struct-vector.md, modules/arrow/src/index.js, modules/arrow/src/lib/arrow-table-batch.js, modules/arrow/test/arrow-loader.spec.js, modules/core/test/iterator-utils/async-queue.spec.js, modules/csv/test/csv-loader-arrow.spec.js, modules/csv/test/csv-loader.spec.js, modules/csv/test/index.js
@trxcllnt Pretty sure this is not taking advantage of the sophistication of the Arrow API, but at least it is a start...
=> Add `ArrowTableBatch` class. Tests for streaming CSV->Arrow `RecordBatch` async iterator

docs/api-reference/core/fetch-file.md, docs/api-reference/core/load-file.md, docs/api-reference/core/parse-file.md, docs/api-reference/core/register-loaders.md, modules/arrow/test/arrow-loader.spec.js, modules/core/src/fetch-file/fetch-file-browser.js, modules/core/src/fetch-file/fetch-file-node.js, modules/core/src/fetch-file/fetch-file.js, modules/core/src/image-utils/image-loaders.js, modules/core/src/index.js, modules/core/test/fetch-file/fetch-file.spec.js, modules/core/test/image-utils/get-image-size.spec.js, modules/csv/test/csv-loader.bench.js, modules/csv/test/csv-writer.spec.js, modules/draco/test/draco-encoder.spec.js, modules/draco/test/draco.bench.js, modules/gltf/test/gltf/gltf-draco.spec.js, modules/images/test/load-image.spec.js, modules/ply/test/ply-loader.bench.js, modules/ply/test/ply-loader.spec.js, test/render/test-cases/mesh.js, test/render/test-cases/point-cloud.js, webpack.config.js
Supports the use of fetch response objects across the API.
=> Use fetchFile instead of readFile

.eslintrc, modules/arrow/test/arrow-loader.spec.js, modules/core/src/fetch-and-write/node/fetch-file-node.js, modules/draco/src/gltf-attribute-utils.js, modules/gltf/src/packed-json/pack-binary-json.js, modules/kml/src/kml-parser.js, modules/ply/src/parser/parse-ply-stream.js, modules/ply/src/parser/parse-ply.js, package.json, website/gatsby-config.js, website/ocular-config.js, yarn.lock
The full lint script in older versions of ocular-dev-tools was not working
=> Upgrade ocular-dev-tools and fix lint

docs/api-reference/specifications/loader-object-format.md, modules/arrow/src/arrow-loader.js, modules/arrow/src/arrow-worker-loader.js, modules/core/src/lib/loader-utils/auto-detect-loader.js, modules/core/src/lib/loader-utils/normalize-loader.js, modules/core/src/lib/register-loaders.js, modules/core/test/lib/load-file.spec.js, modules/core/test/lib/load.spec.js, modules/csv/src/csv-loader.js, modules/csv/test/csv-loader.bench.js, modules/draco/src/draco-loader.js, modules/draco/src/draco-worker-loader.js, modules/draco/src/draco-writer.js, modules/experimental/src/json-loader/json-loader.js, modules/experimental/src/xml-loader/xml-loader.js, modules/gltf/src/gltf/gltf-writer.js, modules/images/src/image-writer.js, modules/kml/src/kml-as-geojson-loader.js, modules/kml/src/kml-loader.js, modules/obj/src/obj-loader.js, modules/obj/src/obj-worker-loader.js, modules/pcd/src/pcd-loader.js, modules/pcd/src/pcd-worker-loader.js, modules/ply/src/ply-loader.js, modules/ply/src/ply-stream-loader.js, modules/ply/src/ply-worker-loader.js, modules/zip/src/zip-loader.js, modules/zip/src/zip-writer.js
E.g. Use same loader object for `gltf`/`glb` etc.
=> Support for multiple extensions

scripts/worker-webpack-config.js
Removes ~70K from each worker bundle
=> Enable tree shaking in workers

package.json, webpack.config.js
We now load from webpack-dev-server using the alias system.
=> Remove arraybuffer-loader

arrow-docs/api-reference/chunked.md, arrow-docs/api-reference/record-batch-writer.md, arrow-docs/api-reference/row.md, arrow-docs/api-reference/vector.md, arrow-docs/api-reference/vectors.md
@trxcllnt Rebased #148 to resolve conflicts
=> Fill in some arrow docs

examples/3d-tiles/app.js, website/docs/README.md, website/docs/contributing.md, website/docs/table-of-contents.json, website/ocular/ocular-config.js
@loshjawrence @lilleyse Based on the two hour setup exercise today, added a new page `docs/contributing.md` giving some pointers to how to set up the development environment.
=> Add contributing/environment setup docs

arrowjs/docs/developer-guide/big-ints.md
@trxcllnt Added your notes to the big int doc.
=> ArrowJS docs: Add notes about big int

.nycrc, modules/polyfills/test/fetch-node/fetch.node.spec.js
Excluding bundles and generated external files (laz-perf, text-encoding) yields 20% coverage increase.
=> Improve coverage +20%

modules/gltf/src/lib/deprecated/gltf-post-processor-old.js, modules/gltf/src/lib/post-process-gltf.js
=> Add default sampler

dev-docs/RFCs/README.md, dev-docs/RFCs/v2.0/fetch-option-rfc.md, dev-docs/RFCs/v2.0/json-support-rfc.md, dev-docs/RFCs/v2.0/loader-auto-detection-rfc.md, dev-docs/RFCs/v2.0/loader-auto-registration-rfc.md, dev-docs/RFCs/v2.0/loader-lookup-by-name-rfc.md, dev-docs/RFCs/vNext/file-system-rfc.md
Largely based the deck.gl [data loading RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v7.x/data-loading-rfc.md)  and discussions in https://github.com/uber/deck.gl/pull/3276
=> RFCs: Proposals for v2.0

arrowjs/docs/paul-drafts/introduction.md, arrowjs/website/package.json
Opening this draft PR so we can track progress. I sat down today to start writing the introduction to the Arrow library I wish I'd had at the beginning. My writing style lends itself to starting from a fresh directory and filling things in as I go along, but I plan to incorporate with the rest of the docs once I advance to the editing process.
=> arrowjs docs: Skeleton of arrow docs from first-principles

examples/3d-tiles/package.json, examples/3d-tiles/tile-3d-layer.js
@loshjawrence Just as sanity check, do you know if the instanced 3d tiles all use the same embedded box geometry?
=> 3d-tiles: Embedded GLBs now display in ScenegraphLayer

examples/3d-tiles/app.js, examples/3d-tiles/tile-3d-layer.js, examples/webpack.config.local.js, website/src/components/site-query.jsx
=>  Support ion dataset

modules/gltf/src/lib/gltf-scenegraph.js
=> Fix for GLTFScenegraph.addBufferView

examples/3d-tiles/app.js, examples/3d-tiles/components/stats-widgets.js, examples/3d-tiles/package.json
Website left issues:
- `ionAccessToken` can not be passed from webpack config
- stats not update correctly
=> Fix widget styling

modules/math/package.json, modules/math/src/geometry/compression/attribute-compression.js, modules/math/src/geometry/index.js, modules/math/test/geometry/compression/attribute-compression.spec.js, modules/math/test/geometry/index.js, test/modules.js, test/utils/expect-assertions.js, test/utils/tape-assertions.js, yarn.lock
Raw port of oct-encoding/decoding for 3d-tiles. 
Will be reused in gltf.
=> 3d-tiles: attribute compression Phase 1

examples/3d-tiles/tile-3d-layer.js, modules/3d-tiles/src/tileset/tile-3d-header.js
Haven't tested on anything but it should just be this.
=> Adding call for installing the external tileset

modules/3d-tiles/src/tileset/tileset-3d.js
@loshjawrence Trying to clean up tileset3d, organizing methods in public/private order.
=>  3d-tiles: Reorder tileset3d methods

examples/3d-tiles/app.js, modules/3d-tiles/src/tileset/tile-3d-header.js, modules/3d-tiles/src/tileset/tileset-3d.js
To help debug cache and tile unloading
@loshjawrence
=> Track Memory Use

modules/core/src/utils/globals.js
=> fix bug with read property match of undefined (#340)

docs/README.md, docs/table-of-contents.json
- Make it a little easier to read. 
- Try to emphasize node support more (@tsherif)
=> docs: front page doc update

modules/core/src/index.js, modules/core/src/lib/parse-with-loader.js, modules/core/src/lib/parse.js, modules/core/src/lib/path/path.js, modules/gltf/src/lib/deprecated/gltf-parser.js
- Improve URL extraction enabling more robust auto detection
=> core: Fixes to `parse`

docs/api-reference/math/gl-type.md, examples/3d-tiles/app.js, examples/3d-tiles/examples.js, examples/3d-tiles/tile-3d-layer/tile-3d-layer.js, examples/webpack.config.local.js, modules/3d-tiles/src/tileset/tile-3d-header.js
With the webpack changes, it will be possible to run `yarn start-local --env.luma` to link and test against local luma.gl.
=> 3d-tiles: small fixes

modules/core/src/lib/parse-with-loader.js, modules/core/src/lib/parse-with-worker.js, modules/core/src/worker-utils/worker-farm.js, modules/core/src/worker-utils/worker-pool.js, modules/core/src/worker-utils/worker-thread.js, modules/core/src/worker-utils/worker-utils.js, modules/core/test/worker-utils/json-loader.worker.js, modules/core/test/worker-utils/jsonl-loader.worker.js, modules/core/test/worker-utils/test-worker.js, modules/core/test/worker-utils/worker-farm.spec.js, modules/loader-utils/src/worker-utils/create-worker.js, webpack.config.js
- Support asynchronous `parse` in worker loaders
- Support using another loader (on main/another worker thread) inside a worker
=> Worker improvements

dev-docs/RFCs/v1.0/loader-module-rfc.md, docs/README.md, docs/table-of-contents.json, modules/3d-tiles/README.md, modules/arrow/README.md, modules/ply/README.md, website/ocular-config.js
- Move core api reference into the module reference list
- Tone down the "framework independent" message - we want to focus on the simple message that we have loaders...
=> docs: Address review comments

examples/gltf-deck/README.md, examples/gltf-deck/app.js, examples/gltf-deck/environment.js, examples/gltf-deck/file-drop.js, examples/gltf-deck/package.json, examples/gltf-deck/webpack.config.js, examples/pointcloud/package.json, examples/webpack.config.local.js
This is an example of using the `GLTFLoader` with the scenegraph layer.
@georgios-uber 
- I can't get the IBL lighting to work, any chance you could take a quick look?
@xintongxia 
- The `ScenegraphLayer` doesn't update after the model loads, until I interact with the viewport, are we forgetting to call `layer.setNeedsUpdate()` somewhere in the `ScenegrapLayer?
@bravecow FYI
- you requested a simpler example
- this is not luma.gl but deck.gl, however the example is much cleaner in this API. 
- Naturally the luma.gl glTF API and example still need to be simplified.
=> glTF deck.gl example

docs/api-reference/potree/README.md, docs/specifications/category-3d-tiles.md, modules/potree/LICENSE, modules/potree/README.md, modules/potree/docs/README.md, modules/potree/package.json, modules/potree/src/bundle.js, modules/potree/src/index.js, modules/potree/src/lib/octree.js, modules/potree/src/parsers/parse-potree-hierarchy-chunk.js, modules/potree/src/potree-bin-loader.js, modules/potree/src/potree-hierarchy-chunk-loader.js, modules/potree/src/potree-loader.js, modules/potree/test/index.js, modules/potree/test/potree-hierarchy-chunk-loader.spec.js, test/aliases.js, test/modules.js
=> potree: Initial parser code for potree format

examples/deck.gl/3d-tiles/components/control-panel.js, examples/deck.gl/3d-tiles/package.json, modules/3d-tiles/package.json, modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-gltf-view.js, modules/3d-tiles/src/lib/tileset/tileset-3d-traverser.js, modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.js
Restored the additive refinement code. Naturally, this uncovers other issues.
=> glTF fixes

examples/three.js/3d-tiles/mapbox-3d-tiles-layer/mapbox-3d-tiles-layer.js, examples/three.js/3d-tiles/threejs-3d-tiles/tile-header.js, examples/three.js/3d-tiles/threejs-3d-tiles/tile-parsers.js, examples/three.js/3d-tiles/threejs-3d-tiles/tileset.js, modules/3d-tiles/docs/api-reference/tile-3d-loader.md, modules/3d-tiles/src/lib/parsers/helpers/parse-3d-tile-gltf-view.js
- Prep for introducing loaders.gl traversal
=> 3d-tiles: THREE.js example refactor

modules/images/docs/README.md, modules/images/docs/api-reference/image-loader.md, modules/images/src/image-loader.js, modules/images/src/lib/parsers/parse-to-image-bitmap.js
=> images: Pass through imagebitmap creation options

cpp/PotreeConverter/PotreeConverter/CMakeLists.txt, cpp/PotreeConverter/PotreeConverter/include/OctreeNode.h, cpp/PotreeConverter/PotreeConverter/include/PTXPointReader.h, cpp/PotreeConverter/PotreeConverter/include/Tile.h, cpp/PotreeConverter/PotreeConverter/include/Tile3DConverter.h, cpp/PotreeConverter/PotreeConverter/include/TileWriter.h, cpp/PotreeConverter/PotreeConverter/src/OctreeNode.cpp, cpp/PotreeConverter/PotreeConverter/src/Tile.cpp, cpp/PotreeConverter/PotreeConverter/src/Tile3DConverter.cpp, cpp/PotreeConverter/PotreeConverter/src/TileWriter.cpp, cpp/PotreeConverter/PotreeConverter/src/main.cpp
for #478 
- initial implementation of the tilling tool which supports cesium 3D spec.
- add some improvements to handle app parameters better.
=> Add cesium point cloud 3D tile format support

cpp/PotreeConverter/PotreeConverter/include/Tile.h, cpp/PotreeConverter/PotreeConverter/include/Tile3DConverter.h, cpp/PotreeConverter/PotreeConverter/include/Utils.h, cpp/PotreeConverter/PotreeConverter/lib/arguments/arguments.hpp, cpp/PotreeConverter/PotreeConverter/src/Tile.cpp, cpp/PotreeConverter/PotreeConverter/src/Tile3DConverter.cpp, cpp/PotreeConverter/PotreeConverter/src/Utils.cpp, cpp/PotreeConverter/PotreeConverter/src/main.cpp
=> Add georeference for 3d tiles

cpp/PotreeConverter/PotreeConverter/CMakeLists.txt, cpp/PotreeConverter/PotreeConverter/include/Tile.h, cpp/PotreeConverter/PotreeConverter/include/Tile3DConverter.h, cpp/PotreeConverter/PotreeConverter/include/TileConfig.h, cpp/PotreeConverter/PotreeConverter/include/TileWriter.h, cpp/PotreeConverter/PotreeConverter/src/Tile.cpp, cpp/PotreeConverter/PotreeConverter/src/Tile3DConverter.cpp, cpp/PotreeConverter/PotreeConverter/src/TileWriter.cpp, cpp/PotreeConverter/PotreeConverter/src/main.cpp
=> add draco compression support

modules/core/src/lib/select-loader.js, modules/core/test/lib/select-loader.spec.js, modules/images/src/image-loader.js
For https://github.com/uber-web/loaders.gl/issues/491
=> Support selecting loader from data url

examples/deck.gl/3d-tiles/app.js, examples/deck.gl/3d-tiles/examples.js, yarn.lock
=> Improve point cloud examples by tuning screen space error

modules/3d-tiles/src/lib/tileset/helpers/bounding-volume.js
fix the culling bug when rendering batched models
=> create a sphere from map region

modules/gltf/src/gltf-loader.js, modules/gltf/src/lib/post-process-gltf.js, modules/gltf/test/gltf-loader.spec.js
@ibgreen I redid the previous one commit [#546](https://github.com/uber-web/loaders.gl/pull/546) Added an option resolveValue and test case. But I'm not sure if the test case is done correctly.
=> glTF: Added option - resolveValue. Creates TypedArray for the accessor

modules/gltf/docs/api-reference/gltf-loader.md, modules/gltf/docs/api-reference/post-process-gltf.md, modules/gltf/src/gltf-loader.js, modules/gltf/src/lib/post-process-gltf.js, modules/gltf/test/gltf-loader.spec.js
=> gltf: Remove `gltf.resolveValues` options, better docs

docs/developer-guide/concepts/worker-threads.md, docs/developer-guide/using-loaders.md, docs/developer-guide/using-worker-loaders.md, docs/table-of-contents.json
Improve documentation about worker loaders, to support @xintongxia's work on fixing the CDN worker loading.
=> docs: Improve worker loader docs

examples/deck.gl/3d-tiles/app.js, examples/deck.gl/3d-tiles/package.json, modules/core/src/lib/loader-utils/parse-with-worker.js, modules/draco/src/draco-loader.js, modules/loader-utils/src/lib/validate-loader-version.js, modules/loader-utils/test/worker-utils/validate-loader-version.spec.js
followup
- expand to other worker loaders
- update doc depend on #550
=> Support customized worker loader url

babel.config.js
=> build speed 2x: Avoid transpiling libs folder

babel.config.js, package.json
Now includes a bumped dev-tools to ensure ignored files are copied.
=> build: 2x speed (Take 2)

modules/gltf/src/lib/post-process-gltf.js
luma.gl updated
https://github.com/uber/luma.gl/pull/1318
=> remove unused getImageAsync call

examples/cesium/3d-tiles/tileset-loader.js, examples/deck.gl/3d-tiles/3d-tile-layer/tile-3d-layer.js, examples/deck.gl/3d-tiles/app.js, modules/3d-tiles/docs/api-reference/tileset-3d.md, modules/3d-tiles/src/lib/tileset/tileset-3d.js, modules/3d-tiles/wip/tileset-3d-full.md, modules/i3s/src/lib/tileset/i3s-tileset.js
=> deck.gl v8.0 API audit

modules/i3s/src/lib/utils/lod.js
- changed getDistanceFromLatLon to do the evaluation in Cartesian space 
- added projectVertexToSphere function to project a lon, lat, z values to a sphere
- introduced a qualityFactor to bias LOD selection
- code clean up
@xintongxia  please review.
=> Improved Lod Selection criteria for I3S layers

modules/polyfills/src/index.js, modules/polyfills/test/fetch-node/response.node.spec.js, modules/polyfills/test/index.js
=> Fix polyfill module typo

modules/json/src/clarinet/clarinet.js, modules/json/src/json-loader.js, modules/json/test/json-loader.spec.js, modules/tables/src/lib/table/row-table-batch.js, modules/tables/src/lib/table/table-batch-builder.js
=> json: Minor fixes

modules/3d-tiles/src/lib/tileset/helpers/bounding-volume.js, modules/3d-tiles/src/lib/tileset/tileset-3d.js
The tile transform was not properly applied to halfAxes.
=> [3d-tiles] Fix bounding volume calculation

modules/core/src/lib/select-loader.js
- Check response header's content-type to select loader
- fix typo in polyfill module
- rm debugging code in render test
depend on #577
=> Check response content type to match loader

docs/table-of-contents.json, modules/json/docs/README.md, modules/json/docs/api-reference/json-loader.md, modules/json/package.json, test/modules.js, website/package.json
extracted from the WKT PR #575
=> json: Clean up docs

modules/images/src/lib/texture-loading-api/generate-url.js, modules/images/test/lib/texture-loading-api/load-image.spec.js
=> images: loadImage now calls resolvePath

modules/loader-utils/package.json
Breaks bundling with es5 distribution
=> Fix loader-utils browser field

modules/core/src/index.js, package.json, yarn.lock
Also fixes the precommit breakage.
=> root: Add pre-push hook

modules/mvt/test/mvt-loader.spec.js
Restore tests after publishing #626
=> mvt: enable test after publishing

docs/upgrade-guide.md, docs/whats-new.md, modules/json/docs/api-reference/json-loader.md, modules/json/src/lib/parse-json-in-batches.js, modules/json/src/lib/parser/streaming-json-parser.js, modules/json/test/json-loader.spec.js
=> json: Return wrapper object in streaming parsing

modules/mvt/test/mvt-loader.spec.js
use local worker url as other loaders.
=> mvt: Fix worker url used in test

modules/images/package.json
=> images: Add dependency

modules/tiles/src/tileset/traversers/tileset-traverser.js, package.json
root tile should be selected for render when it is visible.
=> [tiles]: fix traversal - select root node when it is visible

modules/core/src/javascript-utils/is-type.js
=> core: Fix tests on Firefox (ReadableStream detection fix)

examples/deck.gl/3d-tiles/app.js, examples/deck.gl/3d-tiles/components/control-panel.js, examples/deck.gl/3d-tiles/tile-3d-layer.js, modules/3d-tiles/docs/api-reference/cesium-ion-loader.md, modules/3d-tiles/src/cesium-ion-loader.js, modules/3d-tiles/src/index.js, modules/3d-tiles/src/tiles-3d-loader.js, modules/tiles/src/tileset/tileset-3d.js
=> [3d-tiles]: Add CesiumIonLoader to allow resolving authorization in preload

modules/mvt/docs/api-reference/mapbox-vector-tile-loader.md, modules/mvt/src/mvt-loader.js
Small `MVTLoader` docs updates. See #679
=> Small MVTLoader docs updates

examples/get-started/get-started-rollup/app.js, examples/get-started/get-started-rollup/index.html, examples/get-started/get-started-webpack/app.js, examples/get-started/get-started-webpack/index.html, examples/get-started/get-started-webpack/package.json, modules/i3s/src/lib/parsers/constants.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
Few minor changes in the examples to make the resulting json object to be visible within a page (v.s. resorting to go to the debug console) and a spelling fix.
=> Minor changes in examples plus a spelling fix

docs/whats-new.md
Update whats new with some .gifs rendered by deck layers.
=> v2.1 whats new

examples/benchmark/app.js, examples/benchmark/index.html, examples/benchmark/package.json, examples/benchmark/webpack.config.js, examples/webpack.config.local.js, modules/core/src/lib/fetch/fetch-file.js, test/bench/bench-modules.js, test/bench/index.js
Signed-off-by: Shan He <heshan0131@gmail.com>
=> [examples] add benchmark examples

modules/3d-tiles/docs/api-reference/tiles-3d-loader.md, modules/3d-tiles/src/tiles-3d-loader.js, modules/3d-tiles/test/tiles-3d-loader.spec.js, modules/core/docs/api-reference/load.md, modules/core/docs/api-reference/parse.md, modules/i3s/docs/api-reference/i3s-loader.md, modules/i3s/src/i3s-loader.js
=> i3s and 3d-tiles: remove json from extensions

examples/deck.gl/i3s/examples.js
@xintongxia please review. Update to service URL.
thx
=> Service URL update for New York City

modules/images/docs/README.md, website/gatsby-config.js, website/package.json
This probably should be fixed in ocular/gastby. This PR intendeds to point out the issues and unblock publishing website, and look for better solution.
=> website: fix gatsby config

modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.js
for https://github.com/visgl/deck.gl/issues/4457
=> 3d-tiles: restore parsing content url

examples/deck.gl/i3s/README.md, examples/deck.gl/i3s/app.js, examples/deck.gl/i3s/components/control-panel.js, examples/deck.gl/i3s/examples.js, modules/i3s/src/lib/parsers/constants.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
For #730 and https://github.com/visgl/deck.gl/issues/4554
=> i3s: skip parsing region data when not available

modules/3d-tiles/docs/api-reference/cesium-ion-loader.md, modules/3d-tiles/docs/api-reference/tiles-3d-loader.md, modules/3d-tiles/src/tiles-3d-loader.js, modules/i3s/docs/api-reference/i3s-loader.md
for https://github.com/visgl/deck.gl/issues/4582
=> 3d-tiles: fix parsing tileset option

modules/polyfills/src/fetch-node/read-file.node.js, modules/polyfills/src/fetch-node/utils/stream-utils.node.js, modules/polyfills/test/fetch-node/fetch.node.spec.js
This should cover: https://github.com/visgl/loaders.gl/issues/496
=> Support compression in node polyfill

modules/zip/README.md, modules/zip/src/index.js, modules/zip/src/libs/header.js, modules/zip/src/libs/tar.js, modules/zip/src/libs/utils.js, modules/zip/src/tar-builder.js
=> Experimental TARBuilder

examples/website/i3s/examples.js
Updated some tokens that got changed. should be infrequent.
=> Updated token.

modules/ply/src/ply-loader.js
related to: https://github.com/visgl/loaders.gl/issues/783
=> Add octet-stream to ply loader mimetypes

docs/upgrade-guide.md, docs/whats-new.md, modules/core/src/lib/api/parse-in-batches.js, modules/core/src/lib/loader-utils/merge-options.js, modules/json/src/json-loader.js, modules/json/test/json-loader.spec.js, modules/loader-utils/src/types/types.d.ts, modules/ply/src/lib/parse-ply-in-batches.js
Fix metadata batch, add tests
Also add deprecation warnings for `_rootObjectBatches` option.
=> core: Fix metadata batch

modules/core/src/lib/utils/resource-utils.js, modules/core/test/lib/select-loader.spec.js
Added a query param test case to selectLoader but it doesn't seem to trigger the bug discovered in deck.gl.
=> Add query param test case to select loaders

modules/shapefile/src/dbf-loader.js, modules/shapefile/test/dbf/parse-dbf.spec.js
Thanks to https://github.com/visgl/loaders.gl/pull/834
=> Default dbf loader to windows-1252

modules/core/docs/api-reference/load-in-batches.md, modules/core/src/lib/api/load-in-batches.d.ts, modules/core/src/lib/api/load-in-batches.js, modules/core/test/index.js, modules/core/test/lib/load-in-batches.spec.js, modules/core/test/lib/parse-in-batches.spec.js
Another prep diff for FileSystem loading.
=> core: loadInBatches can accept multiple files

modules/core/src/lib/api/load-in-batches.js, modules/core/src/lib/api/parse-in-batches.js, modules/shapefile/src/shapefile-loader.js, modules/shapefile/test/shapefile-loader.spec.js
Various issues found when testing shapefile loader in app
=> shapefile: loading fixes

modules/gis/src/lib/binary-to-geojson.js
@kylebarron Your fix without the test case that triggers the complications, let's see if this passes.
=> gis: Add multipolygon support

modules/core/src/lib/common.d.ts
=> core: Fix stray FileReadableResponse import

modules/mvt/src/lib/parse-mvt.js, modules/mvt/test/mvt-loader.spec.js
To enable `tileCacheMaxBytes` props
=> mvt: Add result.byteLength

CONTRIBUTING.md, docs/developer-guide/dev-env.md
Previous attempt left some duplications.
=> Docs: contributing.md cleanup

modules/pcd/src/lib/parse-pcd.js
=> Fix color values equal 0 after loading from PCD file.

modules/pcd/src/lib/parse-pcd.js, modules/pcd/test/pcd-loader.spec.js
Additional fixes for #885 
@namndtth
=> pcd: color and normal attribute fixes

docs/whats-new.md, modules/core/src/iterator-utils/make-iterator/blob-iterator.js, modules/core/src/lib/filesystems/browser-filesystem.js, modules/core/src/lib/progress/fetch-progress.js, modules/core/test/lib/utils/resource-utils.spec.js, modules/core/test/lib/utils/response-utils.spec.js, modules/csv/test/papaparse/csv-test-cases.js, modules/loader-utils/src/lib/binary-utils/array-buffer-utils.js, modules/polyfills/docs/api-reference/README.md, modules/polyfills/package.json, modules/polyfills/src/fetch-node/response.node.js, modules/polyfills/src/fetch-node/utils/decode-data-uri.node.js, modules/polyfills/src/file/blob-polyfill.d.ts, modules/polyfills/src/file/blob-polyfill.js, modules/polyfills/src/file/file-polyfill.d.ts, modules/polyfills/src/file/file-polyfill.js, modules/polyfills/src/file/file-reader-polyfill.d.ts, modules/polyfills/src/file/file-reader-polyfill.js, modules/polyfills/src/file/polyfills.js, modules/polyfills/src/file/readable-stream-polyfill.d.ts, modules/polyfills/src/file/readable-stream-polyfill.js, modules/polyfills/src/index.js, modules/polyfills/test/file/blob-polyfill.spec.js, modules/polyfills/test/file/file-polyfill.spec.js, modules/polyfills/test/index.js, modules/shapefile/test/shapefile-loader.spec.js, test/modules.js, yarn.lock
For CI testing of apps that make heavy use of `File` objects.
=> polyfills: Blob/File/FileReader polyfills

modules/crypto/docs/README.md, modules/crypto/docs/api-reference/crypto-hash-transform.md
Limit scope of disclaimer to the affected class.
=> Crypto doc correction

modules/compression/src/lib/lz4/lz4-deflate-transform.d.ts, modules/compression/src/lib/lz4/lz4-deflate-transform.js, modules/compression/src/lib/lz4/lz4-inflate-transform.d.ts, modules/compression/src/lib/lz4/lz4-inflate-transform.js, modules/compression/src/lib/zlib/zlib-deflate-transform.d.ts, modules/compression/src/lib/zlib/zlib-deflate-transform.js, modules/compression/src/lib/zlib/zlib-inflate-transform.d.ts, modules/compression/src/lib/zlib/zlib-inflate-transform.js, modules/compression/src/lib/zstd/zstd-deflate-transform.d.ts, modules/compression/src/lib/zstd/zstd-deflate-transform.js, modules/compression/src/lib/zstd/zstd-inflate-transform.d.ts, modules/compression/src/lib/zstd/zstd-inflate-transform.js, modules/compression/src/types.d.ts, modules/compression/test/lz4/lz4.spec.js, modules/compression/test/zlib/zlib.spec.js, modules/compression/test/zstd/zstd.spec.js
Adds Zlib streaming compression transform.
=> compression: Support streaming

modules/pcd/package.json, modules/pcd/src/lib/parse-pcd.js, modules/pcd/test/pcd-loader.spec.js, modules/tables/src/index.d.ts, modules/tables/src/index.js, modules/tables/src/lib/types/arrow-like/type.d.ts, modules/tables/src/lib/types/arrow-like/type.js
Starting to add arrow style schemas to binary loaders.
=> pcd: Add schema

modules/loader-utils/src/types.d.ts, modules/shapefile/src/lib/parsers/parse-dbf.d.ts, modules/shapefile/src/lib/parsers/parse-dbf.js, modules/shapefile/src/lib/parsers/parse-shapefile.d.ts, modules/shapefile/src/lib/parsers/parse-shapefile.js, modules/shapefile/src/lib/parsers/parse-shp-geometry.d.ts, modules/shapefile/src/lib/parsers/parse-shp-header.d.ts, modules/shapefile/src/lib/parsers/parse-shp.d.ts, modules/shapefile/src/lib/parsers/parse-shx.d.ts, modules/shapefile/src/lib/streaming/zip-batch-iterators.d.ts, modules/shapefile/src/shp-loader.js
=> Shapefile: types

examples/website/i3s-arcgis/README.md, examples/website/i3s-arcgis/app.js, examples/website/i3s-arcgis/index.html, examples/website/i3s-arcgis/package.json, examples/website/i3s-arcgis/webpack.config.js, examples/website/i3s/examples.js, examples/website/i3s/index.html
Also fixed html title for the Mapbox-based example.
=> Added an I3S example that uses the Arcgis basemap.

modules/loader-utils/src/index.d.ts, modules/loader-utils/src/index.js, modules/loader-utils/src/lib/binary-utils/array-buffer-utils.d.ts, modules/loader-utils/src/lib/binary-utils/array-buffer-utils.js, modules/loader-utils/src/lib/binary-utils/binary-copy-utils.d.ts, modules/loader-utils/src/lib/binary-utils/binary-copy-utils.js, modules/loader-utils/src/lib/binary-utils/encode-utils.js, modules/loader-utils/src/lib/binary-utils/memory-copy-utils.d.ts, modules/loader-utils/src/lib/binary-utils/memory-copy-utils.js, modules/loader-utils/src/lib/process-utils/child-process-proxy.d.ts, modules/loader-utils/src/lib/process-utils/child-process-proxy.js, modules/loader-utils/test/lib/binary-utils/array-buffer-utils.spec.js, modules/loader-utils/test/lib/binary-utils/binary-copy-utils.spec.js, modules/loader-utils/test/lib/binary-utils/memory-copy-utils.spec.js
- concatenateTypedArrays function;
- padToNBytes function;
- ChildProcessProxy - wait === 0 - infinity
=> loader-utils: new features

modules/gltf/src/lib/encode-glb.js, modules/gltf/src/lib/gltf-scenegraph.js, modules/gltf/src/lib/parse-glb.js, modules/gltf/test/lib/utils/encode-utils.spec.js, modules/loader-utils/src/index.d.ts, modules/loader-utils/src/index.js, modules/loader-utils/src/lib/binary-utils/binary-copy-utils.d.ts, modules/loader-utils/src/lib/binary-utils/binary-copy-utils.js, modules/loader-utils/src/lib/binary-utils/memory-copy-utils.d.ts, modules/loader-utils/src/lib/binary-utils/memory-copy-utils.js, modules/loader-utils/src/lib/process-utils/child-process-proxy.js, modules/loader-utils/test/lib/binary-utils/binary-copy-utils.spec.js, modules/loader-utils/test/lib/binary-utils/memory-copy-utils.spec.js
Fixes comments from https://github.com/visgl/loaders.gl/pull/1003
=> loader-utils: padToNBytes function

modules/las/src/lib/laslaz-decoder.js
=> Fix require is not defined (rollup) (#1011)

modules/crypto/src/lib/utils/digest-utils.js, modules/crypto/test/lib/digest-utils.spec.js
=> crypto: convert zero leading hex correctly

modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js, modules/tile-converter/src/i3s-converter/json-templates/layers.js
1) Features in compressed geometry becomes available
2) Fixed color of tileset without textures (New York)
=> Added feature ids support for compressed geometry 3DTiles -> I3s converter

modules/loader-utils/src/lib/worker-utils/worker-pool.js, modules/loader-utils/test/lib/worker-utils/worker-farm.spec.js
There was an issue https://github.com/visgl/loaders.gl/issues/1026
It was not properly fixed.
Improved this fix + added some tests
=> Fix for workers-pool with reuseWorkers flag

modules/tile-converter/docs/api-reference/3d-tiles-converter.md, modules/tile-converter/docs/cli-reference/tile-converter.md
Fixes comments from https://github.com/visgl/loaders.gl/pull/1045
=> tile-converter: minor docs update

modules/arrow/src/arrow-loader.js, modules/arrow/src/lib/parse-arrow-sync.js, modules/arrow/test/arrow-loader.spec.js, modules/core/src/lib/loader-utils/option-utils.js
=> Add "rowBased" option for arrow loader

test/bench/modules.js
I checked it on the local machine. No errors occur.
=> tests: draco bench test

modules/draco/src/lib/draco-parser.js, modules/draco/src/types/draco-types.d.ts
Current master:
This branch:
I checked this on local loader (not worker).
=> draco: increase decompression performance

modules/gltf/src/lib/parse-gltf.js
=> gltf: change buffer parsing order

examples/website/textures/app.js, examples/website/textures/components/compressed-texture.js, examples/website/textures/components/textures-uploader.js
=> Added drag&drop functionality to textures app

examples/website/textures/components/compressed-texture.js
* Added vendor prefixes to support mobile browsers
=> Texture app get extension with vendor prefixes

modules/csv/src/libs/papaparse.js, modules/las/src/libs/laz-perf.js, modules/polyfills/src/libs/encoding.js, scripts/bundle.config.js
@ibgreen  I tested it to create the same logic is [here](https://codepen.io/Pessimistress/pen/LYRKMqK?editors=1001) but locally.
Also we should implements some test cases for scripts too.
=> Fix for Pre-built bundles broken in 2.3.9

modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js, modules/tile-converter/src/i3s-converter/i3s-converter.js
London: 
[3DTILES_London_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip](https://github.com/visgl/loaders.gl/files/5965208/3DTILES_London_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip)
Berlin:
[3DTILES_Berlin_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip](https://github.com/visgl/loaders.gl/files/5965209/3DTILES_Berlin_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip)
Munich:
[3DTILES_Munich_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip](https://github.com/visgl/loaders.gl/files/5965211/3DTILES_Munich_ubuntu_modules_cli_slpk_draco_full_bundle_16_v17.log.zip)
=> tile-converter: i3s - convert COLOR_0

modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js
I divided logic of normal transformation.
* Used `Vector3.transformAsVector` method;
* Don't apply translation to `cartographicOrigin`;
* Position transformation logic hasn't been changed.
Regarding "Premier3DCities..." tilesets color conversion - nothing changed:
=> tile-converter: i3s fixes normal conversion

modules/loader-utils/src/lib/binary-utils/binary-copy-utils.d.ts, modules/loader-utils/src/types.d.ts
=> fix(loader-utils): TypedArray type import

examples/experimental/i3s-picking/examples.js, examples/experimental/i3s-picking/tile-layer/tile-layer.js, modules/i3s/src/lib/parsers/constants.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js, modules/i3s/test/i3s-loader.spec.js
=> Add i3s 1.6 picking support

examples/experimental/i3s-picking/app.js
=> I3s Picking improve tooltip view

modules/gis/src/lib/geojson-to-binary.js, modules/mvt/test/mvt-loader.spec.js
=> Patch fix MVT empty binary tiles (#1235)

modules/i3s/src/lib/parsers/parse-i3s-tile-content.js, modules/i3s/test/lib/parsers/parse-i3s-tile-content.spec.js
=> I3S-picking fix for integrated mesh layers

examples/experimental/i3s-17-and-debug/app.js, modules/i3s/src/i3s-attribute-loader.js, modules/i3s/src/index.js, modules/i3s/test/i3s-attribute-loader.spec.js
`getAttributesFromTileByFeatureId -> getTileAttributesFromFeatureId`
=> I3s-picking - Rename internal function

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/app.js, examples/experimental/i3s-17-and-debug/components/attributes-tooltip.js, examples/experimental/i3s-17-and-debug/mesh-layer/mesh-layer.js, examples/experimental/i3s-17-and-debug/mesh-layer/simple-mesh-layer-vertex.glsl.js, examples/experimental/i3s-17-and-debug/tile-debug.js, examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
=> I3S - Tileset debugging initial version

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/app.js, examples/experimental/i3s-17-and-debug/mesh-layer/mesh-layer.js, examples/experimental/i3s-17-and-debug/url-utils.js, modules/i3s/src/helpers/i3s-nodepages-tiles.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
Fix for custom tilesets with token
=> I3S - picking add url token support

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js
=> I3S-debug - Move memory usage to debug panel

modules/i3s/test/i3s-loader.bench.js, test/bench/modules.js
=> I3SLoader - Add benchmark

examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/components/semantic-validator.js
=> I3S-Debug - Add semantic validator ui

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/attributes-panel.js, examples/experimental/i3s-17-and-debug/constants.js, examples/experimental/i3s-17-and-debug/tile-debug.js
1) Updated tooltip with short info about tile.
2) Updated attributes-panel with more data about selected tile.
3) Changed color picker component to improve user experience. 
4) Added reset button for selected color
=> I3S-Debug - Improve attributes panel in debug mode

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/components/semantic-validator.js, examples/experimental/i3s-17-and-debug/constants.js
=> I3S-Debug - Change Semantic Validator UI

modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js
=> tile-converter: fix attributes normalization

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/components/semantic-validator.js, examples/experimental/i3s-17-and-debug/tile-debug.js
- Added Clear All Button
- Minor refactoring
=> I3S-Debug - Semantic Validator improvements

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/tile-validator.js, examples/experimental/i3s-17-and-debug/tile-debug.js
=> I3S-Debug - Add validator for tile geometry

examples/experimental/i3s-17-and-debug/components/attributes-panel.js, examples/experimental/i3s-17-and-debug/tile-debug.js
=> I3S-Debug - Attributes panel improvemets

examples/experimental/i3s-17-and-debug/components/debug-panel.js
Rename event handlers and encapsulated methods
=> i3s-debug: debug panel refactoring

modules/tiles/src/tileset/tileset-3d.js, modules/tiles/src/tileset/traversers/tileset-traverser.js
Fixes comments from https://github.com/visgl/loaders.gl/pull/1296
=> tiles: refactor tileset-3d

modules/tile-converter/docs/api-reference/i3s-converter.md, modules/tile-converter/package.json, modules/tile-converter/src/i3s-converter/helpers/node-debug.js, modules/tile-converter/src/i3s-converter/i3s-converter.d.ts, modules/tile-converter/src/i3s-converter/i3s-converter.js, modules/tile-converter/test/i3s-converter/i3s-converter.spec.js, yarn.lock
=> tile-converter - Add Node Bounding Volumes Validation

examples/experimental/i3s-17-and-debug/components/tile-validator.js, examples/experimental/i3s-17-and-debug/tile-debug.js
=> I3S-Debug - Compare geometry bounding volume vs tile bounding volume

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/tile-validator.js, examples/experimental/i3s-17-and-debug/normals-utils.js
=> I3S-Debug - Add normals debug feature

examples/experimental/i3s-17-and-debug/components/tile-validator.js, examples/experimental/i3s-17-and-debug/tile-debug.js
- Added JSDoc to tile debug file
- Change error handling logic while debugging process
=> I3S-Debug - Tile debug refactoring

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
=> I3S-Debug - Add wireframe mode

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/package.json, modules/i3s/src/i3s-loader.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js
=> i3s-debug: texture checker

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/tile-validator.js, examples/experimental/i3s-17-and-debug/normals-utils.js
=> I3S-Debug - Add input for changing debug normals length

examples/experimental/i3s-17-and-debug/components/debug-panel.js
=> I3S-Debug - Move Wireframe mode to tile options

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js
=> i3s-debug: show-debug-texture-image

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/bounding-volume-layer.js, examples/experimental/i3s-17-and-debug/color-map.js, examples/experimental/i3s-17-and-debug/components/debug-panel.js, examples/experimental/i3s-17-and-debug/constants.js, examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js
1. Rename `ObbLayer` -> `BoundingVolume` layer
2. Naming refactoring
=> I3S-Debug - Rename ObbLayer -> BoundingVolumeLayer

modules/i3s/src/lib/parsers/parse-i3s.js, modules/tiles/src/tileset/helpers/bounding-volume.js
1. tiles: obb feature has been added in BoundingVolume logic for compute plane Intersections with frustum. 
2. comment is fixed
=> feat(tiles): OBB transformation

modules/tile-converter/src/lib/utils/compress-util.js, modules/tile-converter/src/lib/utils/file-utils.d.ts, modules/tile-converter/src/lib/utils/file-utils.js, modules/tile-converter/src/lib/utils/statistic-utills.js
Related to [discussion](https://github.com/visgl/loaders.gl/discussions/1362) fix for file paths.
=> Converter - Fix for absolute file path

examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js, modules/i3s/src/helpers/i3s-nodepages-tiles.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.js, modules/i3s/src/lib/parsers/parse-i3s.js, modules/i3s/test/helpers/i3s-nodepages-tiles.spec.js, modules/i3s/test/i3s-loader.spec.js, modules/i3s/test/lib/parsers/parse-i3s-tile-content.spec.js, modules/tile-converter/src/3d-tiles-converter/helpers/b3dm-converter.js
This is improvement for I3S 1.7 loading:
- removed duplicated texture;
- draw indices instead of flattening arrays on CPU;
- optimization for creating MBS from OBB.
It works faster now. But we need to new release after merging this PR to have new version of worker.
=> i3s: optimization

examples/experimental/i3s-17-and-debug/components/tile-validator.js
=> I3S-Debug - Disable normal validation controls if there are no normals in tile

modules/tiles/src/tileset/tileset-3d.js
Its implementation of https://github.com/visgl/deck.gl/pull/5758#issuecomment-848982491
=> tiles: update isLoaded logic

dev-docs/RFCs/3d-tiles-and-i3s.md, docs/specifications/category-3d-tiles.md, modules/3d-tiles/docs/api-reference/tiles-3d-loader.md, modules/i3s/docs/api-reference/i3s-loader.md, yarn.lock
First step towards unifying the tiles documentation.
=> docs(tiles): Unify data format documentation

docs/whats-new.md
regarding this comment
https://github.com/visgl/loaders.gl/issues/1368#issuecomment-852344287
=> Adding docs for new tesselator option in terrainloader

.eslintrc.js
=> eslint: fix ts imports

examples/webpack.config.local.js
Checked the following examples by` yarn start-local`:
- Basis - OK
- Benchmark - ERROR
- 3d-tiles-with-cesium - ERROR Cesium is not defined (looks like an error not related to webpack config)
- 3d-tiles-with-three - OK
- gltf-with-deck.gl - OK
- gltf-with-raw-webgl - OK
- i3s-17-and-debug - OK
- 3d-tiles -OK
- GLTF -OK
- i3s -OK
- i3s-acrgis - OK
- pointcloud - OK
- textures - OK
=> Fix for local webpack config

modules/worker-utils/src/lib/worker-farm/worker-farm.js, modules/worker-utils/src/lib/worker-farm/worker-pool.d.ts, modules/worker-utils/src/lib/worker-farm/worker-pool.js, scripts/webpack/worker.js
=> feat(worker-utils): Support dynamic update of maxConcurrency etc

modules/draco/src/draco-loader.ts, modules/gltf/docs/api-reference/glb-loader.md, modules/gltf/src/glb-loader.ts, modules/gltf/src/glb-writer.ts, modules/gltf/src/gltf-loader.ts, modules/gltf/src/gltf-writer.ts, modules/gltf/src/index.ts, modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.ts, modules/gltf/src/lib/parsers/parse-glb.ts, modules/gltf/src/lib/parsers/parse-gltf.ts, modules/gltf/src/lib/types/glb-types.ts
Similar to #1504 without removing types.
=> fix(gltf): Fix option propagation

modules/gltf/src/glb-loader.ts, modules/gltf/src/gltf-loader.ts, modules/gltf/src/gltf-writer.ts, modules/gltf/src/index.ts, modules/gltf/src/lib/api/gltf-scenegraph.ts, modules/gltf/src/lib/api/normalize-gltf-v1.js, modules/gltf/src/lib/extensions/EXT_meshopt_compression.ts, modules/gltf/src/lib/extensions/KHR_binary_gltf.ts, modules/gltf/src/lib/extensions/KHR_draco_mesh_compression.ts, modules/gltf/src/lib/extensions/KHR_lights_punctual.ts, modules/gltf/src/lib/extensions/KHR_materials_unlit.ts, modules/gltf/src/lib/extensions/KHR_techniques_webgl.ts, modules/gltf/src/lib/extensions/gltf-extensions.ts, modules/gltf/src/lib/gltf-utils/gltf-attribute-utils.ts, modules/gltf/src/lib/parsers/parse-gltf.ts, modules/gltf/src/lib/types/gltf-json-schema.ts, modules/gltf/src/lib/types/gltf-postprocessed-schema.ts, modules/gltf/src/lib/types/gltf-types.ts, modules/tiles/src/tileset/tileset-3d.ts
- Add autogenerated types for the GLTF json structure
- Improve loader option typings
=> chore(gltf): Add autogenerated glTF types

examples/experimental/i3s-17-and-debug/app-debug.js, examples/experimental/i3s-17-and-debug/app.js, examples/experimental/i3s-17-and-debug/package.json, website/package.json, website/yarn.lock
- update deck.gl version;
- fix warning "Top level loader option 'throttleRequests' not recognized.";
- fix warning "Top level loader option 'loadTiles' not recognized.".
=> i3s-app: update deck.gl version

modules/tiles/src/tileset/helpers/tiles-3d-lod.ts, modules/tiles/src/tileset/tileset-3d.ts
I cross-checked the deleted properties with other modules. These are never used.
=> tiles: remove unused private props

package.json, scripts/webpack/worker.js, yarn.lock
Just remove hardcode of dev env. 
@ibgreen @Avnerus Maybe I missed some hidden issue related to my changes.
Do you know any?
=> Remove hardcoded dev worker config

.eslintrc.js, .ocularrc.js, babel.config.js, package.json, yarn.lock
@Avnerus this should pull in your ocular changes.
=> chore: Bump ocular-dev-tools

examples/webpack.config.local.js
Now benchmark app works in local mode
=> Refactoring in webpack-config-local

examples/experimental/i3s-17-and-debug/examples.js, modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts
1. Fix for picking functionality
2. Enable 1.7 tileset by default
=> I3S-App - Fix picking functionality

babel.config.js, package.json
=> Revert "chore: Fix version injection for node and workers"

modules/loader-utils/src/lib/request-utils/request-scheduler.ts
Based on our discussion, did a quick pass on the `RequestScheduler` to make sure typings are solid. Didn't find any issues, but might as well land this as it will make it easier to maintain/refactor the code.
=> chore(loader-utils): Improve RequestScheduler typings

modules/core/src/lib/loader-utils/option-defaults.ts, modules/core/test/lib/api/load-in-batches.spec.js, modules/csv/test/csv-loader.spec.js, modules/loader-utils/src/types.ts, modules/schema/src/lib/table/table-batch-builder.ts
Experimenting with support for preventing browser crashes when loading large files...
=> feat(core): add `limit` options

modules/tiles/docs/api-reference/tile-3d.md, modules/tiles/docs/api-reference/tileset-3d.md, modules/tiles/src/tileset/tileset-3d.ts, modules/tiles/test/tileset/tileset-3d.spec.js
For https://github.com/visgl/loaders.gl/discussions/1527
=> tiles: onTraversalComplete

modules/core/src/lib/loader-utils/normalize-loader.ts
See discussion in deck.gl PR: https://github.com/visgl/deck.gl/pull/5925#discussion_r662299423
=> fix(loader-utils): Fix normalization of text flag

modules/draco/src/lib/draco-parser.ts, modules/draco/src/types.ts, modules/draco/test/lib/utils/schema-attribute-utils.spec.js
This changes fix the following items:
1. GLTF examples on the website
2. I3S-Converter Geometry
=> Fix draco parser

modules/core/src/node/fs.ts
=> fix(core): Fix import statement

modules/loader-utils/src/types.ts, modules/zip/src/zip-loader.ts
Fix for type issues when importing into application.
=> fix: minor issues with exported types

examples/experimental/terrain/README.md, examples/experimental/terrain/app.js, examples/experimental/terrain/package.json
Fixes comments: https://github.com/visgl/loaders.gl/pull/1649
=> examples: terrain use TerrainLoader explicitly

examples/experimental/terrain/app.js, modules/terrain/docs/api-reference/quantized-mesh-loader.md, modules/terrain/docs/api-reference/terrain-loader.md, modules/terrain/src/lib/helpers/skirt.js, modules/terrain/src/lib/parse-quantized-mesh.js, modules/terrain/src/lib/parse-terrain.js, modules/terrain/src/quantized-mesh-loader.ts, modules/terrain/src/terrain-loader.ts, modules/terrain/test/quantized-mesh-loader.spec.js, modules/terrain/test/terrain-loader.spec.js
https://user-images.githubusercontent.com/18549629/125440749-616bfb33-9430-4e1d-b362-8184956e94bd.mp4
=> terrain: skirting

modules/terrain/docs/api-reference/quantized-mesh-loader.md, modules/terrain/docs/api-reference/terrain-loader.md, modules/terrain/src/lib/helpers/skirt.js, modules/terrain/src/lib/parse-quantized-mesh.js, yarn.lock
Fixes comments from https://github.com/visgl/loaders.gl/pull/1662
=> terrain: skirting optimization for quantized

modules/i3s/src/i3s-content-loader.ts, modules/worker-utils/src/lib/worker-api/get-worker-url.ts, website/yarn.lock
=> Load workers of `latest` versions

modules/core/src/iterator-utils/make-iterator/make-iterator.ts, modules/core/src/iterator-utils/make-iterator/stream-iterator.ts, modules/core/src/lib/api/parse-in-batches.ts, modules/core/src/lib/api/parse-sync.ts, modules/core/src/lib/api/parse.ts, modules/core/src/lib/loader-utils/get-data.ts, modules/core/test/lib/loader-utils/get-data.spec.js
Experimental option to increase perf by reading next batch while current batch is being processed.
=> feat(core): Add `options._streamReadAhead`

examples/benchmarks/package.json, examples/website/3d-tiles/package.json, examples/website/i3s/package.json, modules/core/src/iterators/make-iterator/make-stream-iterator.ts
- hopefully final fix for loaders.gl bump
=> fix(core): ReadableStream type result

examples/website/i3s/components/control-panel.js, examples/website/i3s/components/debug-panel.js
=> I3S debug: fix nav visibility on mobile

examples/website/i3s/app.js, examples/website/i3s/index.html
=> I3S Example: hide widget on mobile

examples/website/i3s/color-map.js
=> chore(I3S-debug): change random color map

examples/website/i3s/app-debug.js, examples/website/i3s/app.js, examples/website/i3s/components/control-panel.js, examples/website/i3s/components/debug-option-group.js, examples/website/i3s/components/debug-panel.js, examples/website/i3s/components/memory-stats.js, examples/website/i3s/components/semantic-validator.js, examples/website/i3s/components/toggle-switch.js
=> chore(I3S-Debug): memory stats positioning change

modules/kml/package.json, yarn.lock
https://github.com/placemark/togeojson/blob/main/CHANGELOG.md#450-2021-08-03
=> Bump togeojson dependency for better TCX parsing

modules/crypto/src/lib/node-hash.ts, modules/crypto/test/crypto.spec.js, modules/draco/src/lib/draco-parser.ts, modules/geopackage/src/lib/parse-geopackage.ts, modules/gltf/bundle.js, modules/gltf/src/lib/extensions/EXT_meshopt_compression.ts, modules/images/src/lib/parsers/parse-to-image-bitmap.ts, modules/kml/src/gpx-loader.ts, modules/tiles/src/tileset/helpers/bounding-volume.ts, modules/tiles/src/tileset/tile-3d.ts, modules/worker-utils/src/lib/worker-api/validate-worker-version.ts, scripts/webpack/bundle.js, test/common/conformance.js, tsconfig.json
- add noUnusedLocals rule to tsconfig
- // @ts-ignore in all places to pass noUnusedLocals rule
=> chore(tsc): add noUnusedLocals rule to tsconfig

modules/loader-utils/package.json, modules/worker-utils/package.json
Add node modules to package.json browser field.  Related to https://github.com/visgl/deck.gl/issues/5551 https://github.com/vitejs/vite/issues/2320
=> fix(worker-utils/loader-utils) loaders.gl for vite

modules/gis/test/data/featurecollection.json
Enhance binary/geojson test data to test changes introduced in https://github.com/visgl/loaders.gl/pull/1724
=> Include id field in test data to verify mapping

examples/website/i3s/app-debug.js, examples/website/i3s/components/tool-bar.js, examples/website/i3s/components/tools-bar.js
=> chore(I3S-Debug): tools bar for mobile

examples/website/i3s/app-debug.js, examples/website/i3s/app.js, examples/website/i3s/components/attributes-panel.js, examples/website/i3s/components/control-panel.js, examples/website/i3s/components/debug-panel.js, examples/website/i3s/components/map-info.js, examples/website/i3s/components/semantic-validator.js, examples/website/i3s/components/styles.js, examples/website/i3s/components/tool-bar.js
My suggestion is to add named tooltips on hover buttons.
also, do we need highlighting of an active button?
=> chore(I3S-Debug): add tool bar functionality

examples/website/i3s/components/debug-panel.js
Before fix while scrolling:
After fix while scrolling:
=> Fix toggle buttons I3S-Debug-App

examples/website/i3s/components/debug-panel.js, examples/website/i3s/components/semantic-validator.js
=> I3s-Debug-App - Fix semantic validator layout

examples/website/i3s/components/debug-panel.js, examples/website/i3s/components/semantic-validator.js
Before fix there is no scroll:
After fix scrol for debug panel is available:
=> I3S-Debug-App - Fix debug panel layout

examples/website/3d-tiles/app.js, examples/website/i3s/app-debug.js, examples/website/i3s/app.js, examples/website/pointcloud/app.js
https://deck.gl/docs/whats-new#improved-experience-on-mobile-devices
=> chore(examples): add inertia flag to deck.gl controller

test/size/import-nothing.js
I'm not sure do we need this fix :)
=> fix(test): remove wrong import

examples/website/i3s/app-debug.js, examples/website/i3s/components/map-info.js, examples/website/i3s/components/tool-bar.js, examples/website/i3s/index.html, examples/website/i3s/package.json
- Fixed toolbar layout
- Moved ArcGIS link to Info panel
- Cleanup code
=> I3S-Debug-App - Fix toolbar layout

modules/geotiff/package.json, modules/textures/package.json, modules/zarr/package.json
=> chore(textures): remove unnecessary dependencies

modules/loader-utils/src/types.ts, modules/mvt/src/helpers/binary-util-functions.ts, modules/mvt/src/helpers/mapbox-util-functions.ts, modules/mvt/src/lib/binary-vector-tile/features-to-binary.ts, modules/mvt/src/lib/binary-vector-tile/vector-tile-layer.ts, modules/mvt/src/lib/mapbox-vector-tile/vector-tile-layer.ts, modules/tiles/src/tileset/tile-3d.ts, modules/tiles/src/tileset/tileset-3d.ts
I've re-done https://github.com/visgl/loaders.gl/pull/1723 on latest master
=> chore: fix lint warnings

docs/table-of-contents.json, docs/whats-new.md, modules/json/docs/README.md
Update website to include NDJSONLoader https://github.com/visgl/loaders.gl/pull/1813
=> Add NDJSONLoader to docs

examples/website/gltf/components/examples.js, examples/website/gltf/components/model-picker.js, examples/website/gltf/package.json, modules/gltf/package.json, modules/gltf/src/lib/parsers/parse-gltf.ts
=> feat(gltf): parse basis textures

modules/3d-tiles/package.json, modules/arrow/package.json, modules/gltf/package.json, modules/i3s/package.json, modules/kml/package.json, modules/ply/package.json, modules/schema/package.json, modules/tile-converter/package.json, modules/tiles/package.json, modules/zip/package.json, yarn.lock
Having multiple copies of core is bad.
=> Consistently use core as peer dependency

examples/website/i3s/app.js, examples/website/i3s/components/building-explorer.js, examples/website/i3s/components/checkbox.js, examples/website/i3s/components/control-panel.js, examples/website/i3s/components/debug-panel.js, examples/website/i3s/components/tile-validator.js, examples/website/i3s/helpers/sublayers.js, yarn.lock
=> feat(examples): i3s - building explorer ui

modules/tile-converter/src/i3s-converter/helpers/geometry-converter.js, modules/tile-converter/src/i3s-converter/i3s-converter.ts, yarn.lock
* Use Tiles3DLoader instead of CesiumIonLoader for local datasets;
* Fill uv0 and color with 0 instead of return 0-length array.
=> chore(tile-converter): use Tiles3DLoader for local data

test/apps/typescript-test/package.json, test/apps/typescript-test/yarn.lock, yarn.lock
husky in "typescript-test" application sets commit hooks that is not good for test application.
=> chrore(test-apps): remove husky

website/package.json, website/yarn.lock
Fixes website build by including https://github.com/uber-web/ocular/pull/379
=> fix(website): gatsby-theme-ocular@1.2.5 ignores .tsconfig.json

modules/3d-tiles/src/lib/constants.ts, modules/3d-tiles/src/lib/parsers/parse-3d-tile-gltf.js, modules/3d-tiles/src/lib/parsers/parse-3d-tile-header.ts, modules/3d-tiles/src/lib/parsers/parse-3d-tile.ts
=> feat(3d-tiles): content glTF extension

docs/specifications/category-gis.md
=> feat(gis): Update gis category docs

examples/get-started/get-started-vite/app.ts, examples/get-started/get-started-vite/index.html, examples/get-started/get-started-vite/package.json, examples/get-started/get-started-vite/tsconfig.json, examples/get-started/get-started-vite/vite.config.ts, yarn.lock
@belom88 You may want to consider moving your examples to vite for a better (faster) dev experience.
=> feat(examples): Add vite example

.prettierignore, docs/table-of-contents.json, docs/whats-new.md, modules/flatgeobuf/docs/README.md, modules/flatgeobuf/docs/api-reference/flatgeobuf-loader.md, modules/flatgeobuf/package.json, modules/flatgeobuf/src/index.ts, modules/flatgeobuf/src/lib/binary-geometries.ts, modules/flatgeobuf/src/lib/parse-flatgeobuf.ts, modules/flatgeobuf/test/flatgeobuf-loader.spec.js, modules/mvt/docs/README.md, modules/shapefile/src/lib/parsers/parse-shapefile.ts, yarn.lock
@kylebarron as part of wrapping up 3.1 work, I took the liberty of squashing and rebasing your flatgeobuf PR #884 .
=> feat(flatgeobuf): Binary parsing

modules/polyfills/src/node/fetch/utils/decode-data-uri.node.ts, modules/polyfills/src/node/fetch/utils/stream-utils.node.ts
Perf collapsed due to repeated copying of chunks.
=> fix(polyfills): Fix slow performance in response.arrayBuffer()

modules/shapefile/test/shapefile.bench.js, test/bench/browser.js, test/bench/modules.js
@kylebarron This is a WIP to see if we can improve the parsing speed.
=> chore(shapefile): add benchmarks

examples/website/i3s/deckgl/mesh-layer/mesh-layer-vertex.glsl.js, examples/website/i3s/deckgl/mesh-layer/mesh-layer.js
=> fix(i3s): repeating textures (uv0>1 || uv0<0)

examples/website/i3s/app-debug.js, examples/website/i3s/app.js, examples/website/i3s/components/debug-panel.js
=> feat(i3s-debug-app): add terrain layer

docs/whats-new.md, modules/pcd/docs/api-reference/pcd-loader.md, modules/pcd/src/lib/decompress-lzf.ts, modules/pcd/src/lib/parse-pcd.ts
We got a situation to parse compressed binary PCD data and this should work.
=> feat: pcd loader support for compressed binary data

modules/textures/src/lib/encoders/encode-texture.ts
=> fix: Avoid using __dirname in texture-encoder

modules/terrain/package.json, modules/terrain/src/lib/parse-terrain.ts, modules/terrain/src/terrain-loader.ts, modules/terrain/src/workers/quantized-mesh-worker.js, modules/terrain/src/workers/terrain-worker.js
Force `parse` to choose the ImageLoader
=> TerrainLoader support for more image formats

modules/tile-converter/src/i3s-converter/i3s-converter.ts
@belom88 @dryabinin-actionengine Fix for #2047
=> fixed duplicated texture output

modules/mvt/src/lib/binary-vector-tile/vector-tile-feature.ts, modules/mvt/test/mvt-loader.spec.js
Fix for underlying issue in https://github.com/visgl/deck.gl/issues/6528
=> Fix MVTLoader bug when WGS84 is used

examples/website/i3s/app-debug.js, examples/website/i3s/app.js, modules/tiles/src/tileset/helpers/zoom.ts, modules/tiles/src/tileset/tileset-3d.ts, modules/tiles/src/types.ts, yarn.lock
Projection meaning:
`projection = zmin * tan(pitch)`
Calculate longitude offset and latitude offset having distance and bearing angle:
`[longitude offset] = projection * sin(bearing)`
`[latitude offset] = projection * cos(bearing)`
=> fix(tiles): init zoom calculation

modules/compression/package.json, modules/compression/test/compression.spec.js, modules/worker-utils/src/lib/worker-farm/worker-farm.ts, yarn.lock
Partially unblocked worker tests for compression module.
TODO: Need to unblock - 'zstd#worker' it has an issue:
=> chore(compression): unblock tests

modules/tiles/src/tileset/helpers/frame-state.ts, modules/tiles/src/tileset/helpers/i3s-lod.ts, modules/tiles/src/tileset/tile-3d.ts, modules/tiles/src/tileset/tileset-3d.ts
* tileset traversal debounce;
* i3s-lod optimization;
* `maximumTilesSelected` option
=> perf(tiles): traversal debounce, i3s-lod optimization

examples/experimental/3d-tiles-with-three.js/threejs-3d-tiles/three-tileset.js
=> fix(examples): 3d-tiles-with-three Tileset3D import

modules/draco/package.json, modules/draco/src/draco-writer-nodejs.ts, modules/draco/src/index.ts, modules/draco/src/workers/draco-writer-nodejs-worker.ts, modules/draco/src/workers/draco-writer-worker.ts, modules/draco/test/draco-writer.spec.js, modules/draco/test/test-utils/copyTypedArray.js, modules/draco/tsconfig.json
I created 2 workers: for NodeJS and for Browser. The worker for a web browser doesn't work because of `importScripts`-related issue.
=> feat(draco): writer worker

docs/whats-new.md
Fixes are taken from here - https://github.com/BinomialLLC/basis_universal/commit/7a2094b807fcd8eb8e505d8c48a19b0690fd3404
=> chore(textures): update what's new in basis_universal

modules/las/src/lib/parse-las.ts, modules/las/test/las-loader.spec.js, website/package.json, website/yarn.lock
* Pointcloud example is broken by: https://github.com/visgl/loaders.gl/pull/1808 ;
* 3DTiles example is broken by: https://github.com/visgl/loaders.gl/pull/2057;
* GLTF example is broken by: https://github.com/visgl/loaders.gl/pull/2016 (/website/yarn.lock)
=> fix(website): broken examples

modules/gltf/src/lib/api/normalize-gltf-v1.ts
https://github.com/visgl/loaders.gl/issues/2125#issuecomment-1104953667
=> fix(gltf): v1 texture normalization

modules/tiles/src/tileset/tileset-3d.ts
=> chore(statistics): add vertex count statistics

modules/tile-converter/src/i3s-converter/i3s-converter.ts, modules/tile-converter/src/i3s-converter/json-templates/layers.ts, modules/tile-converter/test/i3s-converter/i3s-converter.spec.js
Issue https://github.com/visgl/loaders.gl/issues/2122
=> chore(tile-converter): full extent appears in json file

modules/tiles/src/tileset/tileset-3d.ts
Fix for https://github.com/visgl/deck.gl/issues/6871
=> fix(tiles): isLoaded criteria

modules/tiles/src/tileset/tileset-3d.ts
Fixes failing tests caused by https://github.com/visgl/loaders.gl/pull/2118
=> fix(tileset-3d): node in node page calculation issue

modules/i3s/src/i3s-content-loader.ts, modules/i3s/src/i3s-loader.ts, modules/i3s/src/lib/parsers/parse-i3s-tile-content.ts, modules/i3s/src/lib/parsers/parse-i3s.ts, modules/i3s/src/types.ts, modules/tiles/src/tileset/tile-3d.ts
Issue https://github.com/visgl/loaders.gl/issues/1118
=> pass i3s loader only required options

modules/video/src/lib/gifshot/gifshot.ts, yarn.lock
=> fix(video) ReferenceError: navigator is not defined

website/yarn.lock, yarn.lock
I reverted https://github.com/visgl/loaders.gl/pull/2192 . I breaks the website
=> fix(website): revert breaking commit

modules/i3s/src/index.ts, modules/i3s/src/types.ts
Also fixed one type.
Spec - https://github.com/Esri/i3s-spec/blob/master/docs/1.8/histogram.cmn.md
=> chore(i3s): export more types

modules/textures/src/lib/parsers/parse-npy.ts
- Add check that buffer is long enough when parsing NPY
- Improved return type
=> NPY: Add check that buffer is long enough

docs/whats-new.md, modules/arrow/package.json, modules/arrow/src/arrow-loader.ts, modules/arrow/src/lib/arrow-table-batch.ts, modules/arrow/src/lib/encode-arrow.ts, modules/arrow/src/lib/parse-arrow-in-batches.ts, modules/arrow/src/lib/parse-arrow-sync.ts, modules/arrow/test/arrow-loader.spec.js, modules/las/package.json, modules/parquet/package.json, modules/parquet/test/parquet-wasm-loader.spec.ts, modules/schema/src/category/mesh/convert-mesh.ts, modules/schema/src/category/mesh/mesh-to-arrow-table.ts, modules/schema/src/category/table/table-types.ts, modules/schema/src/lib/arrow/arrow-type-utils.ts, yarn.lock
=> chore(arrow): bump apache-arrow to 9.0.0

modules/shapefile/src/lib/parsers/parse-dbf.ts
Ignore TS7053 error in `parseRow` function to fix #2263.
=> fix(Shapefile): Ignore TS7053 in parseRow function

modules/core/src/lib/api/register-loaders.ts
Match the type with the code behavior
=> Update type for registerLoaders to accept a single Loader

examples/website/3d-tiles/app.js, website/yarn.lock, yarn.lock
Cesium changed URL format. Now 3DTilesLoader examples are broken on loaders.gl
=> fix(examples): 3d-tiles CesiumION URL

.prettierignore, modules/tile-converter/package.json, modules/wms/src/lib/wms/parse-wms.ts, package.json, yarn.lock
=> fix(tile-converter): Mark join-images as --external to avoid bundling

examples/website/wms/app.tsx, examples/website/wms/components/control-panel.jsx
- small styling change to ControlPanel to help with long metadata
- a loading image indicator that will alleviate the height jump
=> feat(wms): example site styling

.github/workflows/test.yml
=> chore: Upgrade github actions to v3

modules/i3s/docs/api-reference/i3s-loader.md
Fixed links in **Load I3S tileset and render with deck.gl** sub-chapter
=> docs(i3s): update i3s-loader.md

modules/wms/test/services/wms-service.spec.ts, modules/wms/test/test-utils/fetch-spy.ts
For https://github.com/visgl/deck.gl/issues/7747
=> feat(wms): Pass through authorization load options

examples/website/wms/package.json, website/package.json
https://github.com/visgl/loaders.gl/pull/2419#issuecomment-1513215382
=> update monaco deps in example and website

examples/website/i3s/src/components/attributes-panel.jsx, examples/website/i3s/src/components/attributes-tooltip.jsx, examples/website/i3s/src/components/control-panel.jsx, examples/website/i3s/src/components/semantic-validator.jsx, examples/website/i3s/src/components/styles.jsx, examples/website/pointcloud/components/control-panel.jsx, website/docusaurus.config.js, website/src/examples/i3s-debug.mdx, website/src/examples/i3s.mdx, website/src/examples/pointcloud.mdx, website/src/examples/textures.mdx, website/src/examples/wms.mdx, website/src/styles.css
- Fix link to github
- i3s debug ui issues
- fix height of examples
- pointcloud: font color (dark theme)
Before 
After
Before
After
=> fix(website): minor style issues

examples/website/geospatial/components/control-panel.jsx, examples/website/wms/components/control-panel.tsx
=> fix(wms-example): height of side panel

examples/website/i3s/src/app-debug.tsx
=> fix(website): i3s debug stats issue

examples/website/i3s/src/app.tsx, examples/website/i3s/src/examples.js, website/src/pages/index.jsx, website/src/styles.css
- Add hero example
- Add bullets
- Fix style of the background image 
Note: change color of main title?
maybe white or light grey title with dark basemap in the background
Mobile (iPhone 12)
Tablet (iPad Pro)
=> feat(website): add hero example

modules/wms/src/index.ts, modules/wms/src/lib/sources/image-source.ts
Address https://github.com/visgl/deck.gl/pull/7870
=> fix(wms): fix type exports

modules/tiles/src/constants.ts, modules/tiles/src/tileset/tile-3d.ts, modules/tiles/src/tileset/tileset-3d.ts
First step in long overdue overhaul of the tiles module.
=> chore(tiles): Improved typing for Tile3D, Tileset3D

docs/modules/wms/api-reference/wms-capabilities-loader.md, docs/modules/wms/formats/wms.md, examples/website/wms/app.tsx, examples/website/wms/examples.ts, modules/wms/src/lib/parsers/wms/parse-wms-capabilities.ts, yarn.lock
=> feat(wms): Support for layer dimension metadata

modules/tiles/src/tileset/tileset-traverser.ts
That is a blind fix. We will make a patch after landing it
=> fix(tiles): isLoaded has breaking change

CHANGELOG.md, docs/upgrade-guide.md, docs/whats-new.mdx, modules/tiles/src/tileset/tileset-3d.ts
@belom88 This could be cherry picked back to master.
=> docs: Upgrade guide for `WMSCapabilities`, link to CHANGELOG for patch releases

modules/i3s/package.json
For https://github.com/visgl/loaders.gl/issues/2477#issue-1711907789
=> Add missing md5 to i3s module

modules/3d-tiles/package.json
=> [3d-tiles] Fix peer dependency version

docs/modules/tile-converter/cli-reference/supported-features.md
Suggest to fix some typos, wording.
Merge all or some of them
=> docs: fix typo(s) in tile-converter supported features

docs/modules/gltf/README.md, docs/modules/gltf/formats/gltf.md, modules/gltf/src/index.ts, modules/gltf/src/lib/extensions/deprecated/EXT_feature_metadata.ts, modules/gltf/src/lib/types/gltf-json-schema.ts, modules/gltf/src/lib/types/gltf-types.ts, modules/tile-converter/src/i3s-converter/helpers/batch-ids-extensions.ts, modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts
Fix comments from https://github.com/visgl/loaders.gl/pull/2511
=> fix(gltf): 3D tiles extension types & docs

modules/kml/package.json, modules/wms/package.json, modules/xml/package.json, yarn.lock
=> fix: Bump and remove @xmldom/xmldom (input validation issue)

modules/tiles/src/tileset/tileset-traverser.ts
Fix for https://github.com/visgl/deck.gl/issues/7955
=> Handle empty childless tiles in TilesetTraverser

modules/core/src/lib/loader-utils/get-fetch-function.ts
Regression came in #2573 
* CesiumION datasets don't work
=> fix(core): fetchOptions regression

modules/compression/src/lib/deflate-compression.ts
Contains part of https://github.com/visgl/loaders.gl/pull/2578
I need it in order to uncompress files with deflation from 3tz
=> chore(compression): Added raw mode for deflate-compresion module

modules/zip/src/parse-zip/cd-file-header.ts, modules/zip/src/parse-zip/end-of-central-directory.ts, modules/zip/src/parse-zip/local-file-header.ts
Contains part of https://github.com/visgl/loaders.gl/pull/2578
Need compression method info since we have to deal with top level compression in 3tz
=> chore(zip): Compression method added for local header

modules/loader-utils/src/lib/node/fs.browser.ts, modules/loader-utils/src/lib/node/stream.browser.ts
=> Fix import error in some bundlers

modules/images/src/image-loader.ts, modules/images/src/lib/parsers/parse-image.ts, modules/images/src/lib/parsers/parse-to-image-bitmap.ts, modules/images/src/lib/parsers/parse-to-image.ts, modules/images/src/lib/parsers/parse-to-node-image.ts, modules/images/src/lib/texture-api/load-image.ts, modules/wms/src/lib/services/ogc/wms-service.ts
=> chore: Clean up module imports, remove default exports in images module

lerna.json
4.0 is starting to come together, we'll switch into beta track and focus on stabilization.
=> Move master to 4.0-beta tags

modules/tile-converter/Dockerfile
docker container build had been broken without his change, looks like converter.min extension has been changed everywhere except dockerfile
=> fix(tile-converter): dockerfile fix

modules/i3s/package.json, modules/i3s/src/lib/parsers/constants.ts
Fixes https://github.com/visgl/loaders.gl/issues/2725
=> fix(i3s): Remove luma.gl dependency

test/render/index.js
=> [bug] fix render test import

docs/modules/gltf/formats/gltf.md
- EXT_structural_metadata added.
- EXT_mesh_features moved to ready state.
=> docs(gltf): extension support

docs/modules/pmtiles/api-reference/pmtiles-source.md, docs/modules/pmtiles/formats/pmtiles.md, docs/modules/shapefile/formats/shapefile.md
@vojtatom Added a geometry table to the ShapefileLoader docs, you can change the last row if you add MultiPatch support.
=> chore: Improve Shapefile format doc

modules/3d-tiles/package.json, modules/i3s/package.json, modules/tile-converter/package.json, modules/tiles/package.json
=> chore: fix 4.0 peer dependencies

modules/3d-tiles/test/index.ts
Looks like these can be uncommented without issue?
=> fix(3d-tiles): Enable Tiles3DLoader tests

docs/docs-sidebar.json, docs/modules/las/README.md, docs/modules/las/api-reference/las-loader.md, docs/modules/las/formats/las.md, docs/modules/mvt/formats/mvt.md, docs/modules/mvt/formats/tilejson.md, modules/las/src/index.ts, modules/las/src/las-loader.ts
Doc updates as suggested by @sguergachi in #591
=> docs(las): Mark LAS v1.4 as not supported

examples/website/geospatial/examples.ts, modules/parquet/src/index.ts, modules/parquet/src/lib/parsers/get-parquet-schema.ts, modules/parquet/src/lib/parsers/parse-geoparquet.ts, modules/parquet/src/lib/parsers/parse-parquet-to-columns.ts, modules/parquet/src/lib/parsers/parse-parquet.ts, modules/parquet/src/lib/wasm/encode-parquet-wasm.ts, modules/parquet/src/lib/wasm/load-wasm-browser.ts, modules/parquet/src/lib/wasm/load-wasm-node.ts, modules/parquet/src/lib/wasm/load-wasm.ts, modules/parquet/src/lib/wasm/parse-parquet-wasm.ts, modules/parquet/src/parquet-loader.ts, modules/parquet/src/parquet-wasm-loader.ts, modules/parquet/src/workers/parquet-worker.ts
=> chore(parquet): GeoParquetLoader, collect the parquet loader zoo in one file

modules/bson/src/lib/encoders/encode-bson.ts, modules/bson/src/lib/parsers/parse-bson.ts
=> fix(bson): webpack bson bundling issue

examples/website/tiles/app.tsx, modules/mvt/src/lib/parse-tilejson.ts, modules/mvt/src/mvt-source.ts, modules/mvt/src/tilejson-loader.ts, modules/mvt/test/tilejson-loader.spec.ts, modules/pmtiles/src/lib/parse-pmtiles.ts, modules/pmtiles/src/pmtiles-source.ts
- Incorrect handling of maxValues option fixed (uniqueValues weren't included unless it was set)
=> fix(mvt): TileJSONLoader options.maxValues default

docs/modules/pmtiles/formats/pmtiles.md, docs/whats-new.mdx, modules/pmtiles/package.json, modules/pmtiles/src/lib/parse-pmtiles.ts, yarn.lock
- Upgrade to pmtiles JS library v3
- Update docs with information from @bdon
=> feat(pmtiles): Upgrade to pmtiles v3

modules/gltf/src/lib/extensions/KHR_texture_transform.ts
Currently the implementation of KHR_texture_transform assumes that the scene uses KHR_texture_transform anywhere, then every TextureInfo will have that extension property. That condition is not guaranteed, and fails in the case reported at https://github.com/visgl/deck.gl/issues/8355. 
Related:
- Fixes https://github.com/visgl/deck.gl/issues/8355
=> fix(gltf): Fix for scenes with KHR_texture_transform on some but not all TextureInfos

examples/website/geospatial/examples.ts, modules/wkt/src/lib/parse-wkb.ts, yarn.lock
=> Revert "fix(wkt): multipolygons UInt16 overflow"

modules/csv/src/csv-loader.ts
=> fix(csv): CSVLoader return type

modules/loader-utils/src/loader-types.ts, yarn.lock
deck.gl defines some loaders that would require small changes if we didn't make this optional.
=> fix(loader-utils): Do not require dataType and batchType on loaders.

CHANGELOG.md, lerna.json, package.json, yarn.lock
Lerna wants to publish `"examples/website/tiles" with this change in the root `package.json`. Is this expected behavior?
=> fix: prepare 4.3.0-alpha

examples/website/tiles/app.tsx, examples/website/tiles/components/tile-source-layer.ts, examples/website/tiles/examples.ts, modules/core/src/lib/api/select-loader.ts, modules/core/src/lib/init.ts, modules/core/src/lib/utils/log.ts, modules/loader-utils/src/index.ts, modules/loader-utils/src/lib/log-utils/log.ts, modules/loader-utils/src/lib/sources/image-tile-source.ts, modules/loader-utils/src/lib/sources/tile-source-adapter.ts, modules/loader-utils/src/lib/sources/tile-source.ts, modules/loader-utils/src/lib/sources/vector-tile-source.ts, modules/mvt/src/lib/parse-tilejson.ts, modules/mvt/src/lib/utils/geometry-utils.ts, modules/mvt/src/lib/vector-tile/vector-tile-feature.ts, modules/mvt/src/mvt-source.ts, modules/mvt/src/table-tile-source.ts, modules/pmtiles/src/pmtiles-source.ts, modules/wms/src/services/ogc/wms-service.ts, package.json, yarn.lock
`TileSourceLayer` can now use MVTLayer for better vector tile rendering.
=> example: TileSourceLayer can now render MVTLayer

website/package.json
=> Revert "chore: Bump volta to node@20"

modules/core/test/javascript-utils/text-encoder.spec.ts, modules/polyfills/package.json, modules/polyfills/src/crypto/node-hash.ts, modules/polyfills/src/fetch/decode-data-uri.ts, modules/polyfills/src/fetch/utils/decode-data-uri.node.ts, modules/polyfills/src/file/blob-stream-controller.ts, modules/polyfills/src/file/blob-stream.ts, modules/polyfills/src/file/blob.ts, modules/polyfills/src/file/file-reader.ts, modules/polyfills/src/file/file.ts, modules/polyfills/src/file/install-blob-polyfills.ts, modules/polyfills/src/file/install-file-polyfills.ts, modules/polyfills/src/file/readable-stream.ts, modules/polyfills/src/index.ts, modules/polyfills/test/fetch-node/fetch.node.spec.js, yarn.lock
Attempt a fix by back tracking yarn.lock
=> fix: ReadableStream

examples/website/geospatial/app.tsx
The examples have been affected by https://github.com/visgl/loaders.gl/commit/916d3e2019c3f8b128df17177ccaaef55075e80a
=> fix(examples): geoparquet tooltips

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Per[ oboarding checklist,](https://github.com/openjs-foundation/project-status/issues/65) updates loaders.gl code of conduct to match openjs/vis.gl
=> Add Open.js Code Of Conduct File

modules/tile-converter/src/converter-cli.ts, modules/tile-converter/src/i3s-converter/helpers/coordinate-converter.ts, modules/tile-converter/src/i3s-converter/helpers/geometry-converter.ts, modules/tile-converter/src/i3s-converter/i3s-converter.ts
Added an option not to use Geod transformation via the EGM file when converting 3d tiles to i3s
=> feat(tile-converter): Option not to use Geod transformation

modules/terrain/package.json
Ref #3035 
I have added an export to the terrain-worker, since I needed that.
Thanks!
=> fix(terrain): Add terrain-worker.js bundle to exports path

docs/upgrade-guide.md, docs/whats-new.mdx, examples/website/geospatial/app.tsx, modules/core/src/lib/api/encode.ts, modules/core/src/lib/api/load.ts, modules/core/src/lib/api/parse-in-batches.ts, modules/core/src/lib/api/parse-sync.ts, modules/core/src/lib/api/parse.ts, modules/core/src/lib/api/register-loaders.ts, modules/loader-utils/src/index.ts, modules/loader-utils/src/loader-types.ts, modules/loader-utils/src/writer-types.ts, modules/textures/src/basis-loader.ts, modules/textures/src/compressed-texture-loader.ts, modules/textures/src/lib/parsers/parse-basis.ts
Deduce correct option and return types when multiple loaders are specified.
=> feat(core): Type inference for arrays of loader objects
